[package]
name = "gunbc-lib-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Transport operations and executors for gunbc I/O"

[dependencies]
gunbc-ir = { path = "../../0_foundation/ir" }
gunbc-exec = { path = "../../7_execute/exec" }
serde_json = { workspace = true }
glob = { workspace = true }
ureq = { workspace = true }

[dev-dependencies]
gunbc-test = { path = "../../9_test/test" }
