//! Pragma operations.
//!
//! All I/O happens through explicit `TransportOps::Execute` nodes in the DAG.
//! The ops here are PURE (no I/O) - they render pragma artifacts.

use gunbc_exec::{ExecError, Executable, OutputMap};
use gunbc_ir::Value;
use std::collections::HashMap;

use crate::policy::pragma::{
    clippy_renderer, render_disallowed_methods_allowlist, render_pragma_lint_policy,
};

/// Operations for the pragma tool.
///
/// All operations are PURE - no I/O. I/O happens via TransportOps::Execute nodes.
#[derive(Debug, Clone)]
pub enum PragmaOp {
    /// Render clippy.toml content (PURE)
    RenderClippy,
    /// Render disallowed-methods allowlist content (PURE)
    RenderAllowlist,
    /// Render pragma lint policy content (PURE)
    RenderLintPolicy,
}

impl Executable for PragmaOp {
    fn execute(
        &self,
        _inputs: HashMap<String, Value>,
    ) -> Result<HashMap<String, Value>, ExecError> {
        match self {
            PragmaOp::RenderClippy => {
                let content = clippy_renderer().render();
                OutputMap::new()
                    .str("content", content.clone())
                    .str("return", content)
                    .ok()
            }
            PragmaOp::RenderAllowlist => {
                let content = render_disallowed_methods_allowlist();
                OutputMap::new()
                    .str("content", content.clone())
                    .str("return", content)
                    .ok()
            }
            PragmaOp::RenderLintPolicy => {
                let content = render_pragma_lint_policy();
                OutputMap::new()
                    .str("content", content.clone())
                    .str("return", content)
                    .ok()
            }
        }
    }
}

// Mockable implementation for test generation
use gunbc_test::Mockable;

impl Mockable for PragmaOp {
    fn mock_outputs(&self) -> HashMap<String, Value> {
        match self {
            PragmaOp::RenderClippy => OutputMap::new()
                .str("content", "# Mock clippy.toml")
                .str("return", "# Mock clippy.toml")
                .build(),
            PragmaOp::RenderAllowlist => OutputMap::new()
                .str("content", "# Mock allowlist")
                .str("return", "# Mock allowlist")
                .build(),
            PragmaOp::RenderLintPolicy => OutputMap::new()
                .str("content", "# Mock lint policy")
                .str("return", "# Mock lint policy")
                .build(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_clippy() {
        let result = PragmaOp::RenderClippy.execute(HashMap::new()).unwrap();
        match result.get("content") {
            Some(Value::Str(content)) => {
                assert!(content.contains("disallowed-methods"));
            }
            _ => panic!("expected clippy content"),
        }
    }

    #[test]
    fn test_render_allowlist() {
        let result = PragmaOp::RenderAllowlist.execute(HashMap::new()).unwrap();
        match result.get("content") {
            Some(Value::Str(content)) => {
                assert!(content.contains("Generated by gunbc-pragma"));
            }
            _ => panic!("expected allowlist content"),
        }
    }

    #[test]
    fn test_render_lint_policy() {
        let result = PragmaOp::RenderLintPolicy.execute(HashMap::new()).unwrap();
        match result.get("content") {
            Some(Value::Str(content)) => {
                assert!(content.contains("Generated by gunbc-pragma"));
            }
            _ => panic!("expected lint policy content"),
        }
    }
}
