use std::collections::HashMap;

use gunbc_exec::{ExecError, Executable, Value};
use gunbc_file_exec::compute_hash;
use gunbc_ir::transport::file::FileOp;

use crate::types::GitignoreConfig;

/// The operation type for gitignoregen nodes.
#[derive(Debug, Clone)]
pub enum GitignoreOp {
    /// Initialize context from config
    Context { config: GitignoreConfig },
    /// Compose final .gitignore content (Pure)
    ComposeGitignore,
    /// Shared file upsert operations
    File(FileOp),
}

/// The gitignore content template.
const GITIGNORE_CONTENT: &str = r#"# Build artifacts — reproducible from source
/target/
/vendor/
/buck-out/

# Editor/IDE state
.idea/
.vscode/
*.swp
*.swo
*~

# OS metadata
.DS_Store
Thumbs.db

# Secrets / local config
.env
.env.local
.env.*.local
"#;

impl Executable for GitignoreOp {
    fn execute(&self, inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
        match self {
            GitignoreOp::Context { config } => {
                let abs_path = std::fs::canonicalize(&config.workspace_path)
                    .unwrap_or_else(|_| std::path::PathBuf::from(&config.workspace_path));
                let file_path = abs_path.join(&config.output_path);
                let input_hash = compute_hash(GITIGNORE_CONTENT);
                let mut out = HashMap::new();
                out.insert(
                    "file_path".into(),
                    Value::Str(file_path.to_string_lossy().into_owned()),
                );
                out.insert("force".into(), Value::Bool(config.force));
                out.insert("input_hash".into(), Value::Str(input_hash));
                Ok(out)
            }

            GitignoreOp::ComposeGitignore => {
                let hash = inputs
                    .get("input_hash")
                    .and_then(|v| if let Value::Str(s) = v { Some(s.clone()) } else { None })
                    .unwrap_or_else(|| "unknown".into());

                let content = format!(
                    "# Generated by gunbc-gitignoregen\n# Hash: {hash}\n\n{GITIGNORE_CONTENT}"
                );

                let mut out = HashMap::new();
                out.insert("content".into(), Value::Str(content));
                Ok(out)
            }
            GitignoreOp::File(op) => op.execute(inputs),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn context_sets_paths() {
        let config = GitignoreConfig {
            workspace_path: ".".into(),
            output_path: ".gitignore".into(),
            force: false,
        };
        let op = GitignoreOp::Context { config };
        let out = op.execute(HashMap::new()).unwrap();
        assert!(matches!(out.get("file_path"), Some(Value::Str(_))));
        assert!(matches!(out.get("input_hash"), Some(Value::Str(_))));
    }

    #[test]
    fn compose_gitignore_includes_hash() {
        let mut inputs = HashMap::new();
        inputs.insert("input_hash".into(), Value::Str("abc123".into()));

        let op = GitignoreOp::ComposeGitignore;
        let out = op.execute(inputs).unwrap();
        if let Value::Str(content) = &out["content"] {
            assert!(content.contains("# Hash: abc123"));
            assert!(content.contains("/target/"));
            assert!(content.contains(".DS_Store"));
        } else {
            panic!("expected Str");
        }
    }

    // FileOp behavior is covered by gunbc-file-exec tests.
}
