[package]
name = "gunbc-lib-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Transport operations and executors for gunbc I/O"

[dependencies]
gunbc-ir = { path = "../../core/ir" }
gunbc-exec = { path = "../../core/exec" }
serde_json = { workspace = true }
glob = { workspace = true }

[dev-dependencies]
gunbc-test = { path = "../../core/test" }
