//! Generated by regen_stage0 -- do not edit.
//!
//! Layered core crate in the derived stage0 partition.
//!
//! Owns its module bodies via path includes and re-exports lower partition
//! crates so `crate::` references in generated modules keep resolving.

#![allow(
    unused_imports,
    unused_variables,
    unused_mut,
    unused_parens,
    dead_code,
    non_shorthand_field_patterns,
    suspicious_double_ref_op,
    clippy::all
)]
#![deny(unreachable_patterns)]
#![recursion_limit = "256"]

pub use v1_stage0_runtime::*;

#[rustfmt::skip]
#[path = "../../stage0/src/std_content_hash.rs"]
pub mod std_content_hash;
#[rustfmt::skip]
#[path = "../../stage0/src/std_coercion.rs"]
pub mod std_coercion;
#[rustfmt::skip]
#[path = "../../stage0/src/std_currency.rs"]
pub mod std_currency;
#[rustfmt::skip]
#[path = "../../stage0/src/std_decl_ref.rs"]
pub mod std_decl_ref;
#[rustfmt::skip]
#[path = "../../stage0/src/std_disposition.rs"]
pub mod std_disposition;
#[rustfmt::skip]
#[path = "../../stage0/src/std_error_primitives.rs"]
pub mod std_error_primitives;
#[rustfmt::skip]
#[path = "../../stage0/src/std_http_path.rs"]
pub mod std_http_path;
#[rustfmt::skip]
#[path = "../../stage0/src/std_emit_model.rs"]
pub mod std_emit_model;
#[rustfmt::skip]
#[path = "../../stage0/src/std_magnitude.rs"]
pub mod std_magnitude;
#[rustfmt::skip]
#[path = "../../stage0/src/std_measure.rs"]
pub mod std_measure;
#[rustfmt::skip]
#[path = "../../stage0/src/std_types.rs"]
pub mod std_types;
#[rustfmt::skip]
#[path = "../../stage0/src/std_lens_verdict.rs"]
pub mod std_lens_verdict;
#[rustfmt::skip]
#[path = "../../stage0/src/std_algebra.rs"]
pub mod std_algebra;
#[rustfmt::skip]
#[path = "../../stage0/src/std_nat.rs"]
pub mod std_nat;
#[rustfmt::skip]
#[path = "../../stage0/src/std_node.rs"]
pub mod std_node;
#[rustfmt::skip]
#[path = "../../stage0/src/std_syntax.rs"]
pub mod std_syntax;
#[rustfmt::skip]
#[path = "../../stage0/src/std_computation.rs"]
pub mod std_computation;
#[rustfmt::skip]
#[path = "../../stage0/src/std_termination.rs"]
pub mod std_termination;
#[rustfmt::skip]
#[path = "../../stage0/src/std_induction.rs"]
pub mod std_induction;
#[rustfmt::skip]
#[path = "../../stage0/src/std_iteration.rs"]
pub mod std_iteration;
#[rustfmt::skip]
#[path = "../../stage0/src/std_graph.rs"]
pub mod std_graph;
#[rustfmt::skip]
#[path = "../../stage0/src/v1_std_core.rs"]
pub mod v1_std_core;
