set -euo pipefail
# GENERATED RETRACT by dag/gunbc/live_deploy/emit.dag host=srv1
# owned-artifacts only — ensured deps (tailscale, tmux) intentionally NOT purged
# Wave C envelope: shared deploy_apply_preamble_shell — retract also installs/refreshes
# /etc/sudoers.d/gunbc-deploy (idempotent; first retract-after-flip may be the dropin install).
# Principal: UNPRIVILEGED ci-runner. dispatch-worktrees teardown is rm -d (granted rm,
# empty-dir only): live worktrees fail it LOUDLY — the same empty-dir refusal wall.
_gunbc_stage="$(mktemp -d)"
trap 'rm -rf "$_gunbc_stage"' EXIT
# deploy-access-bootstrap-preflight (principal + historical roster grants)
_gunbc_principal="$(whoami)"
if [ "$_gunbc_principal" != "ghrunner" ]; then
  echo "deploy_access: typed refusal before mutation — principal mismatch expected=ghrunner actual=$_gunbc_principal"
  exit 1
fi
sudo -n /usr/bin/apt-get --help >/dev/null || { echo "deploy_access: typed refusal before mutation — privileged commands not granted (sudo -n preflight miss)"; exit 1; }
sudo -n /usr/bin/install --version >/dev/null || { echo "deploy_access: typed refusal before mutation — privileged commands not granted (sudo -n preflight miss)"; exit 1; }
sudo -n /usr/bin/systemctl --version >/dev/null || { echo "deploy_access: typed refusal before mutation — privileged commands not granted (sudo -n preflight miss)"; exit 1; }
sudo -n -l /usr/bin/tailscale >/dev/null 2>&1 || { echo "deploy_access: typed refusal before mutation — privileged command not in sudoers (sudo -l preflight miss)"; exit 1; }
sudo -n /usr/bin/rm --version >/dev/null || { echo "deploy_access: typed refusal before mutation — privileged commands not granted (sudo -n preflight miss)"; exit 1; }
cat > "$_gunbc_stage/gunbc-deploy.sudoers" <<'GUNBC_SUDOERS_EOF'
# GENERATED by dag/gunbc/ci_deploy_sudoers.dag — do not hand-edit
ghrunner ALL=(ALL) NOPASSWD: /usr/bin/apt-get
ghrunner ALL=(ALL) NOPASSWD: /usr/bin/install
ghrunner ALL=(ALL) NOPASSWD: /usr/bin/systemctl
ghrunner ALL=(ALL) NOPASSWD: /usr/bin/tailscale
ghrunner ALL=(ALL) NOPASSWD: /usr/bin/rm
GUNBC_SUDOERS_EOF
sudo -n visudo -cf "$_gunbc_stage/gunbc-deploy.sudoers"
sudo -n install -m 0440 "$_gunbc_stage/gunbc-deploy.sudoers" /etc/sudoers.d/gunbc-deploy
sudo -n visudo -cf /etc/sudoers.d/gunbc-deploy
echo "deploy-access-preflight: PASS principal=ghrunner"
sudo -n tailscale serve reset || true
sudo -n systemctl disable --now gunbc-roadmap.service 2>/dev/null || true
sudo -n rm -f /etc/systemd/system/gunbc-roadmap.service
sudo -n systemctl daemon-reload
sudo -n rm -d /opt/gunbc/dispatch-worktrees
sudo -n rm -f /opt/gunbc/bin/gunbc
sudo -n rm -f /etc/systemd/system/gunbc-tree-sync.service /etc/gunbc-tree-sync.env
sudo -n systemctl daemon-reload
sudo -n rm -rf /opt/gunbc/gunbc
echo live-deploy-receipt host=srv1 fold=retract verdict=converged