// Generated tests for bootstrap_generated_tests DAG.
//
// Generated by gunbc-testgen
// DO NOT EDIT - regenerate with: make testgen

use gunbc_exec::{execute_with_mode, BoundaryMocks, ExecutionMode};
use gunbc_ir::{detect_boundaries, Cardinality, Value};
use gunbc_test::{assert_boundary_mockable, assert_types_compatible, default_mocks};
use gunbc_test::{ResourceAcquireResult, ResourceSimulation};

// ============================================================================
// Flow Verification Tests
// These tests execute the full DAG in DryRun mode with mocked transport
// responses, verifying that pure node logic produces expected outputs.
// ============================================================================

/// Flow verification: bootstrap scenario.
///
/// Builds the DAG, injects mocked transport responses via DryRun,
/// and verifies that the pure node chain produces expected terminal outputs.
#[test]
fn test_flow_bootstrap() {
    let dag = crate::build_bootstrap_graph().unwrap();
    let spec = mock_spec();
    let mocks = spec.to_boundary_mocks();
    let log = execute_with_mode(&dag, ExecutionMode::DryRun(mocks))
        .expect("DryRun execution should succeed");

    // Verify parse_scan_result.crate_count
    let entry = log.get("parse_scan_result").expect("node 'parse_scan_result' should be in execution log");
    assert_eq!(
        entry.outputs.get("crate_count").expect("port 'crate_count' should exist on 'parse_scan_result'"),
        &Value::Int(2),
        "flow verification: parse_scan_result.crate_count mismatch"
    );

}

// ============================================================================
// Resource Simulation Tests
// These tests verify behavior under different resource acquisition scenarios.
// ============================================================================

/// Test resource 'fs:Makefile' (Lock) acquisition.
#[test]
fn test_resource_fs_makefile_acquire() {
    let spec = mock_spec();
    let resource = spec.get_resource("fs:Makefile").expect("resource should exist");
    let result = resource.acquire();
    assert!(matches!(result, ResourceAcquireResult::Acquired), "should acquire successfully");
}

/// Test resource 'fs:.gitignore' (Lock) acquisition.
#[test]
fn test_resource_fs_gitignore_acquire() {
    let spec = mock_spec();
    let resource = spec.get_resource("fs:.gitignore").expect("resource should exist");
    let result = resource.acquire();
    assert!(matches!(result, ResourceAcquireResult::Acquired), "should acquire successfully");
}

