[package]
name = "gunbc-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared code generation utilities for gunbc"

[dependencies]
gunbc-infra = { path = "../infra" }
gunbc-ir = { path = "../ir" }
gunbc-test = { path = "../test" }
gunbc-exec = { path = "../exec" }
gunbc-cli = { path = "../cli" }
daglang-derive = { path = "../daglang/daglang-derive" }
daglang-driver = { path = "../daglang/daglang-driver" }
daglang-lower = { path = "../daglang/daglang-lower" }
serde_json = { workspace = true }
