[package]
name = "gunbc-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared code generation utilities for gunbc"

[dependencies]
gunbc-infra = { path = "../infra" }
gunbc-ir = { path = "../ir" }
gunbc-test = { path = "../test" }
gunbc-exec = { path = "../exec" }
gunbc-cli = { path = "../cli" }
gunbc-clippy = { path = "../../lib/tools/clippy" }
serde_json = { workspace = true }
cargo_metadata = "0.18"
toml_edit = "0.22"

[[bin]]
name = "gunbc-codegen"
path = "src/main.rs"
