[package]
name = "gunbc-lib-gist-ops"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Gist operations library for gunbc DAGs"

[dependencies]
gunbc-ir = { path = "../../core/ir" }
gunbc-exec = { path = "../../core/exec" }
gunbc-lib-transport = { path = "../transport" }

[dev-dependencies]
gunbc-test = { path = "../../core/test" }
