[package]
name = "gunbc-delegate-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Derive macros for delegating Executable/Mockable enum wrappers"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2", features = ["full", "derive"] }

[dev-dependencies]
gunbc-exec = { path = "../exec" }
gunbc-ir = { path = "../ir" }
gunbc-test = { path = "../test" }
