[package]
name = "v1-stage0-core"
version = "0.1.0"
edition = "2021"
[features]
default = []
text_lookup_work_counter = []


[dependencies]
stacker = "0.1"
im-rc = { version = "15.1", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
unicode-ident = "1"
unicode-properties = { version = "0.1", features = ["emoji"] }
