[package]
name = "ci_workflow_ratchet"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
ci_affected_components = { path = "../ci_affected_components" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
v3-compiler = { path = "../../src/v3/compiler" }

[dev-dependencies]
v3-compiler = { path = "../../src/v3/compiler" }
