[package]
name = "v1-compiler-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Integration tests for the v2 self-hosted compiler"

[dependencies]
im-rc = { version = "15.1", features = ["serde"] }
v1-compiler = { path = "../stage0", features = ["text_lookup_work_counter", "interp_test_witness"] }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
