[package]
name = "gunbc-gistgen"
version = "0.1.0"
edition = "2021"

[lib]
name = "gunbc_gistgen"
path = "src/lib.rs"

[dependencies]
gunbc-ir = { path = "../gunbc-ir" }
gunbc-exec = { path = "../gunbc-exec" }
gunbc-test = { path = "../gunbc-test" }
gunbc-contracts = { path = "../gunbc-contracts" }
gunbc-spec = { path = "../gunbc-spec" }
ignore = "0.4"
globset = "0.4"
serde_json = "1"
tempfile = "3"

[dev-dependencies]
gunbc-codegen = { path = "../gunbc-codegen" }
