[package]
name = "gunbc-lib-aws-ops"
version = "0.1.0"
edition = "2021"

[dependencies]
gunbc-exec = { path = "../../core/exec" }
gunbc-delegate-macros = { path = "../../core/delegate-macros" }
gunbc-ir = { path = "../../core/ir" }
gunbc-test = { path = "../../core/test" }
gunbc-testgen-registry = { path = "../../core/testgen-registry" }
gunbc-testgen-registry-macros = { path = "../../core/testgen-registry-macros" }
serde = { workspace = true }
serde_json = { workspace = true }
