//! Bootstrap operations.

use gunbc_codegen::FileWriter;
use gunbc_exec::{ExecError, Executable};
use gunbc_ir::Value;
use std::collections::HashMap;

/// Operations for the bootstrap tool.
#[derive(Debug, Clone)]
pub enum BootstrapOp {
    /// Scan workspace for crates
    ScanWorkspace,
    /// Generate Makefile content
    GenerateMakefile,
    /// Generate .gitignore content
    GenerateGitignore,
    /// Write all generated files (boundary)
    WriteFiles,
}

impl Executable for BootstrapOp {
    fn execute(&self, inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
        match self {
            BootstrapOp::ScanWorkspace => execute_scan_workspace(inputs),
            BootstrapOp::GenerateMakefile => execute_generate_makefile(inputs),
            BootstrapOp::GenerateGitignore => execute_generate_gitignore(inputs),
            BootstrapOp::WriteFiles => execute_write_files(inputs),
        }
    }
}

/// Scan workspace for crate information.
fn execute_scan_workspace(_inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
    // Find all crates in the workspace
    let crates_dir = std::path::Path::new("crates");
    let mut crate_names = Vec::new();

    if crates_dir.exists() {
        if let Ok(entries) = std::fs::read_dir(crates_dir) {
            for entry in entries.flatten() {
                if entry.path().is_dir() {
                    if let Some(name) = entry.file_name().to_str() {
                        crate_names.push(name.to_string());
                    }
                }
            }
        }
    }

    crate_names.sort();

    let mut out = HashMap::new();
    out.insert("crate_count".to_string(), Value::Int(crate_names.len() as i64));
    out.insert("crate_names".to_string(), Value::StrList(crate_names));
    Ok(out)
}

/// Generate Makefile content.
fn execute_generate_makefile(_inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
    let makefile = r#"# Generated by gunbc-bootstrap
# Regenerate with: make bootstrap

.DEFAULT_GOAL := help

.PHONY: help build test lint ci gist buck2 makegen deps bootstrap

help:
	@echo "gunbc - DAG-based code generation framework"
	@echo ""
	@echo "Development:"
	@echo "  build       Build all targets"
	@echo "  test        Run all tests"
	@echo "  lint        Run clippy"
	@echo "  ci          Run full CI pipeline"
	@echo ""
	@echo "Tools:"
	@echo "  gist        Create GitHub gist from code"
	@echo "  buck2       Generate BUCK file"
	@echo "  makegen     Regenerate this Makefile"
	@echo "  deps        Install/check dependencies"
	@echo "  bootstrap   Regenerate all build infrastructure"

build:
	cargo build --all-targets

test:
	cargo test

lint:
	cargo clippy --all-targets -- -D warnings

ci:
	cargo run -p gunbc-ci -- run

gist:
	cargo run -p gunbc-gist -- $(if $(REPO),--repo $(REPO)) $(if $(EXT),-e $(EXT))

gist-dry:
	cargo run -p gunbc-gist -- --dry-run $(if $(REPO),--repo $(REPO))

buck2:
	cargo run -p gunbc-buck2 -- $(if $(INPUT),--input $(INPUT))

buck2-dry:
	cargo run -p gunbc-buck2 -- --dry-run

makegen:
	cargo run -p gunbc-makegen

makegen-dry:
	cargo run -p gunbc-makegen -- --dry-run

deps:
	cargo run -p gunbc-deps -- install

deps-list:
	cargo run -p gunbc-deps -- --list

bootstrap:
	cargo run -p gunbc-bootstrap

bootstrap-dry:
	cargo run -p gunbc-bootstrap -- --dry-run
"#;

    let mut out = HashMap::new();
    out.insert("makefile_content".to_string(), Value::Str(makefile.to_string()));
    Ok(out)
}

/// Generate .gitignore content.
fn execute_generate_gitignore(_inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
    let gitignore = r#"# Generated by gunbc-bootstrap

# Rust
/target/
**/*.rs.bk
Cargo.lock

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Build artifacts
*.o
*.a
*.so
*.dylib

# Generated files (keep these tracked)
# Makefile
# .github/workflows/ci.yml
"#;

    let mut out = HashMap::new();
    out.insert("gitignore_content".to_string(), Value::Str(gitignore.to_string()));
    Ok(out)
}

/// Write all generated files.
fn execute_write_files(inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
    let writer = FileWriter::real();
    let mut files_written = Vec::new();

    // Write Makefile
    if let Some(Value::Str(content)) = inputs.get("makefile_content") {
        let result = writer
            .write_if_changed("Makefile", content)
            .map_err(|e| ExecError::new(format!("failed to write Makefile: {}", e)))?;
        if result.changed {
            files_written.push("Makefile".to_string());
        }
    }

    // Write .gitignore
    if let Some(Value::Str(content)) = inputs.get("gitignore_content") {
        let result = writer
            .write_if_changed(".gitignore", content)
            .map_err(|e| ExecError::new(format!("failed to write .gitignore: {}", e)))?;
        if result.changed {
            files_written.push(".gitignore".to_string());
        }
    }

    let mut out = HashMap::new();
    out.insert(
        "files_written".to_string(),
        Value::StrList(files_written.clone()),
    );
    out.insert(
        "write_count".to_string(),
        Value::Int(files_written.len() as i64),
    );
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_makefile() {
        let result = execute_generate_makefile(HashMap::new()).unwrap();

        match result.get("makefile_content") {
            Some(Value::Str(content)) => {
                assert!(content.contains("build:"));
                assert!(content.contains("test:"));
                assert!(content.contains("gist:"));
            }
            _ => panic!("expected makefile content"),
        }
    }

    #[test]
    fn test_generate_gitignore() {
        let result = execute_generate_gitignore(HashMap::new()).unwrap();

        match result.get("gitignore_content") {
            Some(Value::Str(content)) => {
                assert!(content.contains("/target/"));
                assert!(content.contains(".DS_Store"));
            }
            _ => panic!("expected gitignore content"),
        }
    }
}
