[package]
name = "v1_compiler"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
im = { version = "15.1", features = ["serde"] }
unicode-ident = "1"
unicode-properties = { version = "0.1", features = ["emoji"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
stacker = "0.1"
clap = { version = "4", features = ["derive"] }
lazy_static = "1"
ureq = { version = "2", features = ["json"] }
