// Cargo.toml
// src/compiler_tests.rs
// src/emitted_population.rs
// src/extdeps_cargo.rs
// src/extdeps_cargo_version.rs
// src/extdeps_container_oci_digest.rs
// src/extdeps_external_authority.rs
// src/extdeps_languages_dag_emit.rs
// src/extdeps_languages_dag_syntax.rs
// src/extdeps_languages_dag_types.rs
// src/extdeps_languages_go_emit.rs
// src/extdeps_languages_go_syntax.rs
// src/extdeps_languages_go_types.rs
// src/extdeps_languages_python_emit.rs
// src/extdeps_languages_python_syntax.rs
// src/extdeps_languages_python_types.rs
// src/extdeps_languages_rust_capabilities.rs
// src/extdeps_languages_rust_derive_contracts.rs
// src/extdeps_languages_rust_emit.rs
// src/extdeps_languages_rust_syntax.rs
// src/extdeps_languages_rust_types.rs
// src/extdeps_units_dimensionless.rs
// src/extdeps_units_iec_80000_13.rs
// src/extdeps_units_iso8601.rs
// src/extdeps_units_iso_80000_3.rs
// src/extdeps_uri.rs
// src/extdeps_uri_path.rs
// src/extdeps_version.rs
// src/extdeps_version_semver.rs
// src/gunbc_rust_decl_type_overlay.rs
// src/gunbc_stage0_crate_layout_generated.rs
// src/gunbc_stage0_crate_partition_generated.rs
// src/gunbc_stage0_emitted_population_manifest.rs
// src/lib.rs
// src/main.rs
// src/std_algebra.rs
// src/std_checked_arithmetic.rs
// src/std_coercion.rs
// src/std_computation.rs
// src/std_constructors.rs
// src/std_content_hash.rs
// src/std_currency.rs
// src/std_decl_ref.rs
// src/std_disposition.rs
// src/std_dissolution.rs
// src/std_effects.rs
// src/std_emit_model.rs
// src/std_error_primitives.rs
// src/std_execution_mode.rs
// src/std_graph.rs
// src/std_http_path.rs
// src/std_induction.rs
// src/std_integer.rs
// src/std_interface_summary.rs
// src/std_keyed_roster.rs
// src/std_keyed_row.rs
// src/std_logic.rs
// src/std_machine_constraints.rs
// src/std_magnitude.rs
// src/std_measure.rs
// src/std_nat.rs
// src/std_node.rs
// src/std_occurrence_binding.rs
// src/std_occurrence_binding_candidates.rs
// src/std_occurrence_binding_resolve.rs
// src/std_occurrence_identity.rs
// src/std_pareto.rs
// src/std_primitive_projection.rs
// src/std_process_termination.rs
// src/std_realization_schedule.rs
// src/std_reference_binding_observation.rs
// src/std_roster_frontier.rs
// src/std_serialization.rs
// src/std_source_annotation.rs
// src/std_syntax.rs
// src/std_termination.rs
// src/std_trait_derive_shape.rs
// src/std_types.rs
// src/std_unicode_types.rs
// src/std_witness_admission.rs
// src/v1_compiler_annotation_bind.rs
// src/v1_compiler_artifact.rs
// src/v1_compiler_closure_stub_v2_std_integer_rust.rs
// src/v1_compiler_closure_stub_v2_std_text_rust.rs
// src/v1_compiler_coercion.rs
// src/v1_compiler_compile.rs
// src/v1_compiler_compiler_tests_rust.rs
// src/v1_compiler_complexity.rs
// src/v1_compiler_dag_collect.rs
// src/v1_compiler_dag_collect_support.rs
// src/v1_compiler_effect_derivation.rs
// src/v1_compiler_emit.rs
// src/v1_compiler_emit_core_support.rs
// src/v1_compiler_emit_go.rs
// src/v1_compiler_emit_python.rs
// src/v1_compiler_emit_rust.rs
// src/v1_compiler_expected_red_roster_join.rs
// src/v1_compiler_frontend_observation.rs
// src/v1_compiler_infer.rs
// src/v1_compiler_infer_access.rs
// src/v1_compiler_infer_cycle.rs
// src/v1_compiler_infer_emit_info.rs
// src/v1_compiler_infer_env.rs
// src/v1_compiler_infer_items.rs
// src/v1_compiler_infer_lookup.rs
// src/v1_compiler_infer_method.rs
// src/v1_compiler_infer_occurrence_binding.rs
// src/v1_compiler_infer_patterns.rs
// src/v1_compiler_infer_resolve.rs
// src/v1_compiler_infer_service.rs
// src/v1_compiler_infer_sigs.rs
// src/v1_compiler_infer_types.rs
// src/v1_compiler_languages.rs
// src/v1_compiler_normalize.rs
// src/v1_compiler_ownership.rs
// src/v1_compiler_parse.rs
// src/v1_compiler_resolve.rs
// src/v1_compiler_runtime_go.rs
// src/v1_compiler_runtime_rust.rs
// src/v1_compiler_stage0_crates.rs
// src/v1_compiler_tokenize.rs
// src/v1_compiler_trace.rs
// src/v1_compiler_trait_bound_witness.rs
// src/v1_compiler_trait_derive_emit.rs
// src/v1_compiler_type_head_exposure.rs
// src/v1_compiler_workspace_members.rs
// src/v1_gunbc_namespace_reference_derived_closure_production_observations.rs
// src/v1_gunbc_occurrence_binding_parser_walk.rs
// src/v1_probe_emit_interp.rs
// src/v1_rt.rs
// src/v1_std_core.rs
// src/v1_test_non_ascii_perf_fixture.rs
// src/v1_tests_claim_checkpoint_identity_keying_witness_test.rs
// src/v1_tests_claim_resolved_call_emission_identity_internal_witness_test.rs
// src/v1_tests_claim_transport_roster_closure_witness_test.rs
// src/wt_a.rs
// src/wt_b.rs
// src/wt_common.rs
