// Generated by v1 compiler -- do not edit.

#![allow(unused_parens, clippy::all, clippy::disallowed_macros)]

use clap::{Parser, Subcommand};

use im::HashMap;
use std::rc::Rc;
use v1_compiler::cli_run;
use v1_compiler::v1_compiler_compile;
use v1_compiler::v1_compiler_compile::PipelineResult;
use v1_compiler::v1_rt;
use v1_compiler::v1_std_core::{
    byte_to_line_col, diagnostic_to_message, diagnostic_to_span, source_line_at, NewlineIndex,
};

#[derive(Subcommand)]
enum RetainedCommands {
    /// Compile .dag source files to a target language
    Compile {
        /// Source root directories (searched recursively for .dag files).
        /// Module imports are resolved transitively from these roots.
        #[arg(long = "source-root")]
        source_roots: Vec<String>,
        /// Legacy: single source directory (all .dag files loaded, no import resolution)
        #[arg(long = "source-dir")]
        source_dir: Option<String>,
        #[arg(long)]
        output_dir: String,
        /// Target language: rust, python, go, dag, or + separated set such as rust+dag
        #[arg(long, default_value = "rust")]
        target: String,
        #[arg(long = "dependency-pool-index", default_value = "strict")]
        dependency_pool_index: String,
        /// Entry `.dag` file: compile only this module and its transitive imports
        /// (not every `.dag` file under the first --source-root). Scopes the compile
        /// to a subtree so a small closure can be emitted without a whole-tree pass.
        #[arg(long)]
        entry: Option<String>,
    },

    /// Run one target by its absolute label and report the standing its own producer
    /// answers in. The label is exact: a target PATTERN refuses, and an unbound or
    /// unknown target refuses rather than reporting a pass.
    Test {
        /// Absolute label of exactly one target, e.g.
        /// `//gunbc/instruments:heads-reading-differential`.
        #[arg(value_name = "LABEL")]
        target: String,
    },

    /// Execute a .dag program directly (interpreter)
    Run {
        /// Source root directories (searched recursively for .dag files)
        #[arg(long = "source-root")]
        source_roots: Vec<String>,
        /// Entry function to execute (default: "main")
        #[arg(long, default_value = "main")]
        function: String,
        /// Entry `.dag` file: load only this module and its transitive imports
        /// (not every file under --source-root). Required for scoped TestClaim runs.
        #[arg(long)]
        entry: Option<String>,
        /// TestClaim / witness run: Bool false → exit 1; requires --entry
        #[arg(long)]
        claim_run: bool,
        /// Named argument for the entry function, repeatable: `--arg name=value`.
        /// Values enter as String; a missing `=` refuses rather than guessing.
        #[arg(long = "arg")]
        args: Vec<String>,
    },

    /// Long-running HTTP server: compile once, then answer each request by
    /// calling ONE .dag entry `fn(method, path, body) -> ServeWireResponse`.
    /// The seam is parse/write only — routing and handlers live in .dag.
    Serve {
        /// Source root directories (searched recursively for .dag files)
        #[arg(long = "source-root")]
        source_roots: Vec<String>,
        /// Entry `.dag` file: load only this module and its transitive imports
        #[arg(long)]
        entry: String,
        /// Handler function: fn(method: String, path: String, body: String) -> ServeWireResponse
        #[arg(long)]
        function: String,
        #[arg(long, default_value = "127.0.0.1")]
        host: String,
        #[arg(long, default_value = "8080")]
        port: u16,
        /// Release revision this process serves, bound ONCE at startup and immutable for the
        /// process lifetime. Required and validated before the listener binds: `gunbc serve`
        /// compiles its graph once, so the launch argument is the only fact describing what
        /// this PROCESS serves; re-reading a file, an env var, or git HEAD per request would
        /// report mutable disk state wearing a process-shaped interface. Published through
        /// /healthz beside the served-surface identity (gunbc.running_release_identity).
        #[arg(long = "release-revision")]
        release_revision: String,
        /// Per-request THREAD-CPU evaluation budget in milliseconds. Omitted means this process
        /// declares no CPU bound -- today's behavior, stated. Deliberately no default: no
        /// measurement of normal `roadmap_serve_handle` evaluation cost exists, and the one
        /// adjacent figure (~70s cold graph compile) gives no reason to believe a sub-second
        /// ceiling is safe, so an invented value would risk refusing legitimate requests.
        #[arg(long = "eval-budget-cpu-ms")]
        eval_budget_cpu_ms: Option<u64>,
        /// Per-request MONOTONIC-WALL evaluation budget in milliseconds. Separate from the CPU
        /// bound because they catch different failures: CPU catches a spin, wall catches a stall
        /// that holds the listener while consuming almost no CPU. Neither contains an evaluation
        /// blocked inside a single native primitive -- that needs worker isolation.
        #[arg(long = "eval-budget-wall-ms")]
        eval_budget_wall_ms: Option<u64>,
    },
}

/// cargo's build-output dir (a `target` dir beside a `Cargo.toml`) is realization output, not
/// source: a corpus copy materialized under it must never enter a module index alongside the
/// tree it was copied from. A source root passed FROM inside `target/` is still walked -- only
/// DESCENT into the output dir is refused.
fn is_cargo_target_output_dir(parent: &std::path::Path, child: &std::path::Path) -> bool {
    child.file_name().and_then(|n| n.to_str()) == Some("target")
        && parent.join("Cargo.toml").is_file()
}

/// Recursively find all .dag files under a directory.
/// Fail-closed: panics on unreadable directory entries.
///
/// THE GUARD BELOW IS RESTORED FROM THE COPY THIS CUT DELETES: `cli_run`'s `collect_dag_files`
/// carried the target-dir refusal and this one did not, so the dying copy was the SAFER one.
/// Deleting `cli_run` without moving the guard would have lowered safety by deletion -- the one
/// outcome delete-first must not produce.
///
/// Without it, a whole-root compile (the no-`--entry` branch, which calls this) walks into
/// `target/` and ingests emitted or materialized `.dag` as SOURCE beside the tree it was copied
/// from: duplicate module paths, resolved by collision panic or silent shadowing.
///
/// RUNG, HONESTLY: this restores a guard, it does not prove a live bug -- `find target -name
/// '*.dag'` returns 0 in this worktree today. The hazard is evidenced by the deleted code's own
/// comment naming its case: a corpus copy under `target/func_env_semantic_baseline_corpus/dag/**`.
fn collect_dag_files(dir: &std::path::Path, files: &mut Vec<std::path::PathBuf>) {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read dir {:?}: {}", dir, e))
        .map(|e| e.unwrap_or_else(|e| panic!("failed to read dir entry in {:?}: {}", dir, e)))
        .collect();
    entries.sort_by_key(|e| e.file_name());
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            if is_cargo_target_output_dir(dir, &path) {
                continue;
            }
            collect_dag_files(&path, files);
        } else if path.extension().map(|e| e == "dag").unwrap_or(false) {
            files.push(path);
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum DependencyPoolIndex {
    Strict,
    PrimaryPrecedence,
}

fn parse_dependency_pool_index(value: &str) -> DependencyPoolIndex {
    match value {
        "strict" => DependencyPoolIndex::Strict,
        "primary-precedence" => DependencyPoolIndex::PrimaryPrecedence,
        other => {
            eprintln!(
                "unknown --dependency-pool-index: {} (expected strict | primary-precedence)",
                other
            );
            std::process::exit(1);
        }
    }
}

// SEVEN FUNCTIONS WERE DELETED HERE AND THE COMPILER IS WHAT FOUND THEM.
//
// `extract_module_path`, `report_moduleless_dag_entry_skips`, `extract_import_paths`,
// `insert_module_path`, `index_source_root`, `build_module_index` and
// `resolve_transitively_with_seen` were this handler's private module-indexing and
// import-walking machinery. Routing the whole-root subject through `cli_run::compile_emission`
// left each with no caller -- DESIGN's delete-first doctrine, the deletion BEING the census.
// Surviving authorities are `cli_run`'s: `extract_module_path`, `extract_import_paths`,
// `build_multi_entry_index*` and `resolve_transitively_bfs_legacy`.
//
// AN EARLIER REVISION OF THIS NOTE CLAIMED THE MODULE-LESS SKIP REPORT HAD NO COUNTERPART THERE.
// False, corrected rather than dropped because a note asserting an ABSENCE is the claim a later
// reader will not re-check: `report_moduleless_dag_entry_skips` and `moduleless_dag_entry_paths`
// are both `pub` in `cli_run`, both carry tests, neither was deleted, and the behaviour is wired
// into the transaction's `PrimaryRoot` arm through them -- nothing lost, no second authority.

fn render_target_from_name(
    target: &str,
) -> Option<v1_compiler::v1_compiler_artifact::RenderTarget> {
    match target {
        "rust" => Some(v1_compiler::v1_compiler_artifact::RenderTarget::Rust),
        "python" => Some(v1_compiler::v1_compiler_artifact::RenderTarget::Python),
        "go" => Some(v1_compiler::v1_compiler_artifact::RenderTarget::Go),
        "dag" => Some(v1_compiler::v1_compiler_artifact::RenderTarget::Dag),
        _ => None,
    }
}

/// THE PARSE RETURNS TARGETS, NOT (NAME, TARGET) PAIRS. The authored spelling is discarded
/// deliberately: it is recoverable through `cli_run::render_target_name`, this function's
/// inverse, and keeping both would let a caller carry a name that disagrees with its target.
fn parse_render_targets(target: &str) -> Vec<v1_compiler::v1_compiler_artifact::RenderTarget> {
    let mut targets = Vec::new();
    for part in target.split('+') {
        let trimmed = part.trim();
        if trimmed.is_empty() {
            continue;
        }
        match render_target_from_name(trimmed) {
            Some(render_target) => targets.push(render_target),
            None => {
                eprintln!(
                    "unknown target: {}. supported: rust, python, go, dag, rust+dag",
                    target
                );
                std::process::exit(1);
            }
        }
    }
    if targets.is_empty() {
        eprintln!("error: --target must name at least one target");
        std::process::exit(1);
    }
    targets
}

/// THE OUTPUT WRITER'S OWN REFUSAL VOCABULARY. Three causes, one per host effect the writer
/// performs, each naming the path it failed on.
///
/// The parent-directory arm had no representation: `create_dir_all(parent).ok()`, then a panic
/// naming the WRITE, so a missing parent was reported as a write failure -- a silent arm feeding
/// a misleading one, the absorbing failure arm DESIGN §5 forbids.
///
/// The form follows `Stage0CargoBinManifestParseRefusal` in `cli_run` (gunbc#9285): a typed
/// refusal with a `Display`, returned by `Result`, the exit taken at the command boundary.
///
/// `v1.05_emit_rust` `emit_main_rs` now emits the same three refusal arms before wiring the
/// candidate compile handler. `main.rs` remains a declared hand-maintained divergence for its
/// other retained host bodies, but executing the emitted compile entry no longer regresses this
/// boundary to panic-or-ignore semantics.
#[derive(Debug, Clone, PartialEq, Eq)]
enum OutputWriteRefusal {
    OutputDirectoryNotCreated {
        path: String,
        cause: String,
    },
    ParentDirectoryNotCreated {
        path: String,
        file: String,
        cause: String,
    },
    FileNotWritten {
        path: String,
        cause: String,
    },
}

impl std::fmt::Display for OutputWriteRefusal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Deliberately not the `refused at {phase}` sentence the compile arms use: that is the
        // COMPILER disowning its output; this is the filesystem refusing output the compiler
        // stands behind.
        write!(f, "gunbc compile: output write refused: ")?;
        match self {
            Self::OutputDirectoryNotCreated { path, cause } => {
                write!(f, "could not create output directory {path}: {cause}")
            }
            Self::ParentDirectoryNotCreated { path, file, cause } => {
                write!(
                    f,
                    "could not create parent directory {path} for {file}: {cause}"
                )
            }
            Self::FileNotWritten { path, cause } => {
                write!(f, "could not write {path}: {cause}")
            }
        }
    }
}

impl OutputWriteRefusal {
    /// THE BOUNDARY TRANSLATION, so no call site decides a status of its own.
    ///
    /// `1` already means "the compile refused, or the arguments were bad". Reusing it would
    /// re-fuse at the exit status -- what a machine consumer reads -- exactly what the typed
    /// refusal above splits at the message. So the writer gets its own, `3`, chosen here only.
    fn verdict(self) -> Verdict {
        Verdict {
            status: 3,
            message: Some(self.to_string()),
        }
    }
}

/// WRITING THE TREE IS A HOST EFFECT, NOT A COMPILE PHASE, AND IT NOW HAS A FAILURE CHANNEL.
///
/// This returned `()`, so two failures could only `panic!` and the third went unreported. At all
/// three call sites the outcome was exit 101, a panic message, and no `compiled:` summary line
/// after a compile that had SUCCEEDED through emit -- which every consumer classifies as a
/// compile failure (`gunbc.emit_diagnostic_observation` reads the absent line as "the compile
/// refused and wrote no tree"). "Your program is wrong" and "this disk would not take the
/// output" have opposite remedies, and the unit return made them one symbol.
fn write_output_files(
    output_dir: &str,
    result: &v1_compiler::v1_compiler_compile::PipelineResult,
) -> Result<(), OutputWriteRefusal> {
    let src_dir = format!("{}/src", output_dir);
    if let Err(e) = std::fs::create_dir_all(&src_dir) {
        return Err(OutputWriteRefusal::OutputDirectoryNotCreated {
            path: src_dir,
            cause: e.to_string(),
        });
    }
    for file in result.files.iter() {
        let out_path = format!("{}/{}", output_dir, file.path);
        if let Some(parent) = std::path::Path::new(&out_path).parent() {
            if let Err(e) = std::fs::create_dir_all(parent) {
                return Err(OutputWriteRefusal::ParentDirectoryNotCreated {
                    path: parent.display().to_string(),
                    file: out_path,
                    cause: e.to_string(),
                });
            }
        }
        if let Err(e) = std::fs::write(&out_path, &*file.content) {
            return Err(OutputWriteRefusal::FileNotWritten {
                path: out_path,
                cause: e.to_string(),
            });
        }
    }
    Ok(())
}

fn main() {
    let cli = v1_compiler::gunbc_cli_dispatch_generated::Cli::parse();
    let host = RetainedCliHost {
        dry_run: cli.dry_run,
    };
    v1_compiler::gunbc_cli_dispatch_generated::dispatch(cli.command, cli.dry_run, &host)
}

struct RetainedCliHost {
    dry_run: bool,
}

impl v1_compiler::gunbc_cli_dispatch_generated::CliDispatchHost for RetainedCliHost {
    fn retained_host_kernel(
        &self,
        source_roots: Vec<String>,
        source_dir: Option<String>,
        output_dir: String,
        target: String,
        dependency_pool_index: String,
        entry: Option<String>,
    ) -> ! {
        retained_dispatch(
            RetainedCommands::Compile {
                source_roots,
                source_dir,
                output_dir,
                target,
                dependency_pool_index,
                entry,
            },
            self.dry_run,
        )
    }

    fn run_verb(
        &self,
        source_roots: Vec<String>,
        function: String,
        entry: Option<String>,
        claim_run: bool,
        args: Vec<String>,
    ) -> ! {
        retained_dispatch(
            RetainedCommands::Run {
                source_roots,
                function,
                entry,
                claim_run,
                args,
            },
            self.dry_run,
        )
    }

    fn handle_serve(
        &self,
        source_roots: Vec<String>,
        entry: String,
        function: String,
        host: String,
        port: u16,
        release_revision: String,
        eval_budget_cpu_ms: Option<u64>,
        eval_budget_wall_ms: Option<u64>,
    ) -> ! {
        retained_dispatch(
            RetainedCommands::Serve {
                source_roots,
                entry,
                function,
                host,
                port,
                release_revision,
                eval_budget_cpu_ms,
                eval_budget_wall_ms,
            },
            self.dry_run,
        )
    }

    fn invoke_bound_target_producer(&self, target: String) -> ! {
        retained_dispatch(RetainedCommands::Test { target }, self.dry_run)
    }
}

fn retained_dispatch(command: RetainedCommands, dry_run: bool) -> ! {
    match command {
        RetainedCommands::Compile {
            source_roots,
            source_dir,
            output_dir,
            target,
            dependency_pool_index,
            entry,
        } => {
            // #6967/§13 silent-pick piggyback: drain resolution silent-pick
            // telemetry over this same compile. This is NOT the join-filtered
            // resolution-divergence census (deleted 2026-08-18 — see
            // gunbc.ci_layer_roots resolution_divergence_silent_pick_gate_retirement_receipt).
            // That path required a second whole-corpus resolve plus parent-plan
            // capture this compile route never had. This is a deliberately narrower,
            // cost-motivated proxy, asymmetric in both directions (review 41032):
            //   - fn_parent_first_hit: red-on-any raw count here (bare reference
            //     resolved by first-hit among multiple parents — containment-ambiguous).
            //   - global_bare_lcp: skipped entirely here (whole-pool name overlap
            //     alone — benign at compile-time scope, not genuine under §13
            //     unique-on-chain).
            // Join-filtered silent-pick divergence detection has no enrolled
            // witness today; the retirement receipt carries the rung drop and
            // rebuild constraints.
            let render_targets = parse_render_targets(&target);
            let pool_index = parse_dependency_pool_index(&dependency_pool_index);

            // -- THE SCOPED SINGLE-TARGET COMPILE IS THE SHARED EMISSION TRANSACTION --
            //
            // This is the invocation the cargo board's producer uses
            // (`docs/probes/curated_cargo_probe_one.sh`), and the SAME FUNCTION the required
            // v2-emission phase calls: `cli_run::compile_entry_emission`. Before, the phase
            // reproduced the closure load, census assembly, refusal check and silent-pick gate
            // beside these, with three parameters kept equal by hand -- a gate drifting from the
            // board's producer can green while the board refuses (DESIGN §3).
            // -- BOTH CLI SUBJECTS REACH THE ONE TRANSACTION --
            //
            // `--entry` compiles that file's reference-derived closure; without it, the first
            // `--source-root` is the primary root and the rest a dependency pool. Until this
            // landed the second case was a SECOND index/load/resolve/admit/compile/refuse
            // pipeline open-coded here, two producers of one fact (DESIGN §3). The handler keeps
            // what is its own: writing the tree, rendering diagnostics, choosing an exit code.
            //
            // THE MULTI-TARGET CASE ROUTES HERE TOO, as of the transaction taking a target
            // VECTOR. Briefly it did not -- a REGRESSION, not a scope statement:
            // `--source-root X --target rust+dag` fell through to the `--source-dir` branch and
            // exited "provide --source-root or --source-dir" over an argv that provided one. The
            // transaction resolves once and emits per target, as the deleted loop did.
            let cli_subject = match (&entry, &source_roots.is_empty()) {
                (Some(entry_path), _) => Some(cli_run::CompileSubject::Entry(entry_path.clone())),
                (None, false) => Some(cli_run::CompileSubject::PrimaryRoot(
                    source_roots[0].clone(),
                )),
                // `--source-dir` (no source roots at all) keeps the legacy flat scan below.
                (None, true) => None,
            };
            if let Some(subject) = cli_subject {
                let multi_target = render_targets.len() > 1;
                let run = cli_run::compile_emission(&cli_run::CompileRequest {
                    subject,
                    source_roots: source_roots.clone(),
                    primary_precedence: matches!(
                        pool_index,
                        DependencyPoolIndex::PrimaryPrecedence
                    ),
                    render_targets: render_targets.clone(),
                });
                match &run.disposition {
                    cli_run::CompileDisposition::NotExecuted {
                        earlier_phase,
                        cause,
                    } => {
                        // The closure/census line is DELIBERATELY not printed: the transaction
                        // never ran, so `resolved 0 sources` would report a resolve that did not
                        // happen as one that found nothing.
                        eprintln!("gunbc compile: {earlier_phase}: {cause}");
                        std::process::exit(1);
                    }
                    cli_run::CompileDisposition::Refused { phase, cause } => {
                        eprintln!(
                            "resolved {} sources ({}), {} indexed modules in the name census only",
                            run.closure_modules,
                            run.subject.scope_receipt().render(),
                            run.census_modules
                        );
                        // The tree is NOT written on a refusal: writing a partial tree the
                        // compiler has disowned is a fabricated plausible output (DESIGN §5).
                        eprintln!("gunbc compile: refused at {phase}: {cause}");
                        for emission in &run.emissions {
                            render_diagnostics(&emission.result);
                        }
                        std::process::exit(1);
                    }
                    cli_run::CompileDisposition::Completed { emitted_count } => {
                        eprintln!(
                            "resolved {} sources ({}), {} indexed modules in the name census only",
                            run.closure_modules,
                            run.subject.scope_receipt().render(),
                            run.census_modules
                        );
                        // NOTHING IS MATERIALIZED UNTIL EVERY TARGET HAS COMPLETED. The
                        // disposition above is over the whole emission set, so reaching here
                        // means no target refused -- a per-target write inside the emit loop
                        // would leave one target's tree on disk beside another's refusal, the
                        // partial fabricated output §5 forbids.
                        //
                        // A single target writes to `output_dir` itself; several write to
                        // `output_dir/<name>`, the layout the deleted loop used and downstream
                        // consumers read.
                        let mut total_diagnostics = 0usize;
                        for emission in &run.emissions {
                            let target_dir = if multi_target {
                                format!("{}/{}", output_dir, emission.target_name)
                            } else {
                                output_dir.clone()
                            };
                            if let Err(refusal) = write_output_files(&target_dir, &emission.result)
                            {
                                refusal.verdict().apply();
                            }
                            if multi_target {
                                eprintln!(
                                    "compiled[{}]: {} files emitted, {} diagnostics",
                                    emission.target_name,
                                    emission.result.files.len(),
                                    emission.result.diagnostics.len()
                                );
                            }
                            render_diagnostics(&emission.result);
                            total_diagnostics += emission.result.diagnostics.len();
                        }
                        eprintln!(
                            "compiled: {} files emitted, {} diagnostics",
                            emitted_count, total_diagnostics
                        );
                        std::process::exit(0);
                    }
                }
            }

            v1_rt::resolution_silent_pick_enable();

            // THE WHOLE-ROOT PIPELINE THAT STOOD HERE IS DELETED, NOT DISABLED: ~200 lines
            // re-implementing indexing, memory admission, entry-set discovery, the import walk,
            // census fill and the refusal check `cli_run::compile_emission` owns. Every
            // `--source-root` invocation routes through the transaction above, so keeping the
            // code would be a second authority kept warm for nothing (DESIGN §3, delete-first).
            //
            // WHAT REMAINS BELOW IS THE `--source-dir` FLAT SCAN AND NOTHING ELSE: a legacy
            // subject with no source roots, index or dependency pool, which the transaction's
            // two subjects do not describe. The remaining fork in this handler, named.
            //
            // THE CENSUS BEHIND "ONE COMPILATION CONCEPT", AT CALL-SITE GRAIN RATHER THAN FILE
            // GRAIN, because a file-grain claim is not checkable and this one was overstated
            // once. Direct calls to the compile kernel (`compile_sources_with_options` /
            // `compile_to_resolved_with_options` / `emit_resolved_for_target`) outside
            // `cli_run::compile_emission`, in non-test code:
            //
            //   - main.rs, this handler, the `--source-dir` arm (3 sites) -- the legacy flat
            //     scan above. A FORK, declared: no root, index or pool for the transaction to
            //     model; terminal form is a third subject or the flag's deletion, and nothing in
            //     the repository passes `--source-dir` today.
            //   - cli_run compile-clean oracle (2 sites) -- deliberately index- and
            //     cache-independent; it exists to disagree with the via-index path.
            //   - cli_run synthesized-resolved emit (1 site) -- emits a `ResolvedPipelineResult`
            //     assembled in memory; no source set for a transaction to take.
            //   - required_regen_host `compile_stage0` (1 site) -- calls `compile_sources` over
            //     `regen_input_sources`. A FORK, declared: its subject is an EXACT SOURCE SET
            //     from the regen roster, neither root nor entry; terminal form is a third
            //     subject (`ExactSourceSet`) carrying the roster as authority. It also passes a
            //     hardcoded refusal subject ("v2 self-compile") the transaction derives itself.
            //
            // THIS CENSUS WAS WRONG ONCE, IN THE DIRECTION THAT FLATTERS: its first revision
            // omitted `required_regen_host`, present in the file-level count and lost in the
            // call-site list transcribed from it. Caught in review. As the floor's own
            // first-execution receipt records: a list transcribed from a wider measurement is
            // not the measurement.
            //
            // NOT a claim that nothing else compiles: test files and witness bins call the
            // kernel directly too, outside this census by scope, not because they were checked.
            let compile_subject = match &source_dir {
                Some(dir) => format!("compile of {dir}"),
                None => "compile".to_string(),
            };
            let census_only_sources: Vec<Rc<v1_compiler_compile::SourceFile>> = Vec::new();
            let sources = if let Some(dir) = source_dir {
                // Legacy: flat directory scan (backward compatibility)
                let mut dag_paths = Vec::new();
                collect_dag_files(std::path::Path::new(&dir), &mut dag_paths);
                let mut sources = Vec::new();
                for path in &dag_paths {
                    let content = std::fs::read_to_string(path)
                        .unwrap_or_else(|e| panic!("failed to read {:?}: {}", path, e));
                    let filename = path.file_name().unwrap().to_string_lossy().to_string();
                    sources.push(Rc::new(v1_compiler_compile::SourceFile {
                        path: filename,
                        content,
                    }));
                }
                eprintln!(
                    "compiling {} .dag files from {} (target: {})",
                    sources.len(),
                    dir,
                    target
                );
                sources
            } else {
                eprintln!("error: provide --source-root or --source-dir");
                std::process::exit(1);
            };

            let pipeline_options = Rc::new(v1_compiler_compile::CompilePipelineOptions {
                analyze_complexity: false,
                census_only_sources: Rc::new(census_only_sources.into()),
            });
            if render_targets.len() == 1 {
                let result = v1_compiler_compile::compile_sources_with_options(
                    Rc::new(sources.into()),
                    render_targets[0].clone(),
                    pipeline_options.clone(),
                );
                if let Some(message) = v1_compiler_compile::stage0_self_compile_refusal_message(
                    compile_subject.clone(),
                    result.clone(),
                ) {
                    eprintln!("{message}");
                    std::process::exit(1);
                }
                if let Err(refusal) = write_output_files(&output_dir, &result) {
                    refusal.verdict().apply();
                }
                eprintln!(
                    "compiled: {} files emitted, {} diagnostics",
                    result.files.len(),
                    result.diagnostics.len()
                );
                render_diagnostics(&result);
                if has_blocking_diagnostics(result.diagnostics.as_ref()) {
                    std::process::exit(1);
                }
            } else {
                let resolved = v1_compiler_compile::compile_to_resolved_with_options(
                    Rc::new(sources.into()),
                    pipeline_options.clone(),
                );
                let mut total_files = 0usize;
                let mut total_diagnostics = 0usize;
                for render_target in render_targets {
                    let name = v1_compiler::cli_run::render_target_name(&render_target);
                    let result = v1_compiler_compile::emit_resolved_for_target(
                        resolved.clone(),
                        render_target,
                    );
                    if let Some(message) = v1_compiler_compile::stage0_self_compile_refusal_message(
                        format!("{compile_subject} [{name}]"),
                        result.clone(),
                    ) {
                        eprintln!("{message}");
                        std::process::exit(1);
                    }
                    let target_output_dir = format!("{}/{}", output_dir, name);
                    if let Err(refusal) = write_output_files(&target_output_dir, &result) {
                        refusal.verdict().apply();
                    }
                    eprintln!(
                        "compiled[{}]: {} files emitted, {} diagnostics",
                        name,
                        result.files.len(),
                        result.diagnostics.len()
                    );
                    render_diagnostics(&result);
                    total_files += result.files.len();
                    total_diagnostics += result.diagnostics.len();
                    if has_blocking_diagnostics(result.diagnostics.as_ref()) {
                        std::process::exit(1);
                    }
                }
                eprintln!(
                    "compiled: {} files emitted, {} diagnostics",
                    total_files, total_diagnostics
                );
            }

            let silent_pick = v1_rt::resolution_silent_pick_disable();
            if !silent_pick.fn_parent_first_hits.is_empty() {
                eprintln!(
                    "SILENT-PICK-GATE: {} fn_parent_first_hit silent pick(s) in this compile (raw-count proxy gate, not the join-filtered resolution_divergence_silent_pick_refusal authority — §13 fail-open — a bare reference resolved by first-hit-among-multiple-parents, i.e. containment-ambiguous):",
                    silent_pick.fn_parent_first_hits.len()
                );
                for site in &silent_pick.fn_parent_first_hits {
                    eprintln!(
                        "  SILENT-PICK-GATE fn_parent_first_hit module={} name={} parent_match_count={} chosen_parent_module={}",
                        site.env_module_path,
                        site.name,
                        site.parent_match_count,
                        site.chosen_parent_module
                    );
                }
                std::process::exit(1);
            }
        }

        // THE FOUR VERB HANDLERS ARE DELETED, AND THIS ARM IS THE DECLARED INTERIM.
        //
        // Their terminal Y is NOT YET MODELLED, and this branch deliberately does not sketch
        // it: a CLI model authored before its consumer exists is shaped by the CLI we have, not
        // the one we are building. Until it lands these verbs have a decoder and no dispatcher.
        //
        // This REFUSES rather than degrading: a typed, located reason and a nonzero exit; no
        // partial run, no guessed default verb, no plausible success. A cut that leaves a verb
        // unimplemented must say so loudly at the boundary -- an absorbing fallback here would
        // be the exact §5 failure this deletion exists to remove.
        //
        // NOT a scaffold with a trigger standing in for a decision: the terminal construction
        // is named, its two halves exist, and the missing piece is the wiring between them.
        RetainedCommands::Run {
            source_roots,
            function,
            entry,
            claim_run,
            args,
        } => run_verb(
            &source_roots,
            &function,
            entry.as_deref(),
            dry_run,
            claim_run,
            &args,
        )
        .apply(),

        // THE TARGET DISPATCH SEAM, AND THE WHOLE ARM IS A CALL.
        //
        // Deliberately no mode switch and no arm per instrument: which producer a label names is
        // decided by the registry in `target_invocation_host`, mirroring
        // `gunbc.instrument_targets`, and the realization is selected one level below. A second
        // instrument adds a row there and nothing here.
        //
        // The status is the producer's own termination, not an aggregate verdict: 0 the reading
        // held, 1 it did not, 2 no reading was taken. `gunbc.build_target`'s
        // `test_standing_verdict` and the Blaze status export are deliberately NOT consulted --
        // each refuses instrument producers by design, so either would answer a question this
        // verb is not asking.
        RetainedCommands::Test { target } => {
            let outcome = cli_run::target_invocation_host::test_verb(&target);
            Verdict {
                status: cli_run::target_invocation_host::invocation_exit_status(
                    outcome.termination,
                ),
                message: Some(outcome.message),
            }
            .apply()
        }

        // `converge` is no longer a retained verb. It is a bootstrap .dag operation on the
        // generated dispatch (gunbc.cli_dispatch_surface gunbc_fleet_converge_operation_binding),
        // the same route `build` takes, so no arm here can answer for it.

        // SERVE IS WIRED AGAIN, AND IT IS A FROZEN QUARRY ROUTE RATHER THAN A DESIGN.
        // #8286 deleted this seam together with converge's, but converge has a successor that
        // EXISTS (the spine above) while serve's declared successor -- gunbc.roadmap_serve
        // roadmap_serve_interpreted_scaffold, dissolving to emit-on-demand of the serve closure
        // -- was never built, so the deletion removed a live outward-facing production route
        // with no minimal Y to hold the boundary. DESIGN section 3 names that carve-out: where
        // no Y can hold a gap-intolerant boundary, X stays FROZEN. This restores X and freezes
        // it.
        //
        // FROZEN MEANS: no new options, verbs, routes into the interpreter, or completion work.
        // The deleted refusal's claim is NOT retracted -- serve is a desired service occurrence
        // that convergence should observe and reconcile, and gunbc.host_effect has no
        // service-occurrence member to express that. This seam runs until it does.
        //
        // The engine objection is recorded, not argued away: this makes the interpreter
        // load-bearing for a capability two lanes are deleting. Not a NEW dependency (it existed
        // until #8286), but if this route attracts completion work the freeze has been repealed
        // by drift.
        RetainedCommands::Serve {
            source_roots,
            entry,
            function,
            host,
            port,
            release_revision,
            eval_budget_cpu_ms,
            eval_budget_wall_ms,
        } => {
            cli_run::handle_serve(
                source_roots,
                entry,
                function,
                host,
                port,
                release_revision,
                cli_run::ServeEvaluationBudget {
                    cpu_limit_ms: eval_budget_cpu_ms,
                    wall_limit_ms: eval_budget_wall_ms,
                },
            );
            Verdict {
                status: 0,
                message: None,
            }
            .apply()
        }
    };
    std::process::exit(0)
}

/// Severity of one diagnostic, as a TOTAL partition.
///
/// The deleted `cli_run` pair asked two independent questions -- `..._is_hard` and an
/// `..._is_advisory` ALLOWLIST -- so a non-blocking variant absent from the allowlist was counted
/// by NEITHER: rendered to the terminal while every reported count read zero for it, the silent
/// wrongness §5 forbids, reachable by adding a variant and forgetting a list. One classification
/// with no third arm makes that unwritable: `hard + advisory == diagnostics.len()` by
/// construction.
///
/// `is_interpreter_blocking_diagnostic` is the whole native answer. `cli_run` differed in one
/// arm -- `UnlistedImportUse`, escalated to blocking via a policy read that reached a full source
/// resolve, entry-graph build and interpreter run: the escape-hatch mechanism this cut removes,
/// a projection owning a compiler invocation. The base predicate already answers `false` there,
/// and import-list enforcement is being deleted at its root, so the override has no referent in
/// the terminal model.
/// A NOTE ON THE PARAMETER TYPE, wrong in both directions before the compiler could speak.
/// `PipelineResult.diagnostics` is declared `Rc<Vec<Rc<ErrorNode>>>`, but
/// `v1_compiler_compile.rs` opens with `use im::{.., Vector as Vec}`, so the field is an
/// `im::Vector`: the declaring file's imports are part of the type. The deleted helpers'
/// `compile_clean_im_vector_*` name was accurate and the signatures were "corrected" away from
/// it on the strength of a declaration that reads as std `Vec`.
enum DiagnosticSeverity {
    Blocking,
    Advisory,
}

fn classify_diagnostic(d: &Rc<v1_compiler::v1_std_core::ErrorNode>) -> DiagnosticSeverity {
    if v1_compiler::v1_std_core::is_interpreter_blocking_diagnostic(d.diagnostic.clone()) {
        DiagnosticSeverity::Blocking
    } else {
        DiagnosticSeverity::Advisory
    }
}

fn blocking_diagnostic_count(
    diagnostics: &im::Vector<Rc<v1_compiler::v1_std_core::ErrorNode>>,
) -> usize {
    diagnostics
        .iter()
        .filter(|d| matches!(classify_diagnostic(d), DiagnosticSeverity::Blocking))
        .count()
}

fn has_blocking_diagnostics(
    diagnostics: &im::Vector<Rc<v1_compiler::v1_std_core::ErrorNode>>,
) -> bool {
    diagnostics
        .iter()
        .any(|d| matches!(classify_diagnostic(d), DiagnosticSeverity::Blocking))
}

fn render_diagnostics(result: &PipelineResult) {
    if result.diagnostics.is_empty() {
        return;
    }

    let index_map: HashMap<String, Rc<NewlineIndex>> = result
        .newline_indices
        .iter()
        .map(|idx| (idx.file.clone(), idx.clone()))
        .collect();

    for d in result.diagnostics.iter() {
        render_one_diagnostic(d, &index_map, "");
    }

    let hard = blocking_diagnostic_count(result.diagnostics.as_ref());
    // Derived, not separately scanned: the two counts partition one population, so they
    // cannot disagree with the total or with each other.
    let advisory = result.diagnostics.len() - hard;
    if advisory > 0 {
        eprintln!(
            "\n{hard} blocking error(s), {advisory} advisory diagnostic(s) (policy: gunbc.compile_clean_diagnostic_policy)"
        );
    } else {
        eprintln!("\n{hard} error(s)");
    }
}

fn render_one_diagnostic(
    d: &Rc<v1_compiler::v1_std_core::ErrorNode>,
    index_map: &HashMap<String, Rc<NewlineIndex>>,
    indent: &str,
) {
    let severity = match classify_diagnostic(d) {
        DiagnosticSeverity::Advisory => "advisory",
        DiagnosticSeverity::Blocking => "error",
    };
    let message = diagnostic_to_message(d.diagnostic.clone());
    let span = diagnostic_to_span(d.diagnostic.clone());

    let location = if !span.file.is_empty() {
        if let Some(idx) = index_map.get(&span.file) {
            let lc = byte_to_line_col(idx.clone(), span.start);
            format!("{}:{}:{}", span.file, lc.line, lc.col)
        } else {
            span.file.clone()
        }
    } else if !d.module_name.is_empty() {
        d.module_name.clone()
    } else {
        String::new()
    };

    if location.is_empty() {
        eprintln!("{}{}: {}", indent, severity, message);
    } else {
        eprintln!("{}{}[{}]: {}", indent, severity, location, message);
    }

    if !span.file.is_empty() {
        if let Some(idx) = index_map.get(&span.file) {
            let lc = byte_to_line_col(idx.clone(), span.start);
            let line_text = source_line_at(idx.clone(), lc.line);
            let line_num = format!("{}", lc.line);
            let gutter_width = line_num.len();
            eprintln!("{} {} |", indent, " ".repeat(gutter_width));
            eprintln!("{} {} | {}", indent, line_num, line_text);

            let span_len = std::cmp::max(1, (span.end - span.start) as usize);
            let col_offset = (lc.col - 1) as usize;
            eprintln!(
                "{} {} | {}{}",
                indent,
                " ".repeat(gutter_width),
                " ".repeat(col_offset),
                "^".repeat(std::cmp::min(
                    span_len,
                    line_text.len().saturating_sub(col_offset)
                ))
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use clap::{CommandFactory, Parser};
    use v1_compiler::gunbc_cli_dispatch_generated::Cli;
    // THE TESTS SURVIVE THE FUNCTION AND ARE RE-POINTED AT THE SURVIVING AUTHORITY. Written
    // against this file's private `extract_module_path`, deleted by the fork closure, they pin
    // `cli_run`'s behaviour and now assert it there. Deleting them with the function would
    // retire the evidence with one of two implementations -- what DESIGN §4b(4) forbids: the
    // redundant machinery goes, the discriminating cases stay enrolled.
    use v1_compiler::cli_run::extract_module_path_public as extract_module_path;

    #[test]
    fn shipped_cli_parses_the_generated_build_surface() {
        assert!(Cli::try_parse_from(["gunbc", "build", "gunbc"]).is_ok());
    }

    #[test]
    fn version_surface_reports_the_exact_source_commit() {
        assert_eq!(
            Cli::command().get_version(),
            Some(env!("GUNBC_BUILD_IDENTITY"))
        );
        let identity = env!("GUNBC_BUILD_IDENTITY");
        let commit = identity.strip_suffix("-dirty").unwrap_or(identity);
        assert_eq!(commit.len(), 40);
        assert!(commit.bytes().all(|byte| byte.is_ascii_hexdigit()));
        assert!(identity == commit || identity == format!("{commit}-dirty"));
    }

    #[test]
    fn emitted_non_gunbc_cli_has_no_gunbc_build_environment_dependency() {
        let rendered = v1_compiler::v1_compiler_emit_rust::emit_cli_struct(
            std::rc::Rc::new(im::vector![]),
            "user-program".to_string(),
            "".to_string(),
            "".to_string(),
        );
        assert!(!rendered.contains("GUNBC_BUILD_IDENTITY"));
        assert!(!rendered.contains("version ="));
    }

    #[test]
    fn extract_module_path_none_for_moduleless_parse_fixture() {
        let fixture =
            "data split_brace_sample: SplitBraceSample =\nSplitBraceSample { field: \"x\" }\n";
        assert!(extract_module_path(fixture).is_none());
    }

    #[test]
    fn extract_module_path_some_for_module_decl() {
        assert_eq!(
            extract_module_path("module v1.test.fixture\n"),
            Some("v1.test.fixture".to_string())
        );
    }
}

/// Decode `--arg name=value` into the interpreter's named-argument shape.
///
/// This is DRIVER work and lives here rather than in the retained engine: argv is the
/// driver's subject.
/// A missing `=` REFUSES with the offending spec rather than guessing a positional —
/// the deleted handler's own rule, kept because it is right, not because it was there.
fn decode_run_args(
    raw: &[String],
) -> Result<Vec<(Option<String>, v1_compiler::v1_interpreter::Value)>, String> {
    raw.iter()
        .map(|spec| match spec.split_once('=') {
            Some((name, value)) if !name.is_empty() => Ok((
                Some(name.to_string()),
                v1_compiler::v1_interpreter::str_value(value),
            )),
            _ => Err(format!(
                "--arg expects name=value, got `{spec}` (a missing `=` is refused, not \
                 interpreted as a positional argument)"
            )),
        })
        .collect()
}

/// `gunbc run` -- argv -> modeled intent -> the RETAINED resolve/eval engine -> exit code.
///
/// The seam the cut's declared boundary was missing. It calls the engine
/// (`cli_run::resolve_entry_graph`, `cli_run::make_eval_context`) and the interpreter
/// (`run_in_context_with_args`), re-homes neither, and adds no policy beyond decoding argv and
/// mapping an outcome to a status.
///
/// Every failure arm REFUSES with a typed, located reason and a nonzero status; none widens,
/// defaults, or prints a plausible success -- the whole-tree case is declared unsupported rather
/// than approximated by loading everything under `--source-root`.
/// A verb's OUTCOME, returned rather than acted on.
///
/// The construction half. A pure mapping was not enough: the defect a planted-drift control
/// caught was an arm that PRINTED AND FELL THROUGH, never calling any mapping -- a driver can
/// always decline to call a function. With the verdict as RETURN TYPE, every arm of `run_verb`
/// must produce a `Verdict`, one place maps it to a status, and a forgotten failure report is a
/// TYPE ERROR rather than a silent zero exit.
struct Verdict {
    status: i32,
    message: Option<String>,
}

impl Verdict {
    /// The ONE place a verdict becomes a process status. Nothing else in this file calls
    /// `std::process::exit` for a verb outcome.
    ///
    /// `OutputWriteRefusal::verdict` is the second producer and not a verb outcome: the output
    /// writer's refusal, which before this change had no channel. The carrier is reused rather
    /// than a second status-plus-message pair, so the writer's status is decided where the
    /// writer refuses and nowhere else.
    fn apply(self) -> ! {
        if let Some(message) = self.message {
            eprintln!("{message}");
        }
        std::process::exit(self.status);
    }
}

fn run_verb(
    source_roots: &[String],
    function: &str,
    entry: Option<&str>,
    dry_run: bool,
    claim_run: bool,
    args: &[String],
) -> Verdict {
    if source_roots.is_empty() {
        return Verdict {
            status: 1,
            message: Some(format!("error: provide at least one --source-root")),
        };
    }

    // Refuse a malformed --arg BEFORE the compile, so the diagnostic is the first thing
    // printed rather than the last thing after a minute of resolution.
    let run_args = match decode_run_args(args) {
        Ok(parsed) => parsed,
        Err(message) => {
            return Verdict {
                status: 2,
                message: Some(format!("error: {message}")),
            };
        }
    };

    let Some(entry_file) = entry else {
        return Verdict {
            status: 2,
            message: Some(format!(
                "error: --entry <file.dag> is required.\n  \
             cause: this seam resolves an entry's import closure; the whole-tree run the \
             deleted handler also served is not implemented here.\n  \
             status: refused rather than approximated — loading every file under \
             --source-root would answer a different question with the same exit code."
            )),
        };
    };

    if claim_run && entry.is_none() {
        return Verdict {
            status: 2,
            message: Some(format!("error: --claim-run requires --entry <file.dag>")),
        };
    }

    let (graph, source_indices) = match cli_run::resolve_entry_graph(source_roots, entry_file) {
        Ok(resolved) => resolved,
        Err(cause) => {
            return Verdict {
                status: 1,
                message: Some(format!(
                    "error: resolve failed for {entry_file}\n  cause: {cause}"
                )),
            };
        }
    };

    // The SAME total classification the compile path uses — blocking vs advisory, with
    // advisory derived as (total - blocking) so no diagnostic is counted by neither.
    if has_blocking_diagnostics(graph.diagnostics.as_ref()) {
        let blocking = blocking_diagnostic_count(graph.diagnostics.as_ref());
        let advisory = graph.diagnostics.len() - blocking;
        return Verdict {
            status: 1,
            message: Some(format!(
                "error: {entry_file} has {blocking} blocking diagnostic(s) ({advisory} advisory); \
             refusing to evaluate"
            )),
        };
    }

    // Exactly the deleted handler's selection: `--dry-run` means Hermetic, which REFUSES
    // host operations rather than mocking them silently, and absence means Wet.
    let execution_mode = if dry_run {
        v1_compiler::v1_interpreter::ExecutionMode::Hermetic
    } else {
        v1_compiler::v1_interpreter::ExecutionMode::Wet
    };
    let ctx = cli_run::make_eval_context(graph.as_ref(), source_indices, execution_mode);

    match v1_compiler::v1_interpreter::run_in_context_with_args(
        &ctx, function, &run_args, !claim_run,
    ) {
        // A claim run's Bool is the verdict: false is a FAILED claim, exit 1. Outside a
        // claim run a Bool is an ordinary value and says nothing about success.
        Ok(v1_compiler::v1_interpreter::Value::Bool(false)) if claim_run => Verdict {
            status: 1,
            message: Some(format!("FAIL {function}")),
        },
        Ok(v1_compiler::v1_interpreter::Value::Bool(true)) if claim_run => {
            println!("PASS {function}");
            Verdict {
                status: 0,
                message: None,
            }
        }
        // The verdict a `.dag` entry returns IS the run's outcome. `cli_run::classify_exit`
        // is the single authority for reading the ProcessExit variant; `exit_status_for`
        // is the total map from that class to a status.
        Ok(value) => {
            // A `CliWireResponse` is an ANSWER PLUS A VERDICT, and it is the only return shape
            // that carries bytes for the operator. Binding it HERE rather than under a new
            // `scm` subcommand keeps dispatch peripheral (§3): one binding serves every
            // wire-returning entry -- `scm_log_cli_response`, `scm_status_cli_response`, and
            // whatever else renders next -- instead of the host growing an arm per verb.
            //
            // Before this, such a function hit `classify_exit`'s `NotProcessExit` arm and the
            // run refused with "wrap the result in ExitSuccess / ExitFailure", which is why
            // gunbc.scm.render's two wire functions had no consumer outside their witness
            // test: the answer was computed and discarded.
            //
            // A non-wire value falls through unchanged, so every existing `ProcessExit` entry
            // behaves exactly as it did.
            match cli_run::cli_wire_outcome(cli_run::classify_cli_wire(&value, &ctx), function) {
                Some(outcome) => {
                    if let Some(bytes) = outcome.stdout {
                        use std::io::Write;
                        let mut out = std::io::stdout();
                        // Written verbatim: the .dag renderer already decided every byte,
                        // including trailing newlines. `print!` plus an implicit flush-at-exit
                        // is not enough when the process exits nonzero, so flush explicitly
                        // and refuse rather than silently dropping the answer.
                        if let Err(err) = out.write_all(bytes.as_bytes()).and_then(|()| out.flush())
                        {
                            return Verdict {
                                status: 1,
                                message: Some(format!(
                                    "error: `{function}` rendered {} bytes that could not be \
                                     written to stdout.\n  cause: {err}\n  status: refused — \
                                     exiting nonzero rather than reporting success for an \
                                     answer the operator never received.",
                                    bytes.len()
                                )),
                            };
                        }
                    }
                    Verdict {
                        status: outcome.status,
                        message: outcome.message,
                    }
                }
                None => {
                    let (status, message) =
                        exit_status_for(cli_run::classify_exit(&value, &ctx), function);
                    Verdict { status, message }
                }
            }
        }
        Err(err) => Verdict {
            status: 1,
            message: Some(format!(
                "error: evaluating {function} in {entry_file}\n  cause: {err:?}"
            )),
        },
    }
}

/// TOTAL map from a run's verdict to a process status, plus the message that explains it.
///
/// Pure on purpose (§5 construction-over-validation). The first version inlined this in a
/// `match` arm and DROPPED the failure case -- printed `ExitFailure { code: 1, reason:
/// "…drift…" }` and exited 0, green for every consumer of `gunbc run` regardless of content. A
/// planted-drift control caught it; nothing else could, since a clean run and a malformed-argv
/// refusal are both satisfiable by a seam that always exits 0.
///
/// Total and pure, the arm has nowhere to drop a verdict: every `ExitClass` yields a status,
/// `Failure` cannot yield 0 (its code is the status, and the .dag side cannot construct
/// `ExitFailure` with code 0 -- see the assertion below), and re-introducing the defect means
/// editing THIS function rather than forgetting a case.
///
/// RUNG, HONESTLY: a construction, not an enrolled check. The tests below are Rust, and CI runs
/// no Rust suite (removed 2026-07-11, operator ruling, local-only), so the class is
/// `mechanically preventable` ONLY where the suite is run by hand; in CI it rests on the
/// totality above. The planted-drift control is a manual procedure recorded in the PR.
fn exit_status_for(class: cli_run::ExitClass, function: &str) -> (i32, Option<String>) {
    // ONE AUTHORITY, in the lib. This function used to carry the match itself, and when the
    // wire path needed the same decision the copy became a §3 fork -- two places deciding what
    // a verdict means, free to drift. The body moved to `cli_run::exit_status_for_class`, where
    // it is also REACHABLE BY AN EXECUTING TEST: `rust-unit-tests` runs
    // `cargo test -p v1-compiler --lib`, and this file is a BIN target whose tests are compiled
    // by clippy and run by nobody.
    cli_run::exit_status_for_class(class, function)
}

#[cfg(test)]
mod exit_status_tests {
    use super::*;

    /// THE DISCRIMINATING RED FOR THE WRITER/COMPILER CONFLATION.
    ///
    /// The claim under test is not "a refusal type exists" -- that probe cannot fail for the
    /// reason that matters -- but that a writer failure and a compiler refusal are
    /// DISTINGUISHABLE AT THE EXIT STATUS, impossible before: the writer's only outcome was an
    /// unwind at 101 with no summary line, which every consumer reads as a failed compile.
    ///
    /// The edits that make this red: changing the status in `OutputWriteRefusal::verdict` to 1
    /// (re-fusing the two states at the status a compile refusal exits with), or to 0 (a writer
    /// refusal reporting success). Restoring the `panic!` makes it fail to compile instead,
    /// the stronger outcome.
    #[test]
    fn a_writer_refusal_does_not_exit_as_a_compile_refusal() {
        // The status a compile refusal exits with, at every compile arm in `main`.
        const COMPILE_REFUSAL_STATUS: i32 = 1;
        for refusal in [
            OutputWriteRefusal::OutputDirectoryNotCreated {
                path: "/proc/nope/src".to_string(),
                cause: "Not a directory".to_string(),
            },
            OutputWriteRefusal::ParentDirectoryNotCreated {
                path: "/proc/nope".to_string(),
                file: "/proc/nope/src/a.rs".to_string(),
                cause: "Not a directory".to_string(),
            },
            OutputWriteRefusal::FileNotWritten {
                path: "/proc/nope/src/a.rs".to_string(),
                cause: "Permission denied".to_string(),
            },
        ] {
            let verdict = refusal.verdict();
            assert_ne!(
                verdict.status, COMPILE_REFUSAL_STATUS,
                "a writer refusal must not exit as a compile refusal"
            );
            assert_ne!(verdict.status, 0, "a writer refusal must never exit 0");
        }
    }

    /// THE THREE CAUSES STAY THREE. The parent-directory arm is here because it had no
    /// representation at all -- `.ok()` discarded it and the write arm reported its own name for
    /// the failure. Red if any arm collapses into another's wording, the state the repair
    /// removed.
    #[test]
    fn each_writer_cause_names_itself_and_its_path() {
        assert_eq!(
            OutputWriteRefusal::OutputDirectoryNotCreated {
                path: "/out/src".to_string(),
                cause: "Not a directory".to_string(),
            }
            .to_string(),
            "gunbc compile: output write refused: could not create output directory /out/src: Not a directory"
        );
        assert_eq!(
            OutputWriteRefusal::ParentDirectoryNotCreated {
                path: "/out/src/deep".to_string(),
                file: "/out/src/deep/a.rs".to_string(),
                cause: "Not a directory".to_string(),
            }
            .to_string(),
            "gunbc compile: output write refused: could not create parent directory /out/src/deep for /out/src/deep/a.rs: Not a directory"
        );
        assert_eq!(
            OutputWriteRefusal::FileNotWritten {
                path: "/out/src/a.rs".to_string(),
                cause: "Permission denied".to_string(),
            }
            .to_string(),
            "gunbc compile: output write refused: could not write /out/src/a.rs: Permission denied"
        );
    }

    #[test]
    fn success_is_zero() {
        assert_eq!(exit_status_for(cli_run::ExitClass::Success, "main").0, 0);
    }

    /// THE REGRESSION CONTROL for the defect the planted-drift run caught. If this ever
    /// returns 0, every consumer of `gunbc run` reports green regardless of content.
    #[test]
    fn failure_is_never_zero() {
        for code in [1, 2, 42, 127] {
            let (status, _) = exit_status_for(
                cli_run::ExitClass::Failure {
                    code,
                    reason: Some("drift".to_string()),
                },
                "main",
            );
            assert_eq!(status, code);
            assert_ne!(status, 0, "a Failure verdict must never exit 0");
        }
    }

    #[test]
    fn failure_with_zero_code_refuses_rather_than_reporting_success() {
        let (status, message) = exit_status_for(
            cli_run::ExitClass::Failure {
                code: 0,
                reason: None,
            },
            "main",
        );
        assert_eq!(status, 1);
        assert!(message.unwrap().contains("contradicts its own variant"));
    }

    #[test]
    fn non_process_exit_refuses_rather_than_printing_and_succeeding() {
        let (status, message) = exit_status_for(
            cli_run::ExitClass::NotProcessExit {
                type_name: "Bool".to_string(),
            },
            "main",
        );
        assert_eq!(status, 2);
        assert!(message.unwrap().contains("not `ProcessExit`"));
    }

    /// The failure's own reason must SURVIVE to the message — a located diagnostic that the
    /// driver swallows is the same silence as a wrong exit code, one channel over.
    #[test]
    fn failure_reason_is_carried_not_dropped() {
        let (_, message) = exit_status_for(
            cli_run::ExitClass::Failure {
                code: 1,
                reason: Some("drift: docs/plans/x.md".to_string()),
            },
            "main",
        );
        assert_eq!(message.as_deref(), Some("drift: docs/plans/x.md"));
    }
}
