// Generated by v1 compiler -- do not edit.
// Source module: std.trait_derive_shape

use self::PairCompletionBody::*;
use self::PairCompletionComponent::*;
use self::PairCompletionOperand::*;
use self::ReprGroundingDeriveElemShape::*;
use self::ReprGroundingDeriveTrait::*;
pub use crate::std_algebra::FreeMonoid;
use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

pub fn trait_derive_shape_note() -> String {
    thread_local! {
        static CACHED: String = {
            "Target-agnostic authority for ReprGroundingDeriveTrait × ReprGroundingDeriveElemShape capability table and derive-trait list builders. Rust spellings: extdeps.languages.rust.emit. Consumed by v2.compiler.trait_derive_completeness and v1.compiler.trait_derive_emit. #7174 (operator 2026-07-25): v1 emit wires (a) clone bounds and (c) serde/Debug/Ord #[derive] on named structs/enums. Root-4 arm (b): predicate-gated supplemental impl { … } blocks for coproduct-native arithmetic carriers — see trait_derive_shape_grounding_lane_handoff; ReprDeriveAdd/Sub/… rows on KernelInt are capability-table authority for repr_grounding_derive_completeness_predicate, not spellings.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn trait_derive_shape_grounding_lane_handoff() -> String {
    thread_local! {
        static CACHED: String = {
            "Root-4 arm (b): coproduct-native arithmetic + PartialOrd/PartialEq impl blocks for algebra carriers (GroupCompletion<Nat>, Vector). Capability table + repr_grounding_derive_completeness_predicate remain the shared authority; v1.compiler.trait_derive_emit emits impl { … } from shape rows (not #[derive]) through the seed emitter. GroupCompletion<M> pos/neg pair Add/Sub/Mul/Div landed in #7197 (dissolves interim CommutativeSemiring<Magnitude> stubs).".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn trait_derive_shape_dissolve_on() -> String {
    thread_local! {
        static CACHED: String = {
            "ReprGroundingDeriveTrait members that name Rust-specific authorities (ReprDeriveSerialize, ReprDeriveAdd, …) migrate beside each target's spelling table when a second consumer exists; until then capability roles stay in std/ with spellings in extdeps.languages.rust.emit.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum ReprGroundingDeriveTrait {
    ReprDeriveDebug,
    ReprDeriveClone,
    ReprDeriveCopy,
    ReprDerivePartialEq,
    ReprDeriveEq,
    ReprDerivePartialOrd,
    ReprDeriveOrd,
    ReprDeriveSerialize,
    ReprDeriveDeserialize,
    ReprDeriveAdd,
    ReprDeriveSub,
    ReprDeriveMul,
    ReprDeriveDiv,
    ReprDeriveRem,
    ReprDeriveNeg,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum ReprGroundingDeriveElemShape {
    ReprDeriveElemKernelString,
    ReprDeriveElemKernelInt,
    ReprDeriveElemKernelBool,
    ReprDeriveElemKernelUnit,
    ReprDeriveElemNullaryEnumCopy,
    ReprDeriveElemSymbolWrappedOrdCarrier,
    ReprDeriveElemPayloadCoproduct,
    ReprDeriveElemUnknown,
}

pub fn repr_grounding_derive_shape_has_trait(
    shape: ReprGroundingDeriveElemShape,
    derive_trait: ReprGroundingDeriveTrait,
) -> bool {
    match shape.clone() {
        ReprGroundingDeriveElemShape::ReprDeriveElemKernelString => match derive_trait.clone() {
            ReprGroundingDeriveTrait::ReprDeriveDebug => true,
            ReprGroundingDeriveTrait::ReprDeriveClone => true,
            ReprGroundingDeriveTrait::ReprDerivePartialEq => true,
            ReprGroundingDeriveTrait::ReprDeriveEq => true,
            ReprGroundingDeriveTrait::ReprDerivePartialOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveSerialize => true,
            ReprGroundingDeriveTrait::ReprDeriveDeserialize => true,
            _ => false,
        },
        ReprGroundingDeriveElemShape::ReprDeriveElemKernelInt => match derive_trait.clone() {
            ReprGroundingDeriveTrait::ReprDeriveDebug => true,
            ReprGroundingDeriveTrait::ReprDeriveClone => true,
            ReprGroundingDeriveTrait::ReprDeriveCopy => true,
            ReprGroundingDeriveTrait::ReprDerivePartialEq => true,
            ReprGroundingDeriveTrait::ReprDeriveEq => true,
            ReprGroundingDeriveTrait::ReprDerivePartialOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveSerialize => true,
            ReprGroundingDeriveTrait::ReprDeriveDeserialize => true,
            ReprGroundingDeriveTrait::ReprDeriveAdd => true,
            ReprGroundingDeriveTrait::ReprDeriveSub => true,
            ReprGroundingDeriveTrait::ReprDeriveMul => true,
            ReprGroundingDeriveTrait::ReprDeriveDiv => true,
            ReprGroundingDeriveTrait::ReprDeriveRem => true,
            ReprGroundingDeriveTrait::ReprDeriveNeg => true,
        },
        ReprGroundingDeriveElemShape::ReprDeriveElemKernelBool => match derive_trait.clone() {
            ReprGroundingDeriveTrait::ReprDeriveDebug => true,
            ReprGroundingDeriveTrait::ReprDeriveClone => true,
            ReprGroundingDeriveTrait::ReprDeriveCopy => true,
            ReprGroundingDeriveTrait::ReprDerivePartialEq => true,
            ReprGroundingDeriveTrait::ReprDeriveEq => true,
            ReprGroundingDeriveTrait::ReprDerivePartialOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveSerialize => true,
            ReprGroundingDeriveTrait::ReprDeriveDeserialize => true,
            _ => false,
        },
        ReprGroundingDeriveElemShape::ReprDeriveElemKernelUnit => match derive_trait.clone() {
            ReprGroundingDeriveTrait::ReprDeriveDebug => true,
            ReprGroundingDeriveTrait::ReprDeriveClone => true,
            ReprGroundingDeriveTrait::ReprDeriveCopy => true,
            ReprGroundingDeriveTrait::ReprDerivePartialEq => true,
            ReprGroundingDeriveTrait::ReprDeriveEq => true,
            ReprGroundingDeriveTrait::ReprDerivePartialOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveSerialize => true,
            ReprGroundingDeriveTrait::ReprDeriveDeserialize => true,
            _ => false,
        },
        ReprGroundingDeriveElemShape::ReprDeriveElemNullaryEnumCopy => match derive_trait.clone() {
            ReprGroundingDeriveTrait::ReprDeriveDebug => true,
            ReprGroundingDeriveTrait::ReprDeriveClone => true,
            ReprGroundingDeriveTrait::ReprDeriveCopy => true,
            ReprGroundingDeriveTrait::ReprDerivePartialEq => true,
            ReprGroundingDeriveTrait::ReprDeriveEq => true,
            ReprGroundingDeriveTrait::ReprDerivePartialOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveOrd => true,
            ReprGroundingDeriveTrait::ReprDeriveSerialize => true,
            ReprGroundingDeriveTrait::ReprDeriveDeserialize => true,
            _ => false,
        },
        ReprGroundingDeriveElemShape::ReprDeriveElemSymbolWrappedOrdCarrier => {
            match derive_trait.clone() {
                ReprGroundingDeriveTrait::ReprDeriveDebug => true,
                ReprGroundingDeriveTrait::ReprDeriveClone => true,
                ReprGroundingDeriveTrait::ReprDerivePartialEq => true,
                ReprGroundingDeriveTrait::ReprDeriveEq => true,
                ReprGroundingDeriveTrait::ReprDerivePartialOrd => true,
                ReprGroundingDeriveTrait::ReprDeriveOrd => true,
                ReprGroundingDeriveTrait::ReprDeriveSerialize => true,
                ReprGroundingDeriveTrait::ReprDeriveDeserialize => true,
                _ => false,
            }
        }
        ReprGroundingDeriveElemShape::ReprDeriveElemPayloadCoproduct => {
            match derive_trait.clone() {
                ReprGroundingDeriveTrait::ReprDeriveDebug => true,
                ReprGroundingDeriveTrait::ReprDeriveClone => true,
                ReprGroundingDeriveTrait::ReprDerivePartialEq => true,
                ReprGroundingDeriveTrait::ReprDeriveSerialize => true,
                ReprGroundingDeriveTrait::ReprDeriveDeserialize => true,
                _ => false,
            }
        }
        ReprGroundingDeriveElemShape::ReprDeriveElemUnknown => false,
    }
}

pub fn repr_grounding_derive_completeness_predicate(
    required: Rc<Vec<ReprGroundingDeriveTrait>>,
    shape: ReprGroundingDeriveElemShape,
) -> bool {
    {
        let mut __all = true;
        for dt in required.clone().iter().cloned() {
            if !(repr_grounding_derive_shape_has_trait(shape.clone(), dt.clone())) {
                __all = false;
                break;
            }
        }
        __all
    }
}

pub fn record_derive_traits_heap() -> Rc<Vec<ReprGroundingDeriveTrait>> {
    Rc::new({
        let mut __cons_v = (*Rc::new({
            let mut __cons_v = (*Rc::new({
                let mut __cons_v = (*Rc::new({
                    let mut __cons_v = (*Rc::new({
                        let mut __cons_v = (*Rc::new(vec![])).clone();
                        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDeserialize);
                        __cons_v
                    }))
                    .clone();
                    __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveSerialize);
                    __cons_v
                }))
                .clone();
                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDerivePartialEq);
                __cons_v
            }))
            .clone();
            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveClone);
            __cons_v
        }))
        .clone();
        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDebug);
        __cons_v
    })
}

pub fn record_derive_traits_copy() -> Rc<Vec<ReprGroundingDeriveTrait>> {
    Rc::new({
        let mut __cons_v = (*Rc::new({
            let mut __cons_v = (*Rc::new({
                let mut __cons_v = (*Rc::new({
                    let mut __cons_v = (*Rc::new({
                        let mut __cons_v = (*Rc::new({
                            let mut __cons_v = (*Rc::new(vec![])).clone();
                            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDeserialize);
                            __cons_v
                        }))
                        .clone();
                        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveSerialize);
                        __cons_v
                    }))
                    .clone();
                    __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDerivePartialEq);
                    __cons_v
                }))
                .clone();
                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveCopy);
                __cons_v
            }))
            .clone();
            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveClone);
            __cons_v
        }))
        .clone();
        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDebug);
        __cons_v
    })
}

pub fn nullary_coproduct_derive_traits() -> Rc<Vec<ReprGroundingDeriveTrait>> {
    Rc::new({
        let mut __cons_v = (*Rc::new({
            let mut __cons_v = (*Rc::new({
                let mut __cons_v = (*Rc::new({
                    let mut __cons_v = (*Rc::new({
                        let mut __cons_v = (*Rc::new({
                            let mut __cons_v = (*Rc::new({
                                let mut __cons_v = (*Rc::new({
                                    let mut __cons_v = (*Rc::new({
                                        let mut __cons_v = (*Rc::new(vec![])).clone();
                                        __cons_v.insert(
                                            0,
                                            ReprGroundingDeriveTrait::ReprDeriveDeserialize,
                                        );
                                        __cons_v
                                    }))
                                    .clone();
                                    __cons_v
                                        .insert(0, ReprGroundingDeriveTrait::ReprDeriveSerialize);
                                    __cons_v
                                }))
                                .clone();
                                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveOrd);
                                __cons_v
                            }))
                            .clone();
                            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDerivePartialOrd);
                            __cons_v
                        }))
                        .clone();
                        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveEq);
                        __cons_v
                    }))
                    .clone();
                    __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDerivePartialEq);
                    __cons_v
                }))
                .clone();
                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveCopy);
                __cons_v
            }))
            .clone();
            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveClone);
            __cons_v
        }))
        .clone();
        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDebug);
        __cons_v
    })
}

pub fn symbol_wrapped_ord_carrier_derive_traits() -> Rc<Vec<ReprGroundingDeriveTrait>> {
    Rc::new({
        let mut __cons_v = (*Rc::new({
            let mut __cons_v = (*Rc::new({
                let mut __cons_v = (*Rc::new({
                    let mut __cons_v = (*Rc::new({
                        let mut __cons_v = (*Rc::new({
                            let mut __cons_v = (*Rc::new({
                                let mut __cons_v = (*Rc::new({
                                    let mut __cons_v = (*Rc::new(vec![])).clone();
                                    __cons_v
                                        .insert(0, ReprGroundingDeriveTrait::ReprDeriveDeserialize);
                                    __cons_v
                                }))
                                .clone();
                                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveSerialize);
                                __cons_v
                            }))
                            .clone();
                            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveOrd);
                            __cons_v
                        }))
                        .clone();
                        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDerivePartialOrd);
                        __cons_v
                    }))
                    .clone();
                    __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveEq);
                    __cons_v
                }))
                .clone();
                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDerivePartialEq);
                __cons_v
            }))
            .clone();
            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveClone);
            __cons_v
        }))
        .clone();
        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDebug);
        __cons_v
    })
}

pub fn fn_field_derive_traits() -> Rc<Vec<ReprGroundingDeriveTrait>> {
    Rc::new({
        let mut __cons_v = (*Rc::new(vec![])).clone();
        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveClone);
        __cons_v
    })
}

pub fn payload_coproduct_derive_traits() -> Rc<Vec<ReprGroundingDeriveTrait>> {
    Rc::new({
        let mut __cons_v = (*Rc::new({
            let mut __cons_v = (*Rc::new({
                let mut __cons_v = (*Rc::new({
                    let mut __cons_v = (*Rc::new({
                        let mut __cons_v = (*Rc::new(vec![])).clone();
                        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDeserialize);
                        __cons_v
                    }))
                    .clone();
                    __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveSerialize);
                    __cons_v
                }))
                .clone();
                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDerivePartialEq);
                __cons_v
            }))
            .clone();
            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveClone);
            __cons_v
        }))
        .clone();
        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDebug);
        __cons_v
    })
}

pub fn kernel_int_arithmetic_traits() -> Rc<Vec<ReprGroundingDeriveTrait>> {
    Rc::new({
        let mut __cons_v = (*Rc::new({
            let mut __cons_v = (*Rc::new({
                let mut __cons_v = (*Rc::new({
                    let mut __cons_v = (*Rc::new({
                        let mut __cons_v = (*Rc::new({
                            let mut __cons_v = (*Rc::new({
                                let mut __cons_v = (*Rc::new({
                                    let mut __cons_v = (*Rc::new(vec![])).clone();
                                    __cons_v
                                        .insert(0, ReprGroundingDeriveTrait::ReprDerivePartialOrd);
                                    __cons_v
                                }))
                                .clone();
                                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDerivePartialEq);
                                __cons_v
                            }))
                            .clone();
                            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveNeg);
                            __cons_v
                        }))
                        .clone();
                        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveRem);
                        __cons_v
                    }))
                    .clone();
                    __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveDiv);
                    __cons_v
                }))
                .clone();
                __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveMul);
                __cons_v
            }))
            .clone();
            __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveSub);
            __cons_v
        }))
        .clone();
        __cons_v.insert(0, ReprGroundingDeriveTrait::ReprDeriveAdd);
        __cons_v
    })
}

pub fn pair_completion_shape_note() -> String {
    thread_local! {
        static CACHED: String = {
            "Target-agnostic authority for the Grothendieck pair-completion operator BODIES on GroupCompletion<M> (std.algebra). Each output component is a polynomial over the four operand components self.pos, self.neg, rhs.pos, rhs.neg: an arm is a sum of terms, a term is a product of factors, a factor names one operand component. Selection (which traits apply) stays in the capability table above; SPELLING (trait paths, where-clauses, field syntax) lives per target in extdeps.languages.rust.emit. Reuses ReprGroundingDeriveTrait as the op key rather than minting a parallel operator enum.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn pair_completion_shape_dissolve_on() -> String {
    thread_local! {
        static CACHED: String = {
            "Dissolves when v2 derives these rows from the std.algebra Ring/AbelianGroup inhabitance witnesses directly, so the Grothendieck construction is read off the algebra rather than tabulated here; tracked by the numeric-tower grounding lane.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum PairCompletionOperand {
    PairCompletionSelf,
    PairCompletionRhs,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum PairCompletionComponent {
    PairCompletionPos,
    PairCompletionNeg,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PairCompletionFactor {
    pub operand: PairCompletionOperand,
    pub component: PairCompletionComponent,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PairCompletionTerm {
    pub factors: Rc<Vec<Rc<PairCompletionFactor>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PairCompletionArm {
    pub terms: Rc<Vec<Rc<PairCompletionTerm>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum PairCompletionBody {
    PairCompletionSumOfProducts {
        pos: Rc<PairCompletionArm>,
        neg: Rc<PairCompletionArm>,
    },
    PairCompletionNegatedAddend,
    PairCompletionCanonicalQuotient,
}
impl PairCompletionBody {
    pub fn pos(&self) -> Rc<PairCompletionArm> {
        match self {
            PairCompletionBody::PairCompletionSumOfProducts { pos: __val, .. } => __val.clone(),
            PairCompletionBody::PairCompletionNegatedAddend => panic!("no pos on unit variant"),
            PairCompletionBody::PairCompletionCanonicalQuotient => panic!("no pos on unit variant"),
        }
    }
    pub fn neg(&self) -> Rc<PairCompletionArm> {
        match self {
            PairCompletionBody::PairCompletionSumOfProducts { neg: __val, .. } => __val.clone(),
            PairCompletionBody::PairCompletionNegatedAddend => panic!("no neg on unit variant"),
            PairCompletionBody::PairCompletionCanonicalQuotient => panic!("no neg on unit variant"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PairCompletionOpRow {
    pub op: ReprGroundingDeriveTrait,
    pub body: Rc<PairCompletionBody>,
}

pub fn pair_completion_factor(
    operand: PairCompletionOperand,
    component: PairCompletionComponent,
) -> Rc<PairCompletionFactor> {
    Rc::new(PairCompletionFactor {
        operand: operand.clone(),
        component: component.clone(),
    })
}

pub fn pair_completion_op_rows() -> Rc<Vec<Rc<PairCompletionOpRow>>> {
    Rc::new(vec![
        Rc::new(PairCompletionOpRow {
            op: ReprGroundingDeriveTrait::ReprDeriveNeg,
            body: Rc::new(PairCompletionBody::PairCompletionSumOfProducts {
                pos: Rc::new(PairCompletionArm {
                    terms: Rc::new(vec![Rc::new(PairCompletionTerm {
                        factors: Rc::new(vec![pair_completion_factor(
                            PairCompletionOperand::PairCompletionSelf,
                            PairCompletionComponent::PairCompletionNeg,
                        )]),
                    })]),
                }),
                neg: Rc::new(PairCompletionArm {
                    terms: Rc::new(vec![Rc::new(PairCompletionTerm {
                        factors: Rc::new(vec![pair_completion_factor(
                            PairCompletionOperand::PairCompletionSelf,
                            PairCompletionComponent::PairCompletionPos,
                        )]),
                    })]),
                }),
            }),
        }),
        Rc::new(PairCompletionOpRow {
            op: ReprGroundingDeriveTrait::ReprDeriveAdd,
            body: Rc::new(PairCompletionBody::PairCompletionSumOfProducts {
                pos: Rc::new(PairCompletionArm {
                    terms: Rc::new(vec![
                        Rc::new(PairCompletionTerm {
                            factors: Rc::new(vec![pair_completion_factor(
                                PairCompletionOperand::PairCompletionSelf,
                                PairCompletionComponent::PairCompletionPos,
                            )]),
                        }),
                        Rc::new(PairCompletionTerm {
                            factors: Rc::new(vec![pair_completion_factor(
                                PairCompletionOperand::PairCompletionRhs,
                                PairCompletionComponent::PairCompletionPos,
                            )]),
                        }),
                    ]),
                }),
                neg: Rc::new(PairCompletionArm {
                    terms: Rc::new(vec![
                        Rc::new(PairCompletionTerm {
                            factors: Rc::new(vec![pair_completion_factor(
                                PairCompletionOperand::PairCompletionSelf,
                                PairCompletionComponent::PairCompletionNeg,
                            )]),
                        }),
                        Rc::new(PairCompletionTerm {
                            factors: Rc::new(vec![pair_completion_factor(
                                PairCompletionOperand::PairCompletionRhs,
                                PairCompletionComponent::PairCompletionNeg,
                            )]),
                        }),
                    ]),
                }),
            }),
        }),
        Rc::new(PairCompletionOpRow {
            op: ReprGroundingDeriveTrait::ReprDeriveSub,
            body: Rc::new(PairCompletionBody::PairCompletionNegatedAddend),
        }),
        Rc::new(PairCompletionOpRow {
            op: ReprGroundingDeriveTrait::ReprDeriveMul,
            body: Rc::new(PairCompletionBody::PairCompletionSumOfProducts {
                pos: Rc::new(PairCompletionArm {
                    terms: Rc::new(vec![
                        Rc::new(PairCompletionTerm {
                            factors: Rc::new(vec![
                                pair_completion_factor(
                                    PairCompletionOperand::PairCompletionSelf,
                                    PairCompletionComponent::PairCompletionPos,
                                ),
                                pair_completion_factor(
                                    PairCompletionOperand::PairCompletionRhs,
                                    PairCompletionComponent::PairCompletionPos,
                                ),
                            ]),
                        }),
                        Rc::new(PairCompletionTerm {
                            factors: Rc::new(vec![
                                pair_completion_factor(
                                    PairCompletionOperand::PairCompletionSelf,
                                    PairCompletionComponent::PairCompletionNeg,
                                ),
                                pair_completion_factor(
                                    PairCompletionOperand::PairCompletionRhs,
                                    PairCompletionComponent::PairCompletionNeg,
                                ),
                            ]),
                        }),
                    ]),
                }),
                neg: Rc::new(PairCompletionArm {
                    terms: Rc::new(vec![
                        Rc::new(PairCompletionTerm {
                            factors: Rc::new(vec![
                                pair_completion_factor(
                                    PairCompletionOperand::PairCompletionSelf,
                                    PairCompletionComponent::PairCompletionPos,
                                ),
                                pair_completion_factor(
                                    PairCompletionOperand::PairCompletionRhs,
                                    PairCompletionComponent::PairCompletionNeg,
                                ),
                            ]),
                        }),
                        Rc::new(PairCompletionTerm {
                            factors: Rc::new(vec![
                                pair_completion_factor(
                                    PairCompletionOperand::PairCompletionSelf,
                                    PairCompletionComponent::PairCompletionNeg,
                                ),
                                pair_completion_factor(
                                    PairCompletionOperand::PairCompletionRhs,
                                    PairCompletionComponent::PairCompletionPos,
                                ),
                            ]),
                        }),
                    ]),
                }),
            }),
        }),
        Rc::new(PairCompletionOpRow {
            op: ReprGroundingDeriveTrait::ReprDeriveDiv,
            body: Rc::new(PairCompletionBody::PairCompletionCanonicalQuotient),
        }),
    ])
}

pub fn pair_completion_arm_uses_rhs(arm: Rc<PairCompletionArm>) -> bool {
    {
        let mut __found = false;
        for term in arm.terms.clone().iter().cloned() {
            if {
                let mut __found = false;
                for f in term.factors.clone().iter().cloned() {
                    if match f.operand.clone() {
                        PairCompletionOperand::PairCompletionRhs => true,
                        PairCompletionOperand::PairCompletionSelf => false,
                    } {
                        __found = true;
                        break;
                    }
                }
                __found
            } {
                __found = true;
                break;
            }
        }
        __found
    }
}

pub fn pair_completion_body_uses_rhs(body: Rc<PairCompletionBody>) -> bool {
    match (*body.clone()).clone() {
        PairCompletionBody::PairCompletionSumOfProducts { pos, neg, .. } => {
            (pair_completion_arm_uses_rhs(pos.clone()) || pair_completion_arm_uses_rhs(neg.clone()))
        }
        PairCompletionBody::PairCompletionNegatedAddend => true,
        PairCompletionBody::PairCompletionCanonicalQuotient => true,
    }
}

pub fn repr_grounding_supplemental_group_completion_target(
    module_path: String,
    name: String,
) -> bool {
    ((module_path.clone() == "std.algebra".to_string())
        && (name.clone() == "GroupCompletion".to_string()))
}

pub fn repr_grounding_supplemental_bool_host_bridge_target(
    module_path: String,
    name: String,
) -> bool {
    ((module_path.clone() == "std.types".to_string()) && (name.clone() == "Bool".to_string()))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveDebug;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveClone;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveCopy;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDerivePartialEq;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveEq;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDerivePartialOrd;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveOrd;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveSerialize;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveDeserialize;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveAdd;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveSub;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveMul;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveDiv;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveRem;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveNeg;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveElemKernelString;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveElemKernelInt;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveElemKernelBool;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveElemKernelUnit;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveElemNullaryEnumCopy;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveElemSymbolWrappedOrdCarrier;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveElemPayloadCoproduct;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ReprDeriveElemUnknown;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PairCompletionSelf;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PairCompletionRhs;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PairCompletionPos;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PairCompletionNeg;
