// Generated by v1 compiler -- do not edit.
// Source module: std.unicode.types

use self::DisplayWidth::*;
use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

pub fn unicode_scalar_max_code_point() -> i64 {
    1114111
}

pub fn unicode_surrogate_first_code_point() -> i64 {
    55296
}

pub fn unicode_surrogate_last_code_point() -> i64 {
    57343
}

pub fn unicode_scalar(code_point: i64) -> bool {
    (((code_point.clone() >= 0) && (code_point.clone() <= unicode_scalar_max_code_point()))
        && !((code_point.clone() >= unicode_surrogate_first_code_point())
            && (code_point.clone() <= unicode_surrogate_last_code_point())))
}

pub fn unicode_scalar_utf8_octet_count(code_point: i64) -> i64 {
    if (code_point.clone() < 128) {
        1
    } else {
        if (code_point.clone() < 2048) {
            2
        } else {
            if (code_point.clone() < 65536) {
                3
            } else {
                4
            }
        }
    }
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum DisplayWidth {
    ZeroWidth,
    Narrow,
    Wide,
}

pub fn display_width_columns(w: DisplayWidth) -> i64 {
    match w.clone() {
        DisplayWidth::ZeroWidth => 0,
        DisplayWidth::Narrow => 1,
        DisplayWidth::Wide => 2,
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UnicodeBlock {
    pub name: String,
    pub start: i64,
    pub end_inclusive: i64,
    pub default_width: DisplayWidth,
}

pub fn in_block(cp: i64, block: Rc<UnicodeBlock>) -> bool {
    ((cp.clone() >= block.start.clone()) && (cp.clone() <= block.end_inclusive.clone()))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ZeroWidth;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Narrow;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Wide;
