// Generated by v1 compiler -- do not edit.
// Source module: std.occurrence_binding

use self::OccurrenceBindingFoldState::*;
use self::OccurrenceBindingResult::*;
pub use crate::std_algebra::FreeMonoid;
use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

pub fn occurrence_binding_staged_adoption_scaffold_note() -> String {
    thread_local! {
        static CACHED: String = {
            "STAGED ADOPTION: v1 and v2 execute over distinct Node algebras, so their shared occurrence-binding semantics must land here before either concrete Node instantiation. The next consumers are #7306/P1's fresh-successor v1 declaration-backed resolver instantiation, followed by the v2 resolver instantiation and its DependencyView BindsTo projection. LexicalLookup is not an interim consumer: it has no exact reference-occurrence Node or occurrence containment identity, so binding it here would fabricate the relation this carrier preserves.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn occurrence_binding_staged_adoption_dissolve_on() -> String {
    thread_local! {
        static CACHED: String = {
            "DISSOLVE-ON: both production resolver paths consume OccurrenceBindingResult by execution — v1 emits declaration-backed occurrence bindings, and v2 emits the same result and derives DependencyView BindsTo from OccurrenceBound — then delete this staged-adoption scaffold note and this dissolution row.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainmentPath<N> {
    pub ancestors: Rc<Vec<N>>,
    pub terminal: N,
    pub _phantom: std::marker::PhantomData<N>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BindingOccurrence<N> {
    pub containment: Rc<ContainmentPath<N>>,
    pub _phantom: std::marker::PhantomData<N>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BindingCandidate<N> {
    pub containment: Rc<ContainmentPath<N>>,
    pub _phantom: std::marker::PhantomData<N>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct OccurrenceBinding<N> {
    pub occurrence: Rc<BindingOccurrence<N>>,
    pub candidate: Rc<BindingCandidate<N>>,
    pub _phantom: std::marker::PhantomData<N>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AmbiguousBindingCandidates<N> {
    pub first: Rc<BindingCandidate<N>>,
    pub second: Rc<BindingCandidate<N>>,
    pub rest: Rc<Vec<Rc<BindingCandidate<N>>>>,
    pub _phantom: std::marker::PhantomData<N>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum OccurrenceBindingResult<N> {
    OccurrenceBound {
        binding: Rc<OccurrenceBinding<N>>,
    },
    OccurrenceUnbound {
        occurrence: Rc<BindingOccurrence<N>>,
    },
    OccurrenceAmbiguous {
        occurrence: Rc<BindingOccurrence<N>>,
        candidates: Rc<AmbiguousBindingCandidates<N>>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum OccurrenceBindingFoldState<N> {
    OccurrenceBindingFoldZero,
    OccurrenceBindingFoldOne {
        first: Rc<BindingCandidate<N>>,
    },
    OccurrenceBindingFoldMany {
        first: Rc<BindingCandidate<N>>,
        second: Rc<BindingCandidate<N>>,
        rest_reversed: Rc<Vec<Rc<BindingCandidate<N>>>>,
    },
}
impl<N> OccurrenceBindingFoldState<N> {
    pub fn first(&self) -> Rc<BindingCandidate<N>> {
        match self {
            OccurrenceBindingFoldState::OccurrenceBindingFoldZero => {
                panic!("no first on unit variant")
            }
            OccurrenceBindingFoldState::OccurrenceBindingFoldOne { first: __val, .. } => {
                __val.clone()
            }
            OccurrenceBindingFoldState::OccurrenceBindingFoldMany { first: __val, .. } => {
                __val.clone()
            }
        }
    }
}

pub fn occurrence_binding_from_candidates<N>(
    occurrence: Rc<BindingOccurrence<N>>,
    candidates: Rc<Vec<Rc<BindingCandidate<N>>>>,
) -> Rc<OccurrenceBindingResult<N>> {
    {
        let state = candidates.clone().iter().cloned().fold(
            Rc::new(OccurrenceBindingFoldState::OccurrenceBindingFoldZero),
            |state: Rc<OccurrenceBindingFoldState<N>>, candidate: Rc<BindingCandidate<N>>| {
                match (*state).clone() {
                    OccurrenceBindingFoldState::OccurrenceBindingFoldZero => {
                        Rc::new(OccurrenceBindingFoldState::OccurrenceBindingFoldOne {
                            first: candidate.clone(),
                        })
                    }
                    OccurrenceBindingFoldState::OccurrenceBindingFoldOne {
                        first: first, ..
                    } => Rc::new(OccurrenceBindingFoldState::OccurrenceBindingFoldMany {
                        first: first.clone(),
                        second: candidate.clone(),
                        rest_reversed: Rc::new(vec![]),
                    }),
                    OccurrenceBindingFoldState::OccurrenceBindingFoldMany {
                        first,
                        second,
                        rest_reversed,
                        ..
                    } => Rc::new(OccurrenceBindingFoldState::OccurrenceBindingFoldMany {
                        first: first.clone(),
                        second: second.clone(),
                        rest_reversed: Rc::new({
                            let mut __cons_v = (*rest_reversed.clone()).clone();
                            __cons_v.insert(0, candidate.clone());
                            __cons_v
                        }),
                    }),
                }
            },
        );
        match (*state.clone()).clone() {
            OccurrenceBindingFoldState::OccurrenceBindingFoldZero => {
                Rc::new(OccurrenceBindingResult::OccurrenceUnbound {
                    occurrence: occurrence.clone(),
                })
            }
            OccurrenceBindingFoldState::OccurrenceBindingFoldOne { first: first, .. } => {
                Rc::new(OccurrenceBindingResult::OccurrenceBound {
                    binding: Rc::new(OccurrenceBinding {
                        occurrence: occurrence.clone(),
                        candidate: first.clone(),
                        _phantom: std::marker::PhantomData,
                    }),
                })
            }
            OccurrenceBindingFoldState::OccurrenceBindingFoldMany {
                first,
                second,
                rest_reversed,
                ..
            } => Rc::new(OccurrenceBindingResult::OccurrenceAmbiguous {
                occurrence: occurrence.clone(),
                candidates: Rc::new(AmbiguousBindingCandidates {
                    first: first.clone(),
                    second: second.clone(),
                    rest: v1_rt::reverse(rest_reversed.clone()),
                    _phantom: std::marker::PhantomData,
                }),
            }),
        }
    }
}
