// Generated by v1 compiler -- do not edit.
// Source module: std.algebra

use self::AlgebraProfile::*;
use self::AlgebraTypeTemplate::*;
use self::CarrierRowMembership::*;
use self::CollectionSizeEffect::*;
use self::ContainerSource::*;
use self::CostShape::*;
use self::Ordering::*;
use crate::std_error_primitives::DivError::*;
use crate::std_error_primitives::Result::*;
pub use crate::std_error_primitives::{DivError, Result};
use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

#[derive(Clone)]
pub struct Magma<T> {
    pub op: Rc<dyn Fn(T, T) -> T>,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct Semigroup<T> {
    pub op: Rc<dyn Fn(T, T) -> T>,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct Monoid<T> {
    pub op: Rc<dyn Fn(T, T) -> T>,
    pub identity: T,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct CommutativeMonoid<T> {
    pub op: Rc<dyn Fn(T, T) -> T>,
    pub identity: T,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct Group<T> {
    pub op: Rc<dyn Fn(T, T) -> T>,
    pub identity: T,
    pub inverse: Rc<dyn Fn(T) -> T>,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct AbelianGroup<T> {
    pub op: Rc<dyn Fn(T, T) -> T>,
    pub identity: T,
    pub inverse: Rc<dyn Fn(T) -> T>,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GroupCompletion<M: Clone> {
    pub pos: M,
    pub neg: M,
    pub _phantom: std::marker::PhantomData<M>,
}
// repr-grounding arm (b): GroupCompletion<M> carrier arithmetic, rendered from the
// pair-completion rows in std.trait_derive_shape (Add/Mul/Neg are row data; Sub/Div bodies
// remain keyed literals: only Add, Mul and Neg render from the PairCompletionSumOfProducts polynomial arms).
impl<M: Clone> std::ops::Neg for GroupCompletion<M> {
    type Output = Self;
    fn neg(self) -> Self::Output {
        GroupCompletion {
            pos: self.neg,
            neg: self.pos,
            _phantom: std::marker::PhantomData,
        }
    }
}
impl<M: Clone> std::ops::Add for GroupCompletion<M>
where
    M: std::ops::Add<Output = M>,
{
    type Output = Self;
    fn add(self, rhs: Self) -> Self::Output {
        GroupCompletion {
            pos: self.pos + rhs.pos,
            neg: self.neg + rhs.neg,
            _phantom: std::marker::PhantomData,
        }
    }
}
impl<M: Clone> std::ops::Sub for GroupCompletion<M>
where
    M: std::ops::Add<Output = M> + std::ops::Neg<Output = M>,
{
    type Output = Self;
    fn sub(self, rhs: Self) -> Self::Output {
        self + (-rhs)
    }
}
impl<M: Clone> std::ops::Mul for GroupCompletion<M>
where
    M: std::ops::Add<Output = M> + std::ops::Mul<Output = M> + Clone,
{
    type Output = Self;
    fn mul(self, rhs: Self) -> Self::Output {
        GroupCompletion {
            pos: self.pos.clone() * rhs.pos.clone() + self.neg.clone() * rhs.neg.clone(),
            neg: self.pos * rhs.neg + self.neg * rhs.pos,
            _phantom: std::marker::PhantomData,
        }
    }
}
impl<M: Clone> std::ops::Div for GroupCompletion<M>
where
    M: std::ops::Add<Output = M> + std::ops::Sub<Output = M> + std::ops::Div<Output = M> + Default,
{
    type Output = Self;
    fn div(self, rhs: Self) -> Self::Output {
        let q = (self.pos - self.neg) / (rhs.pos - rhs.neg);
        GroupCompletion {
            pos: q,
            neg: M::default(),
            _phantom: std::marker::PhantomData,
        }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FieldOfFractions<R: Clone> {
    pub num: R,
    pub denom: R,
    pub _phantom: std::marker::PhantomData<R>,
}

#[derive(Clone)]
pub struct Semiring<T> {
    pub add: Rc<dyn Fn(T, T) -> T>,
    pub zero: T,
    pub mul: Rc<dyn Fn(T, T) -> T>,
    pub one: T,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct CommutativeSemiring<T> {
    pub add: Rc<dyn Fn(T, T) -> T>,
    pub zero: T,
    pub mul: Rc<dyn Fn(T, T) -> T>,
    pub one: T,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct Ring<T> {
    pub add: Rc<dyn Fn(T, T) -> T>,
    pub zero: T,
    pub negate: Rc<dyn Fn(T) -> T>,
    pub mul: Rc<dyn Fn(T, T) -> T>,
    pub one: T,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct OrderedRing<T> {
    pub add: Rc<dyn Fn(T, T) -> T>,
    pub sub: Rc<dyn Fn(T, T) -> T>,
    pub zero: T,
    pub negate: Rc<dyn Fn(T) -> T>,
    pub mul: Rc<dyn Fn(T, T) -> T>,
    pub div: Rc<dyn Fn(T, T) -> Rc<Result<T, DivError>>>,
    pub one: T,
    pub compare: Rc<dyn Fn(T, T) -> Ordering>,
    pub eq: Rc<dyn Fn(T, T) -> bool>,
    pub ne: Rc<dyn Fn(T, T) -> bool>,
    pub lt: Rc<dyn Fn(T, T) -> bool>,
    pub le: Rc<dyn Fn(T, T) -> bool>,
    pub gt: Rc<dyn Fn(T, T) -> bool>,
    pub ge: Rc<dyn Fn(T, T) -> bool>,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct Field<T> {
    pub add: Rc<dyn Fn(T, T) -> T>,
    pub zero: T,
    pub negate: Rc<dyn Fn(T) -> T>,
    pub mul: Rc<dyn Fn(T, T) -> T>,
    pub one: T,
    pub reciprocal: Rc<dyn Fn(T) -> T>,
    pub compare: Rc<dyn Fn(T, T) -> Ordering>,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct Lattice<T> {
    pub meet: Rc<dyn Fn(T, T) -> T>,
    pub join: Rc<dyn Fn(T, T) -> T>,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct BoundedLattice<T> {
    pub meet: Rc<dyn Fn(T, T) -> T>,
    pub join: Rc<dyn Fn(T, T) -> T>,
    pub top: T,
    pub bottom: T,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct BooleanAlgebra<T> {
    pub meet: Rc<dyn Fn(T, T) -> T>,
    pub join: Rc<dyn Fn(T, T) -> T>,
    pub complement: Rc<dyn Fn(T) -> T>,
    pub top: T,
    pub bottom: T,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct PointwisePower<T> {
    pub member: Rc<dyn Fn(T) -> bool>,
    pub _phantom: std::marker::PhantomData<T>,
}

#[derive(Clone)]
pub struct FinitePowerSet<T> {
    pub member: Rc<dyn Fn(T) -> bool>,
    pub union: Rc<dyn Fn(Rc<FinitePowerSet<T>>) -> Rc<FinitePowerSet<T>>>,
    pub intersect: Rc<dyn Fn(Rc<FinitePowerSet<T>>) -> Rc<FinitePowerSet<T>>>,
    pub diff: Rc<dyn Fn(Rc<FinitePowerSet<T>>) -> Rc<FinitePowerSet<T>>>,
    pub contains: Rc<dyn Fn(T) -> bool>,
    pub count: Rc<dyn Fn() -> i64>,
    pub length: Rc<dyn Fn() -> i64>,
    pub _phantom: std::marker::PhantomData<T>,
}

pub type FreeMonoid<T> = Vec<T>;

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(bound(
    serialize = "T: Clone + serde::Serialize",
    deserialize = "T: Clone + serde::Deserialize<'de>"
))]
pub struct FreeSemigroup<T: Clone> {
    pub head: T,
    pub tail: Rc<FreeMonoid<T>>,
    pub _phantom: std::marker::PhantomData<T>,
}

impl<T: Clone + std::fmt::Debug> std::fmt::Debug for FreeSemigroup<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FreeSemigroup")
            .field("head", &self.head)
            .field("tail", &self.tail)
            .finish()
    }
}

impl<T: Clone + PartialEq> PartialEq for FreeSemigroup<T> {
    fn eq(&self, other: &Self) -> bool {
        self.head == other.head && self.tail == other.tail
    }
}

#[derive(Clone)]
pub struct PartialFunction<K, V> {
    pub lookup: Rc<dyn Fn(K) -> Option<V>>,
    pub _phantom: std::marker::PhantomData<(K, V)>,
}

#[derive(Clone)]
pub struct FinitelySupportedFunction<K, V> {
    pub lookup: Rc<dyn Fn(K) -> Option<V>>,
    pub empty: Rc<FinitelySupportedFunction<K, V>>,
    pub get: Rc<dyn Fn(K) -> Option<V>>,
    pub insert: Rc<dyn Fn(K, V) -> Rc<FinitelySupportedFunction<K, V>>>,
    pub merge:
        Rc<dyn Fn(Rc<FinitelySupportedFunction<K, V>>) -> Rc<FinitelySupportedFunction<K, V>>>,
    pub map_keys: Rc<dyn Fn() -> Rc<FreeMonoid<K>>>,
    pub map_values: Rc<dyn Fn() -> Rc<FreeMonoid<V>>>,
    pub map_has: Rc<dyn Fn(K) -> bool>,
    pub contains_key: Rc<dyn Fn(K) -> bool>,
    pub size: Rc<dyn Fn() -> i64>,
    pub _phantom: std::marker::PhantomData<(K, V)>,
}

#[derive(Clone)]
pub struct TotalMap<K, V> {
    pub lookup: Rc<dyn Fn(K) -> V>,
    pub _phantom: std::marker::PhantomData<(K, V)>,
}

#[derive(Clone)]
pub struct TotalPolicy<K, Context, RowTemplate> {
    pub lookup: Rc<dyn Fn(K, Context) -> RowTemplate>,
    pub _phantom: std::marker::PhantomData<(K, Context, RowTemplate)>,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum Ordering {
    Less,
    Equal,
    Greater,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct OrderingFold<R: Clone> {
    pub less: R,
    pub equal: R,
    pub greater: R,
    pub _phantom: std::marker::PhantomData<R>,
}

pub fn ordering_fold<R: Clone>(o: Ordering, fold: Rc<OrderingFold<R>>) -> R {
    match o.clone() {
        Ordering::Less => fold.less.clone(),
        Ordering::Equal => fold.equal.clone(),
        Ordering::Greater => fold.greater.clone(),
    }
}

pub fn ordering_is_less(o: Ordering) -> bool {
    ordering_fold(
        o.clone(),
        Rc::new(OrderingFold {
            less: true,
            equal: false,
            greater: false,
            _phantom: std::marker::PhantomData,
        }),
    )
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum AlgebraProfile {
    OrderedRingProfile,
    ApproximateFieldProfile,
    BooleanAlgebraProfile,
    FinitePowerSetProfile,
    PointwisePowerCollectionProfile,
    FreeMonoidScalarProfile,
    FreeMonoidCollectionProfile,
    PartialFunctionProfile,
    FinitelySupportedFunctionProfile,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum ContainerSource {
    SameAsReceiver,
    Named { name: String },
}
impl ContainerSource {
    pub fn name(&self) -> String {
        match self {
            ContainerSource::SameAsReceiver => panic!("no name on unit variant"),
            ContainerSource::Named { name: __val, .. } => __val.clone(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum AlgebraTypeTemplate {
    ReceiverSelf,
    ReceiverElement,
    ReceiverKey,
    ReceiverValue,
    NamedTemplate {
        name: String,
    },
    ContainerOf {
        source: Rc<ContainerSource>,
        element: Rc<AlgebraTypeTemplate>,
    },
    OptionalOf {
        inner: Rc<AlgebraTypeTemplate>,
    },
    WitnessOf {
        inner: Rc<AlgebraTypeTemplate>,
    },
    TupleOf {
        first: Rc<AlgebraTypeTemplate>,
        second: Rc<AlgebraTypeTemplate>,
    },
    CallableOf {
        params: Rc<Vec<Rc<AlgebraTypeTemplate>>>,
        return_type: Rc<AlgebraTypeTemplate>,
    },
    AlgebraTypeVariable {
        id: String,
    },
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum CollectionSizeEffect {
    ShrinkEffect,
    ProjectionEffect,
    IdentityEffect,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum CostShape {
    ShapeConstant,
    ShapeLinearScan,
    ShapeIterateBody,
    ShapeSortBody,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AlgebraFieldTemplate {
    pub name: String,
    pub param_types: Rc<Vec<Rc<AlgebraTypeTemplate>>>,
    pub return_type: Rc<AlgebraTypeTemplate>,
    pub size_effect: Option<CollectionSizeEffect>,
    pub cost_shape: Option<CostShape>,
    pub callback_element_position: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum CarrierRowMembership {
    RowPresent,
    RowAbsent { reason: String },
}
impl CarrierRowMembership {
    pub fn reason(&self) -> String {
        match self {
            CarrierRowMembership::RowPresent => panic!("no reason on unit variant"),
            CarrierRowMembership::RowAbsent { reason: __val, .. } => __val.clone(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CarrierSpelling {
    pub text: String,
    pub method_surface: Rc<CarrierRowMembership>,
    pub container_algebra_row: Rc<CarrierRowMembership>,
    pub container_alias_row: Rc<CarrierRowMembership>,
    pub container_roster_name: Rc<CarrierRowMembership>,
    pub container_arity_row: Rc<CarrierRowMembership>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AlgebraCarrier {
    pub name: String,
    pub profile: AlgebraProfile,
    pub spellings: Rc<Vec<Rc<CarrierSpelling>>>,
}

pub fn scalar_carrier_not_container_reason() -> String {
    thread_local! {
        static CACHED: String = {
            "scalar carrier: names no container, so it holds no container-spelling row".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn snake_case_spelling_not_alias_reason() -> String {
    thread_local! {
        static CACHED: String = {
            "snake spelling: resolves as an algebra name, not as a declared container alias".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn canonical_spelling_sorts_ahead_of_alias_reason() -> String {
    thread_local! {
        static CACHED: String = {
            "container_alias_canonical_spelling returns the FIRST sorted key mapping to an algebra, so this key would sort ahead of its own alias and silently become the emitted canonical spelling".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn carrier_name_is_not_a_declaration_spelling_reason() -> String {
    thread_local! {
        static CACHED: String = {
            "the carrier name is not written in declaration position; its alias carries the profile".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn arity_row_is_alias_spellings_only_reason() -> String {
    thread_local! {
        static CACHED: String = {
            "container_type_arity is consulted by is_container_type on authored declaration spellings; adding a key here decides containerhood for that spelling".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn scalar_carrier_spelling(text: String) -> Rc<CarrierSpelling> {
    Rc::new(CarrierSpelling {
        text: text.clone(),
        method_surface: Rc::new(CarrierRowMembership::RowPresent),
        container_algebra_row: Rc::new(CarrierRowMembership::RowAbsent {
            reason: scalar_carrier_not_container_reason(),
        }),
        container_alias_row: Rc::new(CarrierRowMembership::RowAbsent {
            reason: scalar_carrier_not_container_reason(),
        }),
        container_roster_name: Rc::new(CarrierRowMembership::RowAbsent {
            reason: scalar_carrier_not_container_reason(),
        }),
        container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
            reason: scalar_carrier_not_container_reason(),
        }),
    })
}

pub fn snake_alias_spelling(text: String) -> Rc<CarrierSpelling> {
    Rc::new(CarrierSpelling {
        text: text.clone(),
        method_surface: Rc::new(CarrierRowMembership::RowAbsent {
            reason: carrier_name_is_not_a_declaration_spelling_reason(),
        }),
        container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
        container_alias_row: Rc::new(CarrierRowMembership::RowPresent),
        container_roster_name: Rc::new(CarrierRowMembership::RowAbsent {
            reason: snake_case_spelling_not_alias_reason(),
        }),
        container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
            reason: arity_row_is_alias_spellings_only_reason(),
        }),
    })
}

pub fn snake_algebra_spelling(text: String) -> Rc<CarrierSpelling> {
    Rc::new(CarrierSpelling {
        text: text.clone(),
        method_surface: Rc::new(CarrierRowMembership::RowAbsent {
            reason: carrier_name_is_not_a_declaration_spelling_reason(),
        }),
        container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
        container_alias_row: Rc::new(CarrierRowMembership::RowAbsent {
            reason: snake_case_spelling_not_alias_reason(),
        }),
        container_roster_name: Rc::new(CarrierRowMembership::RowAbsent {
            reason: snake_case_spelling_not_alias_reason(),
        }),
        container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
            reason: arity_row_is_alias_spellings_only_reason(),
        }),
    })
}

pub fn pascal_alias_spelling(text: String) -> Rc<CarrierSpelling> {
    Rc::new(CarrierSpelling {
        text: text.clone(),
        method_surface: Rc::new(CarrierRowMembership::RowPresent),
        container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
        container_alias_row: Rc::new(CarrierRowMembership::RowPresent),
        container_roster_name: Rc::new(CarrierRowMembership::RowPresent),
        container_arity_row: Rc::new(CarrierRowMembership::RowPresent),
    })
}

pub fn algebra_carriers() -> Rc<Vec<Rc<AlgebraCarrier>>> {
    Rc::new(vec![Rc::new(AlgebraCarrier {
    name: "Int".to_string(),
    profile: AlgebraProfile::OrderedRingProfile,
    spellings: Rc::new(vec![scalar_carrier_spelling("Int".to_string())]),
}), Rc::new(AlgebraCarrier {
    name: "Float".to_string(),
    profile: AlgebraProfile::ApproximateFieldProfile,
    spellings: Rc::new(vec![scalar_carrier_spelling("Float".to_string())]),
}), Rc::new(AlgebraCarrier {
    name: "BooleanAlgebra".to_string(),
    profile: AlgebraProfile::BooleanAlgebraProfile,
    spellings: Rc::new(vec![scalar_carrier_spelling("Bool".to_string()), Rc::new(CarrierSpelling {
    text: "BooleanAlgebra".to_string(),
    method_surface: Rc::new(CarrierRowMembership::RowAbsent {
    reason: carrier_name_is_not_a_declaration_spelling_reason(),
}),
    container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
    container_alias_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: canonical_spelling_sorts_ahead_of_alias_reason(),
}),
    container_roster_name: Rc::new(CarrierRowMembership::RowAbsent {
    reason: "the lattice is not a container: its container inhabitant row moved to FinitePowerSet".to_string(),
}),
    container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: arity_row_is_alias_spellings_only_reason(),
}),
}), snake_algebra_spelling("boolean_algebra".to_string())]),
}), Rc::new(AlgebraCarrier {
    name: "String".to_string(),
    profile: AlgebraProfile::FreeMonoidScalarProfile,
    spellings: Rc::new(vec![scalar_carrier_spelling("String".to_string())]),
}), Rc::new(AlgebraCarrier {
    name: "FreeMonoid".to_string(),
    profile: AlgebraProfile::FreeMonoidCollectionProfile,
    spellings: Rc::new(vec![pascal_alias_spelling("List".to_string()), snake_alias_spelling("list".to_string()), Rc::new(CarrierSpelling {
    text: "FreeMonoid".to_string(),
    method_surface: Rc::new(CarrierRowMembership::RowAbsent {
    reason: carrier_name_is_not_a_declaration_spelling_reason(),
}),
    container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
    container_alias_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: canonical_spelling_sorts_ahead_of_alias_reason(),
}),
    container_roster_name: Rc::new(CarrierRowMembership::RowPresent),
    container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: arity_row_is_alias_spellings_only_reason(),
}),
}), snake_algebra_spelling("free_monoid".to_string())]),
}), Rc::new(AlgebraCarrier {
    name: "FinitePowerSet".to_string(),
    profile: AlgebraProfile::FinitePowerSetProfile,
    spellings: Rc::new(vec![pascal_alias_spelling("Set".to_string()), snake_alias_spelling("set".to_string()), Rc::new(CarrierSpelling {
    text: "FinitePowerSet".to_string(),
    method_surface: Rc::new(CarrierRowMembership::RowPresent),
    container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
    container_alias_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: canonical_spelling_sorts_ahead_of_alias_reason(),
}),
    container_roster_name: Rc::new(CarrierRowMembership::RowPresent),
    container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: arity_row_is_alias_spellings_only_reason(),
}),
}), snake_algebra_spelling("finite_power_set".to_string())]),
}), Rc::new(AlgebraCarrier {
    name: "FinitelySupportedFunction".to_string(),
    profile: AlgebraProfile::FinitelySupportedFunctionProfile,
    spellings: Rc::new(vec![pascal_alias_spelling("Map".to_string()), snake_alias_spelling("map".to_string()), Rc::new(CarrierSpelling {
    text: "FinitelySupportedFunction".to_string(),
    method_surface: Rc::new(CarrierRowMembership::RowPresent),
    container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
    container_alias_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: canonical_spelling_sorts_ahead_of_alias_reason(),
}),
    container_roster_name: Rc::new(CarrierRowMembership::RowPresent),
    container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: arity_row_is_alias_spellings_only_reason(),
}),
}), snake_algebra_spelling("finitely_supported_function".to_string())]),
}), Rc::new(AlgebraCarrier {
    name: "PartialFunction".to_string(),
    profile: AlgebraProfile::PartialFunctionProfile,
    spellings: Rc::new(vec![Rc::new(CarrierSpelling {
    text: "PartialFunction".to_string(),
    method_surface: Rc::new(CarrierRowMembership::RowPresent),
    container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
    container_alias_row: Rc::new(CarrierRowMembership::RowPresent),
    container_roster_name: Rc::new(CarrierRowMembership::RowPresent),
    container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: arity_row_is_alias_spellings_only_reason(),
}),
}), snake_alias_spelling("partial_function".to_string())]),
}), Rc::new(AlgebraCarrier {
    name: "PointwisePower".to_string(),
    profile: AlgebraProfile::PointwisePowerCollectionProfile,
    spellings: Rc::new(vec![Rc::new(CarrierSpelling {
    text: "PointwisePower".to_string(),
    method_surface: Rc::new(CarrierRowMembership::RowAbsent {
    reason: "80 declaration positions would flip from MethodExistenceUndecided to a hard MethodNotFound for any method absent from pointwise_power_collection_templates; that measurement is not taken".to_string(),
}),
    container_algebra_row: Rc::new(CarrierRowMembership::RowPresent),
    container_alias_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: canonical_spelling_sorts_ahead_of_alias_reason(),
}),
    container_roster_name: Rc::new(CarrierRowMembership::RowPresent),
    container_arity_row: Rc::new(CarrierRowMembership::RowAbsent {
    reason: arity_row_is_alias_spellings_only_reason(),
}),
}), snake_algebra_spelling("pointwise_power".to_string())]),
})])
}

pub fn carrier_spelling_row_present(m: Rc<CarrierRowMembership>) -> bool {
    match (*m.clone()).clone() {
        CarrierRowMembership::RowPresent => true,
        CarrierRowMembership::RowAbsent { reason: _, .. } => false,
    }
}

pub fn kernel_algebra_profile_value() -> Rc<HashMap<String, AlgebraProfile>> {
    algebra_carriers().iter().cloned().fold(
        v1_rt::rc_empty_map::<String, AlgebraProfile>(),
        |acc: Rc<HashMap<String, AlgebraProfile>>, carrier: Rc<AlgebraCarrier>| {
            carrier.spellings.clone().iter().cloned().fold(
                acc,
                |inner: Rc<HashMap<String, AlgebraProfile>>, spelling: Rc<CarrierSpelling>| {
                    if carrier_spelling_row_present(spelling.method_surface.clone()) {
                        v1_rt::rc_map_insert(
                            inner.clone(),
                            spelling.text.clone(),
                            carrier.profile.clone(),
                        )
                    } else {
                        inner.clone()
                    }
                },
            )
        },
    )
}

pub fn carrier_container_algebra_rows() -> Rc<HashMap<String, String>> {
    algebra_carriers().iter().cloned().fold(
        v1_rt::rc_empty_map::<String, String>(),
        |acc: Rc<HashMap<String, String>>, carrier: Rc<AlgebraCarrier>| {
            carrier.spellings.clone().iter().cloned().fold(
                acc,
                |inner: Rc<HashMap<String, String>>, spelling: Rc<CarrierSpelling>| {
                    if carrier_spelling_row_present(spelling.container_algebra_row.clone()) {
                        v1_rt::rc_map_insert(
                            inner.clone(),
                            spelling.text.clone(),
                            carrier.name.clone(),
                        )
                    } else {
                        inner.clone()
                    }
                },
            )
        },
    )
}

pub fn carrier_container_alias_rows() -> Rc<HashMap<String, String>> {
    algebra_carriers().iter().cloned().fold(
        v1_rt::rc_empty_map::<String, String>(),
        |acc: Rc<HashMap<String, String>>, carrier: Rc<AlgebraCarrier>| {
            carrier.spellings.clone().iter().cloned().fold(
                acc,
                |inner: Rc<HashMap<String, String>>, spelling: Rc<CarrierSpelling>| {
                    if carrier_spelling_row_present(spelling.container_alias_row.clone()) {
                        v1_rt::rc_map_insert(
                            inner.clone(),
                            spelling.text.clone(),
                            carrier.name.clone(),
                        )
                    } else {
                        inner.clone()
                    }
                },
            )
        },
    )
}

pub fn carrier_container_roster_map() -> Rc<HashMap<String, bool>> {
    algebra_carriers().iter().cloned().fold(
        v1_rt::rc_empty_map::<String, bool>(),
        |acc: Rc<HashMap<String, bool>>, carrier: Rc<AlgebraCarrier>| {
            carrier.spellings.clone().iter().cloned().fold(
                acc,
                |inner: Rc<HashMap<String, bool>>, spelling: Rc<CarrierSpelling>| {
                    if carrier_spelling_row_present(spelling.container_roster_name.clone()) {
                        v1_rt::rc_map_insert(inner.clone(), spelling.text.clone(), true)
                    } else {
                        inner.clone()
                    }
                },
            )
        },
    )
}

pub fn carrier_container_arity_rows() -> Rc<HashMap<String, i64>> {
    algebra_carriers().iter().cloned().fold(
        v1_rt::rc_empty_map::<String, i64>(),
        |acc: Rc<HashMap<String, i64>>, carrier: Rc<AlgebraCarrier>| {
            carrier.spellings.clone().iter().cloned().fold(
                acc,
                |inner: Rc<HashMap<String, i64>>, spelling: Rc<CarrierSpelling>| {
                    if carrier_spelling_row_present(spelling.container_arity_row.clone()) {
                        v1_rt::rc_map_insert(
                            inner.clone(),
                            spelling.text.clone(),
                            algebra_type_param_names(carrier.profile.clone())
                                .iter()
                                .fold(0, |n: i64, _| (n + 1)),
                        )
                    } else {
                        inner.clone()
                    }
                },
            )
        },
    )
}

pub fn kernel_algebra_profile() -> Rc<HashMap<String, AlgebraProfile>> {
    thread_local! {
        static CACHED: Rc<HashMap<String, AlgebraProfile>> = {
            kernel_algebra_profile_value()
        };
    }
    CACHED.with(|c: &Rc<HashMap<String, AlgebraProfile>>| c.clone())
}

pub fn ordered_ring_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![
        Rc::new(AlgebraFieldTemplate {
            name: "add".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "zero".to_string(),
            param_types: Rc::new(vec![]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "negate".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "mul".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "one".to_string(),
            param_types: Rc::new(vec![]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "compare".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Ordering".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "clamp".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeConstant),
            callback_element_position: None,
        }),
    ])
}

pub fn approximate_field_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![
        Rc::new(AlgebraFieldTemplate {
            name: "add".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "zero".to_string(),
            param_types: Rc::new(vec![]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "negate".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "mul".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "one".to_string(),
            param_types: Rc::new(vec![]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "reciprocal".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "compare".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Ordering".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
    ])
}

pub fn boolean_algebra_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![
        Rc::new(AlgebraFieldTemplate {
            name: "meet".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "join".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "complement".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "top".to_string(),
            param_types: Rc::new(vec![]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "bottom".to_string(),
            param_types: Rc::new(vec![]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
    ])
}

pub fn finite_power_set_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![
        Rc::new(AlgebraFieldTemplate {
            name: "union".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "intersect".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "diff".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "member".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverElement),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "contains".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverElement),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "filter".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                        name: "Bool".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: Some(CollectionSizeEffect::IdentityEffect),
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                        id: "MappedElement".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::SameAsReceiver),
                element: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                    id: "MappedElement".to_string(),
                }),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "flat_map".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                        source: Rc::new(ContainerSource::SameAsReceiver),
                        element: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                            id: "MappedElement".to_string(),
                        }),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::SameAsReceiver),
                element: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                    id: "MappedElement".to_string(),
                }),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "fold".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                    id: "FoldAccumulator".to_string(),
                }),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![
                        Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                            id: "FoldAccumulator".to_string(),
                        }),
                        Rc::new(AlgebraTypeTemplate::ReceiverElement),
                    ]),
                    return_type: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                        id: "FoldAccumulator".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                id: "FoldAccumulator".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(1),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "any".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                        name: "Bool".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "all".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                        name: "Bool".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "count".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "length".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
    ])
}

pub fn pointwise_power_collection_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![Rc::new(AlgebraFieldTemplate {
        name: "member".to_string(),
        param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::CallableOf {
            params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
        })]),
        return_type: Rc::new(AlgebraTypeTemplate::CallableOf {
            params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
        }),
        size_effect: None,
        cost_shape: None,
        callback_element_position: None,
    })])
}

pub fn algebra_count_length_name_fork_note() -> String {
    thread_local! {
        static CACHED: String = {
            "count and length sit on the same template rows as the SAME operation, and that is a section 3 nicknaming fork being RECORDED rather than introduced (review 45499 raised it, correctly, as a smell). The fork's authority is the interpreter, which dispatches length, count and size to one native arm -- three names, one concept, and that arm predates this change. What was inconsistent was the declared surface: the templates listed only length, so a String receiver piped into count resolved at runtime while having no declared row, which the method-existence wall exposed the moment it began proving absence from the template roster. Reconciling the declaration to the runtime is the honest direction, because the runtime is what programs actually meet; inventing a distinct meaning for count to justify two rows would be the fabrication, and dropping the row would have left a working call refused. So the row is added and the fork is named here rather than silently propagated. Dissolve-on: feature:collection-size-single-spelling -- one name for this operation across the interpreter arm, the templates, and the corpus, a corpus-wide rename touching every call site, which belongs on its own lane rather than inside a P0 live-system fix. THE TRIGGER IS NAMED RATHER THAN DESCRIBED because a deferral whose condition is only prose cannot be looked up, counted, or closed by anyone but its author -- the asymmetry review 45759 caught beside unresolved_method_frontier, which cites feature:primitive-realization-single-authority and is therefore findable. The closing condition is decidable and stated: the interpreter's length/count/size arm dispatches one spelling, these two template rows carry that spelling only, and no other spelling resolves. Until then the count is the measure: three accepted spellings in the interpreter arm, two on these rows, one concept.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn free_monoid_scalar_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![
        Rc::new(AlgebraFieldTemplate {
            name: "concat".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "empty".to_string(),
            param_types: Rc::new(vec![]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "length".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "count".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "is_empty".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "chars".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::Named {
                    name: "List".to_string(),
                }),
                element: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                    name: "Int".to_string(),
                }),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "split".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::Named {
                    name: "List".to_string(),
                }),
                element: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "join".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ContainerOf {
                    source: Rc::new(ContainerSource::Named {
                        name: "List".to_string(),
                    }),
                    element: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                }),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "contains".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "starts_with".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "ends_with".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "trim".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "to_lower".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "to_upper".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "replace".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "substring".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::NamedTemplate {
                    name: "Int".to_string(),
                }),
                Rc::new(AlgebraTypeTemplate::NamedTemplate {
                    name: "Int".to_string(),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "to_int".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "to_string".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "reverse".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
    ])
}

pub fn free_monoid_collection_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![
        Rc::new(AlgebraFieldTemplate {
            name: "map".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                        id: "MappedElement".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::SameAsReceiver),
                element: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                    id: "MappedElement".to_string(),
                }),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "filter".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                        name: "Bool".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: Some(CollectionSizeEffect::IdentityEffect),
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "flat_map".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                        source: Rc::new(ContainerSource::SameAsReceiver),
                        element: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                            id: "MappedElement".to_string(),
                        }),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::SameAsReceiver),
                element: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                    id: "MappedElement".to_string(),
                }),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "fold".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                    id: "FoldAccumulator".to_string(),
                }),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![
                        Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                            id: "FoldAccumulator".to_string(),
                        }),
                        Rc::new(AlgebraTypeTemplate::ReceiverElement),
                    ]),
                    return_type: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                        id: "FoldAccumulator".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                id: "FoldAccumulator".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(1),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "any".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                        name: "Bool".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "all".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                        name: "Bool".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "count".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "first".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverElement),
            }),
            size_effect: Some(CollectionSizeEffect::ProjectionEffect),
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "last".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverElement),
            }),
            size_effect: Some(CollectionSizeEffect::ProjectionEffect),
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "get".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::NamedTemplate {
                    name: "Int".to_string(),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverElement),
            }),
            size_effect: Some(CollectionSizeEffect::ProjectionEffect),
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "skip".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::NamedTemplate {
                    name: "Int".to_string(),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: Some(CollectionSizeEffect::ShrinkEffect),
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "take".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::NamedTemplate {
                    name: "Int".to_string(),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "sort_by".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::CallableOf {
                    params: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverElement)]),
                    return_type: Rc::new(AlgebraTypeTemplate::AlgebraTypeVariable {
                        id: "SortKey".to_string(),
                    }),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: Some(CollectionSizeEffect::IdentityEffect),
            cost_shape: Some(CostShape::ShapeSortBody),
            callback_element_position: Some(0),
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "append".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverElement),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeConstant),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "contains".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverElement),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "enumerate".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::SameAsReceiver),
                element: Rc::new(AlgebraTypeTemplate::TupleOf {
                    first: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                        name: "Int".to_string(),
                    }),
                    second: Rc::new(AlgebraTypeTemplate::ReceiverElement),
                }),
            }),
            size_effect: Some(CollectionSizeEffect::IdentityEffect),
            cost_shape: Some(CostShape::ShapeIterateBody),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "reverse".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: Some(CollectionSizeEffect::IdentityEffect),
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "join".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::NamedTemplate {
                    name: "String".to_string(),
                }),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "String".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "concat".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "list_push".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverElement),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "length".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "is_empty".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: Some(CostShape::ShapeLinearScan),
            callback_element_position: None,
        }),
    ])
}

pub fn partial_function_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![
        Rc::new(AlgebraFieldTemplate {
            name: "get".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverValue),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map_get".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverValue),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "lookup".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverValue),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
    ])
}

pub fn finitely_supported_function_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new(vec![
        Rc::new(AlgebraFieldTemplate {
            name: "get".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverValue),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map_get".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverValue),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "lookup".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::OptionalOf {
                inner: Rc::new(AlgebraTypeTemplate::ReceiverValue),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map_insert".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
                Rc::new(AlgebraTypeTemplate::ReceiverValue),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map_merge".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map_has".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map_contains_key".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map_keys".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::Named {
                    name: "List".to_string(),
                }),
                element: Rc::new(AlgebraTypeTemplate::ReceiverKey),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "map_values".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::ContainerOf {
                source: Rc::new(ContainerSource::Named {
                    name: "List".to_string(),
                }),
                element: Rc::new(AlgebraTypeTemplate::ReceiverValue),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "with".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
                Rc::new(AlgebraTypeTemplate::ReceiverValue),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::ReceiverSelf),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "contains".to_string(),
            param_types: Rc::new(vec![
                Rc::new(AlgebraTypeTemplate::ReceiverSelf),
                Rc::new(AlgebraTypeTemplate::ReceiverKey),
            ]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Bool".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "length".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
        Rc::new(AlgebraFieldTemplate {
            name: "count".to_string(),
            param_types: Rc::new(vec![Rc::new(AlgebraTypeTemplate::ReceiverSelf)]),
            return_type: Rc::new(AlgebraTypeTemplate::NamedTemplate {
                name: "Int".to_string(),
            }),
            size_effect: None,
            cost_shape: None,
            callback_element_position: None,
        }),
    ])
}

pub fn algebra_method_template_name(name: String) -> bool {
    {
        let mut __found = false;
        for profile in all_algebra_profiles().iter().cloned() {
            if {
                let mut __found = false;
                for t in algebra_templates_for_profile(profile.clone())
                    .iter()
                    .cloned()
                {
                    if (t.name.clone() == name.clone()) {
                        __found = true;
                        break;
                    }
                }
                __found
            } {
                __found = true;
                break;
            }
        }
        __found
    }
}

pub fn algebra_templates_for_profile(profile: AlgebraProfile) -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    match profile.clone() {
        AlgebraProfile::OrderedRingProfile => ordered_ring_templates(),
        AlgebraProfile::ApproximateFieldProfile => approximate_field_templates(),
        AlgebraProfile::BooleanAlgebraProfile => boolean_algebra_templates(),
        AlgebraProfile::FinitePowerSetProfile => finite_power_set_templates(),
        AlgebraProfile::PointwisePowerCollectionProfile => pointwise_power_collection_templates(),
        AlgebraProfile::FreeMonoidScalarProfile => free_monoid_scalar_templates(),
        AlgebraProfile::FreeMonoidCollectionProfile => free_monoid_collection_templates(),
        AlgebraProfile::PartialFunctionProfile => partial_function_templates(),
        AlgebraProfile::FinitelySupportedFunctionProfile => finitely_supported_function_templates(),
    }
}

pub fn algebra_type_param_names(profile: AlgebraProfile) -> Rc<Vec<String>> {
    match profile.clone() {
        AlgebraProfile::OrderedRingProfile => Rc::new(vec![]),
        AlgebraProfile::ApproximateFieldProfile => Rc::new(vec![]),
        AlgebraProfile::BooleanAlgebraProfile => Rc::new(vec![]),
        AlgebraProfile::FinitePowerSetProfile => Rc::new(vec!["T".to_string()]),
        AlgebraProfile::PointwisePowerCollectionProfile => Rc::new(vec!["T".to_string()]),
        AlgebraProfile::FreeMonoidScalarProfile => Rc::new(vec![]),
        AlgebraProfile::FreeMonoidCollectionProfile => Rc::new(vec!["T".to_string()]),
        AlgebraProfile::PartialFunctionProfile => Rc::new(vec!["K".to_string(), "V".to_string()]),
        AlgebraProfile::FinitelySupportedFunctionProfile => {
            Rc::new(vec!["K".to_string(), "V".to_string()])
        }
    }
}

pub fn all_algebra_profiles() -> Rc<Vec<AlgebraProfile>> {
    Rc::new(vec![
        AlgebraProfile::OrderedRingProfile,
        AlgebraProfile::ApproximateFieldProfile,
        AlgebraProfile::BooleanAlgebraProfile,
        AlgebraProfile::FinitePowerSetProfile,
        AlgebraProfile::PointwisePowerCollectionProfile,
        AlgebraProfile::FreeMonoidScalarProfile,
        AlgebraProfile::FreeMonoidCollectionProfile,
        AlgebraProfile::PartialFunctionProfile,
        AlgebraProfile::FinitelySupportedFunctionProfile,
    ])
}

pub fn all_algebra_field_templates() -> Rc<Vec<Rc<AlgebraFieldTemplate>>> {
    Rc::new({
        let mut __result = Vec::new();
        for profile in all_algebra_profiles().iter().cloned() {
            __result.extend(
                (*algebra_templates_for_profile(profile.clone()))
                    .iter()
                    .cloned(),
            );
        }
        __result
    })
}

pub fn all_algebra_template_names() -> Rc<Vec<String>> {
    Rc::new({
        let mut __result = Vec::new();
        for template in all_algebra_field_templates().iter().cloned() {
            __result.push(template.name.clone());
        }
        __result
    })
}

pub fn trim_free_function_authority_note() -> String {
    thread_local! {
        static CACHED: String = {
            "trim is the importable free-function authority for whitespace trim on String. The declared substrate body is a pure-dag seam (1 / 0); semantic execution routes through free_call.trim (v1_rt::trim). Host realization authority: std.primitives trim_contract. Emitted host-native std.algebra::trim delegates to v1_rt::trim via rust_host_string_op_fn_emit. The scalar template row trim on FreeMonoid<String> is the method spelling on the same carrier. Free-call trim(s) requires explicit import std.algebra { trim } -- bare trim refuses via closure_independent_bare_free_call registry in v1.compiler.infer_env even when std.algebra is already in the compilation pool (#6985 Class B pool coincidence closed on trim by #8062).".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn trim(s: String) -> String {
    v1_rt::trim(s)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Less;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Equal;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Greater;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct OrderedRingProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ApproximateFieldProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct BooleanAlgebraProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct FinitePowerSetProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PointwisePowerCollectionProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct FreeMonoidScalarProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct FreeMonoidCollectionProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PartialFunctionProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct FinitelySupportedFunctionProfile;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ShrinkEffect;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ProjectionEffect;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct IdentityEffect;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ShapeConstant;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ShapeLinearScan;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ShapeIterateBody;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ShapeSortBody;
