// Generated by v1 compiler -- do not edit.
// Source module: std.literal_elaboration

use self::LiteralElaborationOutcome::*;
use self::LiteralElaborationRefusal::*;
use self::LiteralHomomorphismLookup::*;
use self::LiteralSourceKind::*;
use self::LiteralUnfolding::*;
pub use crate::std_decl_ref::declaration_ref_eq;
pub use crate::std_decl_ref::DeclarationRef;
pub use crate::std_syntax::LiteralValue;
use crate::std_syntax::LiteralValue::{LitBool, LitFloat, LitInt, LitNull, LitStr, LitSymbol};
use crate::std_types::Bool::*;
pub use crate::std_types::{Bool, List, NonEmptyStr};
use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum LiteralSourceKind {
    KernelIntLiteral,
    KernelStringLiteral,
    KernelFloatLiteral,
    KernelBoolLiteral,
    KernelSymbolLiteral,
    KernelNullLiteral,
}

pub fn literal_source_kind_of(value: Rc<LiteralValue>) -> LiteralSourceKind {
    match (*value.clone()).clone() {
        LiteralValue::LitInt { value: _, .. } => LiteralSourceKind::KernelIntLiteral,
        LiteralValue::LitStr { value: _, .. } => LiteralSourceKind::KernelStringLiteral,
        LiteralValue::LitFloat { value: _, .. } => LiteralSourceKind::KernelFloatLiteral,
        LiteralValue::LitBool { value: _, .. } => LiteralSourceKind::KernelBoolLiteral,
        LiteralValue::LitSymbol { value: _, .. } => LiteralSourceKind::KernelSymbolLiteral,
        LiteralValue::LitNull => LiteralSourceKind::KernelNullLiteral,
    }
}

pub fn literal_source_kind_label(kind: LiteralSourceKind) -> String {
    match kind.clone() {
        LiteralSourceKind::KernelIntLiteral => "kernel_int_literal".to_string(),
        LiteralSourceKind::KernelStringLiteral => "kernel_string_literal".to_string(),
        LiteralSourceKind::KernelFloatLiteral => "kernel_float_literal".to_string(),
        LiteralSourceKind::KernelBoolLiteral => "kernel_bool_literal".to_string(),
        LiteralSourceKind::KernelSymbolLiteral => "kernel_symbol_literal".to_string(),
        LiteralSourceKind::KernelNullLiteral => "kernel_null_literal".to_string(),
    }
}

pub fn literal_source_kind_eq(a: LiteralSourceKind, b: LiteralSourceKind) -> bool {
    (literal_source_kind_label(a.clone()) == literal_source_kind_label(b.clone()))
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum LiteralUnfolding {
    PeanoUnfold {
        zero: Rc<DeclarationRef>,
        succ: Rc<DeclarationRef>,
        prev_field: NonEmptyStr,
    },
    BooleanUnfold {
        true_variant: Rc<DeclarationRef>,
        false_variant: Rc<DeclarationRef>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LiteralHomomorphism {
    pub source_kind: LiteralSourceKind,
    pub destination: Rc<DeclarationRef>,
    pub producer: Rc<LiteralUnfolding>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum LiteralHomomorphismLookup {
    LiteralHomomorphismFound { row: Rc<LiteralHomomorphism> },
    LiteralHomomorphismAbsent,
    LiteralHomomorphismAmbiguous { row_count: i64 },
}

pub fn literal_homomorphism_for(
    rows: Rc<Vec<Rc<LiteralHomomorphism>>>,
    source_kind: LiteralSourceKind,
    destination: Rc<DeclarationRef>,
) -> Rc<LiteralHomomorphismLookup> {
    {
        let matching = Rc::new({
            let mut __result = Vec::new();
            for r in rows.iter().cloned() {
                if (literal_source_kind_eq(r.source_kind.clone(), source_kind.clone())
                    && crate::std_decl_ref::declaration_ref_eq(
                        r.destination.clone(),
                        destination.clone(),
                    ))
                {
                    __result.push(r);
                }
            }
            __result
        });
        let n = (matching.clone().len() as i64);
        if (n.clone() == 0) {
            Rc::new(LiteralHomomorphismLookup::LiteralHomomorphismAbsent)
        } else {
            if (n.clone() == 1) {
                match matching.clone().first().cloned() {
                    Some(row) => Rc::new(LiteralHomomorphismLookup::LiteralHomomorphismFound {
                        row: row.clone(),
                    }),
                    std::option::Option::None => {
                        Rc::new(LiteralHomomorphismLookup::LiteralHomomorphismAbsent)
                    }
                }
            } else {
                Rc::new(LiteralHomomorphismLookup::LiteralHomomorphismAmbiguous {
                    row_count: n.clone(),
                })
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum LiteralElaborationRefusal {
    HomomorphismDuplicated {
        source_kind: LiteralSourceKind,
        destination: Rc<DeclarationRef>,
        row_count: i64,
    },
}
impl LiteralElaborationRefusal {
    pub fn source_kind(&self) -> LiteralSourceKind {
        match self {
            LiteralElaborationRefusal::HomomorphismDuplicated {
                source_kind: __val, ..
            } => __val.clone(),
        }
    }
    pub fn destination(&self) -> Rc<DeclarationRef> {
        match self {
            LiteralElaborationRefusal::HomomorphismDuplicated {
                destination: __val, ..
            } => __val.clone(),
        }
    }
    pub fn row_count(&self) -> i64 {
        match self {
            LiteralElaborationRefusal::HomomorphismDuplicated {
                row_count: __val, ..
            } => __val.clone(),
        }
    }
}

pub fn literal_elaboration_refusal_message(cause: Rc<LiteralElaborationRefusal>) -> String {
    match (*cause.clone()).clone() {
    LiteralElaborationRefusal::HomomorphismDuplicated { source_kind: k, destination: d, row_count: n, .. } => v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat("literal elaboration: ".to_string(), literal_source_kind_label(k.clone())), " into ".to_string()), d.module_path.clone()), ".".to_string()), d.decl_name.clone()), " has more than one declared homomorphism (gunbc.structural_realization_bindings authoring defect)".to_string()),
}
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum LiteralElaborationOutcome {
    DirectLiteral,
    ViaHomomorphism {
        homomorphism: Rc<LiteralHomomorphism>,
    },
    LiteralElaborationRefused {
        cause: Rc<LiteralElaborationRefusal>,
    },
}

pub fn elaborate_literal_at(
    rows: Rc<Vec<Rc<LiteralHomomorphism>>>,
    source_kind: LiteralSourceKind,
    destination: Rc<DeclarationRef>,
    destination_realizes_natively: bool,
) -> Rc<LiteralElaborationOutcome> {
    if destination_realizes_natively.clone() {
        Rc::new(LiteralElaborationOutcome::DirectLiteral)
    } else {
        match (*literal_homomorphism_for(rows.clone(), source_kind.clone(), destination.clone()))
            .clone()
        {
            LiteralHomomorphismLookup::LiteralHomomorphismFound { row: row, .. } => {
                Rc::new(LiteralElaborationOutcome::ViaHomomorphism {
                    homomorphism: row.clone(),
                })
            }
            LiteralHomomorphismLookup::LiteralHomomorphismAbsent => {
                Rc::new(LiteralElaborationOutcome::DirectLiteral)
            }
            LiteralHomomorphismLookup::LiteralHomomorphismAmbiguous { row_count: n, .. } => {
                Rc::new(LiteralElaborationOutcome::LiteralElaborationRefused {
                    cause: Rc::new(LiteralElaborationRefusal::HomomorphismDuplicated {
                        source_kind: source_kind.clone(),
                        destination: destination.clone(),
                        row_count: n.clone(),
                    }),
                })
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LiteralElaboration {
    pub source_kind: LiteralSourceKind,
    pub destination: Rc<DeclarationRef>,
    pub homomorphism: Rc<LiteralHomomorphism>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct KernelIntLiteral;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct KernelStringLiteral;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct KernelFloatLiteral;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct KernelBoolLiteral;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct KernelSymbolLiteral;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct KernelNullLiteral;
