// Generated by v1 compiler -- do not edit.
// Source module: std.computation

use self::CallPattern::*;
use self::IterationDimension::*;
use self::IterationPrimitive::*;
use self::ShrinkFactor::*;
use self::SizeBound::*;
pub use crate::std_algebra::kernel_algebra_profile;
pub use crate::std_algebra::AlgebraProfile;
use crate::std_algebra::AlgebraProfile::{
    ApproximateFieldProfile, BooleanAlgebraCollectionProfile, BooleanAlgebraProfile,
    FreeMonoidCollectionProfile, FreeMonoidScalarProfile, OrderedRingProfile,
    PartialFunctionProfile,
};
pub use crate::std_termination::positive_descent_count;
use crate::std_termination::DescentEvidence::DescentUnknown;
use crate::std_termination::PositiveDescentAmount::{AdditionalStep, OneStep};
use crate::std_termination::ProportionalDivisor::{DivideByTwo, StrictlyLarger};
use crate::std_termination::RankingDimension::*;
pub use crate::std_termination::{
    DescentEvidence, PositiveDescentAmount, ProportionalDivisor, RankingDimension,
};
use crate::v1_rt;
use crate::v1_rt::Witness;
use crate::v1_rt::Witness::{Holds, Violates};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use std::collections::BTreeSet;
use std::collections::HashMap;
use std::rc::Rc;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum SizeBound {
    CollectionSize { param: Rc<FreeMonoid<Nat>> },
    ParserStreamSize { witness: Rc<FreeMonoid<Nat>> },
    WorklistDrainSize { element: Rc<FreeMonoid<Nat>> },
    TreeSize { param: Rc<FreeMonoid<Nat>> },
    ArithmeticParam { param: Rc<FreeMonoid<Nat>> },
    ExplicitCountZero,
    ExplicitCountPositive { steps: Rc<PositiveDescentAmount> },
    Forever,
}

pub fn tree_size_bound(param: Rc<FreeMonoid<Nat>>) -> Rc<SizeBound> {
    Rc::new(SizeBound::TreeSize { param: param })
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum CallPattern {
    ChildAccessorCall {
        accessor: Rc<FreeMonoid<Nat>>,
    },
    CollectionShrinkCall {
        amount: Rc<PositiveDescentAmount>,
        collection: Rc<FreeMonoid<Nat>>,
    },
    ArithmeticSubtractCall {
        steps: Rc<PositiveDescentAmount>,
        ring_param: Rc<FreeMonoid<Nat>>,
    },
    ArithmeticDivideCall {
        divisor: Rc<ProportionalDivisor>,
        ring_param: Rc<FreeMonoid<Nat>>,
    },
    ParserAdvanceCall {
        witness: Rc<FreeMonoid<Nat>>,
    },
    WorklistDrainCall {
        element: Rc<FreeMonoid<Nat>>,
    },
    FoldBodyCall {
        outer_collection: Rc<FreeMonoid<Nat>>,
    },
    SameArgumentCall,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum ShrinkFactor {
    UnitShrink,
    ConstantShrink { steps: Rc<PositiveDescentAmount> },
    ProportionalShrink { divisor: Rc<ProportionalDivisor> },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoweringTarget {
    pub primitive: IterationPrimitive,
    pub bound: Rc<SizeBound>,
    pub evidence: DescentEvidence,
    pub factor: Option<Rc<ShrinkFactor>>,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum IterationPrimitive {
    Fold,
    Descend,
    Repeat,
}

pub fn lower_call_pattern(pattern: Rc<CallPattern>) -> Rc<LoweringTarget> {
    match (*pattern).clone() {
        CallPattern::ChildAccessorCall { accessor: a, .. } => Rc::new(LoweringTarget {
            primitive: IterationPrimitive::Descend,
            bound: Rc::new(SizeBound::TreeSize { param: a.clone() }),
            evidence: DescentEvidence::Strict,
            factor: None,
        }),
        CallPattern::CollectionShrinkCall {
            amount: p,
            collection: c,
            ..
        } => Rc::new(LoweringTarget {
            primitive: IterationPrimitive::Fold,
            bound: Rc::new(SizeBound::CollectionSize { param: c.clone() }),
            evidence: DescentEvidence::Strict,
            factor: Some(Rc::new(ShrinkFactor::ConstantShrink { steps: p.clone() })),
        }),
        CallPattern::ArithmeticSubtractCall {
            steps: p,
            ring_param: r,
            ..
        } => Rc::new(LoweringTarget {
            primitive: IterationPrimitive::Repeat,
            bound: Rc::new(SizeBound::ArithmeticParam { param: r.clone() }),
            evidence: DescentEvidence::Strict,
            factor: Some(Rc::new(ShrinkFactor::ConstantShrink { steps: p.clone() })),
        }),
        CallPattern::ArithmeticDivideCall {
            divisor: d,
            ring_param: r,
            ..
        } => Rc::new(LoweringTarget {
            primitive: IterationPrimitive::Repeat,
            bound: Rc::new(SizeBound::ArithmeticParam { param: r.clone() }),
            evidence: DescentEvidence::Strict,
            factor: Some(Rc::new(ShrinkFactor::ProportionalShrink {
                divisor: d.clone(),
            })),
        }),
        CallPattern::ParserAdvanceCall { witness: w, .. } => Rc::new(LoweringTarget {
            primitive: IterationPrimitive::Fold,
            bound: Rc::new(SizeBound::ParserStreamSize { witness: w.clone() }),
            evidence: DescentEvidence::Strict,
            factor: None,
        }),
        CallPattern::WorklistDrainCall { element: e, .. } => Rc::new(LoweringTarget {
            primitive: IterationPrimitive::Fold,
            bound: Rc::new(SizeBound::WorklistDrainSize { element: e.clone() }),
            evidence: DescentEvidence::Strict,
            factor: None,
        }),
        CallPattern::FoldBodyCall {
            outer_collection: oc,
            ..
        } => Rc::new(LoweringTarget {
            primitive: IterationPrimitive::Fold,
            bound: Rc::new(SizeBound::CollectionSize { param: oc.clone() }),
            evidence: DescentEvidence::NonIncreasing,
            factor: None,
        }),
        CallPattern::SameArgumentCall => Rc::new(LoweringTarget {
            primitive: IterationPrimitive::Repeat,
            bound: Rc::new(SizeBound::Forever),
            evidence: DescentEvidence::NonIncreasing,
            factor: None,
        }),
    }
}

pub fn size_bound_param(bound: Rc<SizeBound>) -> Rc<FreeMonoid<Nat>> {
    match (*bound).clone() {
        SizeBound::TreeSize { param: p, .. } => Some(p.clone()),
        SizeBound::CollectionSize { param: p, .. } => Some(p.clone()),
        SizeBound::ParserStreamSize { witness: w, .. } => Some(w.clone()),
        SizeBound::WorklistDrainSize { element: e, .. } => Some(e.clone()),
        SizeBound::ArithmeticParam { param: p, .. } => Some(p.clone()),
        SizeBound::ExplicitCountZero => None,
        SizeBound::ExplicitCountPositive { steps: _, .. } => None,
        SizeBound::Forever => None,
    }
}

pub fn is_constant_bound(bound: Rc<SizeBound>) -> bool {
    match (*bound).clone() {
        SizeBound::ExplicitCountZero => true,
        SizeBound::ExplicitCountPositive { steps: _, .. } => true,
        SizeBound::Forever => true,
        _ => false,
    }
}

pub fn forever_iteration_bound() -> i64 {
    9223372036854775807
}

pub fn constant_bound_value(bound: Rc<SizeBound>) -> Option<i64> {
    match (*bound).clone() {
        SizeBound::ExplicitCountZero => Some(0),
        SizeBound::ExplicitCountPositive { steps: s, .. } => {
            Some(positive_descent_count(s.clone()))
        }
        SizeBound::Forever => Some(forever_iteration_bound()),
        _ => None,
    }
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum IterationDimension {
    TreeDescent,
    CollectionFold,
    ArithmeticRepeat,
}

pub fn algebra_profile_to_dimension(profile: AlgebraProfile) -> Option<IterationDimension> {
    match profile {
        AlgebraProfile::FreeMonoidCollectionProfile => Some(IterationDimension::CollectionFold),
        AlgebraProfile::FreeMonoidScalarProfile => Some(IterationDimension::CollectionFold),
        AlgebraProfile::BooleanAlgebraCollectionProfile => Some(IterationDimension::CollectionFold),
        AlgebraProfile::PartialFunctionProfile => Some(IterationDimension::CollectionFold),
        AlgebraProfile::OrderedRingProfile => Some(IterationDimension::ArithmeticRepeat),
        AlgebraProfile::ApproximateFieldProfile => Some(IterationDimension::ArithmeticRepeat),
        AlgebraProfile::BooleanAlgebraProfile => None,
    }
}

pub fn type_iteration_dimension(type_name: Rc<FreeMonoid<Nat>>) -> Option<IterationDimension> {
    if (crate::v2_std_text::host_string_text_to_rust_host(type_name.clone())
        == crate::v2_std_text::host_string_text_to_rust_host("Node".to_string()))
    {
        Some(IterationDimension::TreeDescent)
    } else {
        match v1_rt::map_get(&kernel_algebra_profile(), type_name.clone()) {
            Some(p) => algebra_profile_to_dimension(p.clone()),
            None => None,
        }
    }
}

pub struct Fold;
pub struct Descend;
pub struct Repeat;
pub struct TreeDescent;
pub struct CollectionFold;
pub struct ArithmeticRepeat;
