// Generated by v1 compiler -- do not edit.
// Source module: std.bit

use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

pub type Bit = crate::v2_std_logic::Bool;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Nibble {
    pub bits: Rc<Vec<Bit>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Byte {
    pub bits: Rc<Vec<Bit>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Word8 {
    pub bytes: Rc<Vec<Rc<Byte>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Word16 {
    pub bytes: Rc<Vec<Rc<Byte>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Word32 {
    pub bytes: Rc<Vec<Rc<Byte>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Word64 {
    pub bytes: Rc<Vec<Rc<Byte>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Word128 {
    pub bytes: Rc<Vec<Rc<Byte>>>,
}
