// Generated by v1 compiler -- do not edit.
// Source module: v1.compiler.stage0_crates

use self::Stage0CrateBoundaryEmitOutcome::*;
use self::Stage0CrateBoundaryEmitRefusalCause::*;
use self::Stage0CrateKind::*;
use self::Stage0CrateLibEmitOutcome::*;
use self::Stage0CratePlanOutcome::*;
use self::Stage0EmitShellReexportsOutcome::*;
use self::Stage0ModuleOwnerLookup::*;
use self::Stage0ModuleOwnerRefusalCause::*;
use self::Stage0PackageCrateDirLookup::*;
use self::Stage0PackageCrateDirRefusalCause::*;
use self::Stage0PartitionRowDepsOutcome::*;
use self::Stage0PartitionRowSpecOutcome::*;
use self::Stage0ReexportPathDepsOutcome::*;
use crate::extdeps_cargo::CargoDepSource::{LocalPathDep, RegistryDep};
pub use crate::extdeps_cargo::{CargoDepSource, CargoDependency, CargoFeature};
pub use crate::extdeps_cargo_version::render_cargo_package_header_prefix;
pub use crate::gunbc_stage0_crate_partition_generated::generated_partition_crate_rows;
use crate::gunbc_stage0_crate_partition_generated::GeneratedPartitionCrateKind::{
    GeneratedEmitCoreCrate, GeneratedFoundationCrate, GeneratedLayeredCoreCrate,
};
pub use crate::gunbc_stage0_crate_partition_generated::{
    GeneratedPartitionCrateKind, GeneratedPartitionCrateRow,
};
pub use crate::v1_compiler_emit_rust::{emit_cargo_dep, emit_non_empty_wrappers};
use crate::v1_rt;
use crate::v1_rt::Witness;
use crate::v1_rt::Witness::{Holds, Violates};
use crate::v1_rt::{VecCompat, VecJoin};
pub use crate::v1_std_core::TextFile;
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum Stage0CrateKind {
    FoundationCrate,
    LayeredCoreCrate,
    EmitCoreCrate,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Stage0CrateSpec {
    pub package_name: String,
    pub crate_dir: String,
    pub kind: Stage0CrateKind,
    pub header_doc: String,
    pub modules: Rc<Vec<String>>,
    pub reexport_packages: Rc<Vec<String>>,
    pub dependencies: Rc<Vec<Rc<CargoDependency>>>,
    pub features: Rc<Vec<Rc<CargoFeature>>>,
    pub carries_non_empty_wrappers: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Stage0CratePlan {
    pub crates: Rc<Vec<Rc<Stage0CrateSpec>>>,
}

pub fn stage0_crate_plan_note() -> String {
    thread_local! {
        static CACHED: String = {
            "Derived from v2.workflow.rust_crate_partition via gunbc.stage0_crate_partition_generated (HandExplicit ~8-crate interim partition). Dissolve-on: rust_crate_partition_interim_explicit when PolicyPartition lands.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn stage0_crate_plan_list_wrapper_dissolve_on() -> String {
    thread_local! {
        static CACHED: String = {
            "dissolve-on: stage0_crate_plan — deleted; receipt paths must call stage0_crate_plan_outcome (§5 empty-plan wrapper collapsed Stage0CratePlanRefused to crates:[]). workspace_members and regen_stage0 consume outcome surfaces only.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn stage0_crate_allow_block() -> String {
    Rc::new(vec![
        "#![allow(".to_string(),
        "    unused_imports,".to_string(),
        "    unused_variables,".to_string(),
        "    unused_mut,".to_string(),
        "    unused_parens,".to_string(),
        "    dead_code,".to_string(),
        "    non_shorthand_field_patterns,".to_string(),
        "    suspicious_double_ref_op,".to_string(),
        "    clippy::all".to_string(),
        ")]".to_string(),
        "#![deny(unreachable_patterns)]".to_string(),
        "#![recursion_limit = \"256\"]".to_string(),
    ])
    .join(&"\n".to_string())
}

pub fn unreachable_patterns_deny_note() -> String {
    thread_local! {
        static CACHED: String = {
            "unreachable_patterns is DENIED, not allowed (DESIGN §5 no-escape-hatches). The emitter lowers a nested variant pattern by hoisting the inner discriminant out of the arm into a `let .. = x.as_ref() else { unreachable!() }` prelude, because Rust cannot match through Rc<T> in a pattern. That is sound for ONE arm per outer constructor; two arms sharing an outer constructor collapse to identical Rust patterns, so the second is unreachable and the FIRST panics on any value it did not expect. Allowing unreachable_patterns suppressed the one signal that detects this -- the deficit frequency was zero by construction, so it never ranked for fixing (the exact §5 absorbing shape). Denying converts each occurrence into a located compile error. Proven by execution: reintroducing the nested-pattern form in std.effects.check_modifier_vs_derivation reds std_effects.rs with `unreachable pattern`; the corpus otherwise carried exactly ONE occurrence (a redundant wildcard in v1.compiler.emit.classify_expr, removed with this change). RESIDUE: this is validation, not construction -- the emitter still GENERATES the broken lowering and is merely caught downstream. The construction fix is to group arms sharing an outer constructor into a nested match (the form the emitter already lowers correctly); tracked as follow-on emitter work.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn stage0_foundation_header_doc() -> String {
    Rc::new(vec![
        "//! Generated by regen_stage0 -- do not edit.".to_string(),
        "//!".to_string(),
        "//! Foundation crate for the derived ~8-crate stage0 partition.".to_string(),
        "//!".to_string(),
        "//! Module bodies remain generated into `src/v1/stage0/src`. The root".to_string(),
        "//! `NonEmpty*` wrappers are mirrored here because generated modules address".to_string(),
        "//! them as `crate::NonEmptyVec` and `crate::NonEmptyBTreeSet`.".to_string(),
    ])
    .join(&"\n".to_string())
}

pub fn stage0_layered_core_header_doc() -> String {
    Rc::new(vec![
        "//! Generated by regen_stage0 -- do not edit.".to_string(),
        "//!".to_string(),
        "//! Layered core crate in the derived stage0 partition.".to_string(),
        "//!".to_string(),
        "//! Owns its module bodies via path includes and re-exports lower partition".to_string(),
        "//! crates so `crate::` references in generated modules keep resolving.".to_string(),
    ])
    .join(&"\n".to_string())
}

pub fn stage0_emit_core_header_doc() -> String {
    Rc::new(vec![
        "//! Generated by regen_stage0 -- do not edit.".to_string(),
        "//!".to_string(),
        "//! Emit-shell crate in the derived stage0 partition.".to_string(),
        "//!".to_string(),
        "//! Re-exports the emit surface from module-bearing partition crates and".to_string(),
        "//! hosts `v1_compiler_emit_core_support` without copying semantics.".to_string(),
    ])
    .join(&"\n".to_string())
}

pub fn stage0_package_name_to_rust_ident(package_name: String) -> String {
    v1_rt::replace(package_name.clone(), "-".to_string(), "_".to_string())
}

pub fn stage0_crate_dir_to_sibling_dep_path(crate_dir: String) -> String {
    v1_rt::replace(crate_dir.clone(), "src/v1/".to_string(), "../".to_string())
}

pub fn stage0_partition_row_is_module_bearing(row: Rc<GeneratedPartitionCrateRow>) -> bool {
    match row.kind.clone() {
        GeneratedPartitionCrateKind::GeneratedEmitCoreCrate => false,
        GeneratedPartitionCrateKind::GeneratedFoundationCrate => true,
        GeneratedPartitionCrateKind::GeneratedLayeredCoreCrate => true,
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0ModuleOwnerRefusalCause {
    Stage0ModuleOwnerMissing { module_basename: String },
}
impl Stage0ModuleOwnerRefusalCause {
    pub fn module_basename(&self) -> String {
        match self {
            Stage0ModuleOwnerRefusalCause::Stage0ModuleOwnerMissing {
                module_basename: __val,
                ..
            } => __val.clone(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0ModuleOwnerLookup {
    Stage0ModuleOwnerFound {
        package_name: String,
    },
    Stage0ModuleOwnerRefused {
        cause: Rc<Stage0ModuleOwnerRefusalCause>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0PackageCrateDirRefusalCause {
    Stage0PackageCrateDirMissing { package_name: String },
}
impl Stage0PackageCrateDirRefusalCause {
    pub fn package_name(&self) -> String {
        match self {
            Stage0PackageCrateDirRefusalCause::Stage0PackageCrateDirMissing {
                package_name: __val,
                ..
            } => __val.clone(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0PackageCrateDirLookup {
    Stage0PackageCrateDirFound {
        crate_dir: String,
    },
    Stage0PackageCrateDirRefused {
        cause: Rc<Stage0PackageCrateDirRefusalCause>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0ReexportPathDepsOutcome {
    Stage0ReexportPathDepsOk {
        deps: Rc<Vec<Rc<CargoDependency>>>,
    },
    Stage0ReexportPathDepsRefused {
        cause: Rc<Stage0PackageCrateDirRefusalCause>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0EmitShellReexportsOutcome {
    Stage0EmitShellReexportsOk {
        lines: Rc<Vec<String>>,
    },
    Stage0EmitShellReexportsRefused {
        cause: Rc<Stage0ModuleOwnerRefusalCause>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0PartitionRowDepsOutcome {
    Stage0PartitionRowDepsOk {
        deps: Rc<Vec<Rc<CargoDependency>>>,
    },
    Stage0PartitionRowDepsRefused {
        cause: Rc<Stage0PackageCrateDirRefusalCause>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0PartitionRowSpecOutcome {
    Stage0PartitionRowSpecOk {
        spec: Rc<Stage0CrateSpec>,
    },
    Stage0PartitionRowSpecRefused {
        cause: Rc<Stage0PackageCrateDirRefusalCause>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0CratePlanOutcome {
    Stage0CratePlanOk {
        plan: Rc<Stage0CratePlan>,
    },
    Stage0CratePlanRefused {
        cause: Rc<Stage0PackageCrateDirRefusalCause>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0CrateLibEmitOutcome {
    Stage0CrateLibEmitOk {
        file: Rc<TextFile>,
    },
    Stage0CrateLibEmitRefused {
        cause: Rc<Stage0ModuleOwnerRefusalCause>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0CrateBoundaryEmitRefusalCause {
    Stage0CrateBoundaryEmitModuleOwnerMissing { module_basename: String },
    Stage0CrateBoundaryEmitPackageCrateDirMissing { package_name: String },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum Stage0CrateBoundaryEmitOutcome {
    Stage0CrateBoundaryEmitOk {
        files: Rc<Vec<Rc<TextFile>>>,
    },
    Stage0CrateBoundaryEmitRefused {
        cause: Rc<Stage0CrateBoundaryEmitRefusalCause>,
    },
}

pub fn stage0_lookup_module_owner_package_name(
    module_basename: String,
) -> Rc<Stage0ModuleOwnerLookup> {
    {
        let matches = Rc::new({
            let mut __result = Vec::new();
            for row in generated_partition_crate_rows().iter().cloned() {
                if (stage0_partition_row_is_module_bearing(row.clone()) && {
                    let mut __found = false;
                    for m in row.modules.clone().iter().cloned() {
                        if (m.clone() == module_basename.clone()) {
                            __found = true;
                            break;
                        }
                    }
                    __found
                }) {
                    __result.push(row);
                }
            }
            __result
        });
        let package_name = Rc::new({
            let mut __result = Vec::new();
            for row in matches.clone().iter().cloned() {
                __result.push(row.package_name.clone());
            }
            __result
        })
        .iter()
        .cloned()
        .fold("".to_string(), |acc: String, pkg: String| {
            if (acc.clone() == "".to_string()) {
                pkg.clone()
            } else {
                acc.clone()
            }
        });
        if (package_name.clone() == "".to_string()) {
            Rc::new(Stage0ModuleOwnerLookup::Stage0ModuleOwnerRefused {
                cause: Rc::new(Stage0ModuleOwnerRefusalCause::Stage0ModuleOwnerMissing {
                    module_basename: module_basename.clone(),
                }),
            })
        } else {
            Rc::new(Stage0ModuleOwnerLookup::Stage0ModuleOwnerFound {
                package_name: package_name.clone(),
            })
        }
    }
}

pub fn stage0_lookup_package_crate_dir(package_name: String) -> Rc<Stage0PackageCrateDirLookup> {
    {
        let matches = Rc::new({
            let mut __result = Vec::new();
            for row in generated_partition_crate_rows().iter().cloned() {
                if (row.package_name.clone() == package_name.clone()) {
                    __result.push(row);
                }
            }
            __result
        });
        let crate_dir =
            matches
                .clone()
                .iter()
                .cloned()
                .fold("".to_string(), |acc: String, row: _| {
                    if (acc.clone() == "".to_string()) {
                        row.crate_dir.clone()
                    } else {
                        acc.clone()
                    }
                });
        if (crate_dir.clone() == "".to_string()) {
            Rc::new(Stage0PackageCrateDirLookup::Stage0PackageCrateDirRefused {
                cause: Rc::new(
                    Stage0PackageCrateDirRefusalCause::Stage0PackageCrateDirMissing {
                        package_name: package_name.clone(),
                    },
                ),
            })
        } else {
            Rc::new(Stage0PackageCrateDirLookup::Stage0PackageCrateDirFound {
                crate_dir: crate_dir.clone(),
            })
        }
    }
}

pub fn stage0_map_package_dir_refusal_to_boundary(
    cause: Rc<Stage0PackageCrateDirRefusalCause>,
) -> Rc<Stage0CrateBoundaryEmitRefusalCause> {
    match (*cause.clone()).clone() {
        Stage0PackageCrateDirRefusalCause::Stage0PackageCrateDirMissing {
            package_name: package_name,
            ..
        } => Rc::new(
            Stage0CrateBoundaryEmitRefusalCause::Stage0CrateBoundaryEmitPackageCrateDirMissing {
                package_name: package_name.clone(),
            },
        ),
    }
}

pub fn stage0_map_module_owner_refusal_to_boundary(
    cause: Rc<Stage0ModuleOwnerRefusalCause>,
) -> Rc<Stage0CrateBoundaryEmitRefusalCause> {
    match (*cause.clone()).clone() {
        Stage0ModuleOwnerRefusalCause::Stage0ModuleOwnerMissing {
            module_basename: module_basename,
            ..
        } => Rc::new(
            Stage0CrateBoundaryEmitRefusalCause::Stage0CrateBoundaryEmitModuleOwnerMissing {
                module_basename: module_basename.clone(),
            },
        ),
    }
}

pub fn stage0_crate_boundary_emit_refusal_message(
    cause: Rc<Stage0CrateBoundaryEmitRefusalCause>,
) -> String {
    match (*cause.clone()).clone() {
        Stage0CrateBoundaryEmitRefusalCause::Stage0CrateBoundaryEmitModuleOwnerMissing {
            module_basename: module_basename,
            ..
        } => v1_rt::concat(
            "stage0 partition emit refused: missing module owner for ".to_string(),
            module_basename.clone(),
        ),
        Stage0CrateBoundaryEmitRefusalCause::Stage0CrateBoundaryEmitPackageCrateDirMissing {
            package_name: package_name,
            ..
        } => v1_rt::concat(
            "stage0 partition emit refused: missing package crate_dir for ".to_string(),
            package_name.clone(),
        ),
    }
}

pub fn stage0_foundation_runtime_dependencies() -> Rc<Vec<Rc<CargoDependency>>> {
    Rc::new(vec![
        Rc::new(CargoDependency {
            name: "stacker".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "0.1".to_string(),
                features: Rc::new(vec![]),
            }),
        }),
        Rc::new(CargoDependency {
            name: "im".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "15.1".to_string(),
                features: Rc::new(vec!["serde".to_string()]),
            }),
        }),
        Rc::new(CargoDependency {
            name: "serde".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "1".to_string(),
                features: Rc::new(vec!["derive".to_string(), "rc".to_string()]),
            }),
        }),
        Rc::new(CargoDependency {
            name: "serde_json".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "1".to_string(),
                features: Rc::new(vec![]),
            }),
        }),
        Rc::new(CargoDependency {
            name: "unicode-ident".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "1".to_string(),
                features: Rc::new(vec![]),
            }),
        }),
        Rc::new(CargoDependency {
            name: "unicode-properties".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "0.1".to_string(),
                features: Rc::new(vec!["emoji".to_string()]),
            }),
        }),
    ])
}

pub fn stage0_emit_shell_registry_dependencies() -> Rc<Vec<Rc<CargoDependency>>> {
    Rc::new(vec![
        Rc::new(CargoDependency {
            name: "stacker".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "0.1".to_string(),
                features: Rc::new(vec![]),
            }),
        }),
        Rc::new(CargoDependency {
            name: "im".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "15.1".to_string(),
                features: Rc::new(vec!["serde".to_string()]),
            }),
        }),
        Rc::new(CargoDependency {
            name: "serde".to_string(),
            source: Rc::new(CargoDepSource::RegistryDep {
                version: "1".to_string(),
                features: Rc::new(vec!["derive".to_string(), "rc".to_string()]),
            }),
        }),
    ])
}

pub fn stage0_reexport_path_dependencies_outcome(
    reexport_packages: Rc<Vec<String>>,
) -> Rc<Stage0ReexportPathDepsOutcome> {
    reexport_packages.clone().iter().cloned().fold(
        Rc::new(Stage0ReexportPathDepsOutcome::Stage0ReexportPathDepsOk {
            deps: Rc::new(vec![]),
        }),
        |acc: Rc<Stage0ReexportPathDepsOutcome>, pkg: String| match (*acc).clone() {
            Stage0ReexportPathDepsOutcome::Stage0ReexportPathDepsRefused {
                cause: cause, ..
            } => Rc::new(
                Stage0ReexportPathDepsOutcome::Stage0ReexportPathDepsRefused {
                    cause: cause.clone(),
                },
            ),
            Stage0ReexportPathDepsOutcome::Stage0ReexportPathDepsOk { deps: deps, .. } => {
                match (*stage0_lookup_package_crate_dir(pkg.clone())).clone() {
                    Stage0PackageCrateDirLookup::Stage0PackageCrateDirFound {
                        crate_dir: crate_dir,
                        ..
                    } => Rc::new(Stage0ReexportPathDepsOutcome::Stage0ReexportPathDepsOk {
                        deps: v1_rt::concat(
                            deps.clone(),
                            Rc::new(vec![Rc::new(CargoDependency {
                                name: pkg.clone(),
                                source: Rc::new(CargoDepSource::LocalPathDep {
                                    path: stage0_crate_dir_to_sibling_dep_path(crate_dir.clone()),
                                }),
                            })]),
                        ),
                    }),
                    Stage0PackageCrateDirLookup::Stage0PackageCrateDirRefused {
                        cause: cause,
                        ..
                    } => Rc::new(
                        Stage0ReexportPathDepsOutcome::Stage0ReexportPathDepsRefused {
                            cause: cause.clone(),
                        },
                    ),
                }
            }
        },
    )
}

pub fn stage0_emit_shell_path_dependencies() -> Rc<Vec<Rc<CargoDependency>>> {
    Rc::new({
        let mut __result = Vec::new();
        for row in Rc::new({
            let mut __result = Vec::new();
            for row in generated_partition_crate_rows().iter().cloned() {
                if stage0_partition_row_is_module_bearing(row.clone()) {
                    __result.push(row);
                }
            }
            __result
        })
        .iter()
        .cloned()
        {
            __result.push(Rc::new(CargoDependency {
                name: row.package_name.clone(),
                source: Rc::new(CargoDepSource::LocalPathDep {
                    path: stage0_crate_dir_to_sibling_dep_path(row.crate_dir.clone()),
                }),
            }));
        }
        __result
    })
}

pub fn stage0_partition_row_kind(row: Rc<GeneratedPartitionCrateRow>) -> Stage0CrateKind {
    match row.kind.clone() {
        GeneratedPartitionCrateKind::GeneratedFoundationCrate => Stage0CrateKind::FoundationCrate,
        GeneratedPartitionCrateKind::GeneratedLayeredCoreCrate => Stage0CrateKind::LayeredCoreCrate,
        GeneratedPartitionCrateKind::GeneratedEmitCoreCrate => Stage0CrateKind::EmitCoreCrate,
    }
}

pub fn stage0_partition_row_header_doc(row: Rc<GeneratedPartitionCrateRow>) -> String {
    match row.kind.clone() {
        GeneratedPartitionCrateKind::GeneratedFoundationCrate => stage0_foundation_header_doc(),
        GeneratedPartitionCrateKind::GeneratedLayeredCoreCrate => stage0_layered_core_header_doc(),
        GeneratedPartitionCrateKind::GeneratedEmitCoreCrate => stage0_emit_core_header_doc(),
    }
}

pub fn stage0_partition_row_dependencies_outcome(
    row: Rc<GeneratedPartitionCrateRow>,
) -> Rc<Stage0PartitionRowDepsOutcome> {
    match row.kind.clone() {
        GeneratedPartitionCrateKind::GeneratedFoundationCrate => {
            Rc::new(Stage0PartitionRowDepsOutcome::Stage0PartitionRowDepsOk {
                deps: stage0_foundation_runtime_dependencies(),
            })
        }
        GeneratedPartitionCrateKind::GeneratedLayeredCoreCrate => {
            match (*stage0_reexport_path_dependencies_outcome(row.reexport_packages.clone()))
                .clone()
            {
                Stage0ReexportPathDepsOutcome::Stage0ReexportPathDepsOk {
                    deps: reexport_deps,
                    ..
                } => Rc::new(Stage0PartitionRowDepsOutcome::Stage0PartitionRowDepsOk {
                    deps: v1_rt::concat(
                        stage0_foundation_runtime_dependencies(),
                        reexport_deps.clone(),
                    ),
                }),
                Stage0ReexportPathDepsOutcome::Stage0ReexportPathDepsRefused {
                    cause: cause,
                    ..
                } => Rc::new(
                    Stage0PartitionRowDepsOutcome::Stage0PartitionRowDepsRefused {
                        cause: cause.clone(),
                    },
                ),
            }
        }
        GeneratedPartitionCrateKind::GeneratedEmitCoreCrate => {
            Rc::new(Stage0PartitionRowDepsOutcome::Stage0PartitionRowDepsOk {
                deps: v1_rt::concat(
                    stage0_foundation_runtime_dependencies(),
                    stage0_emit_shell_path_dependencies(),
                ),
            })
        }
    }
}

pub fn stage0_partition_row_features(
    row: Rc<GeneratedPartitionCrateRow>,
) -> Rc<Vec<Rc<CargoFeature>>> {
    match row.kind.clone() {
        GeneratedPartitionCrateKind::GeneratedFoundationCrate => {
            Rc::new(vec![Rc::new(CargoFeature {
                name: "text_lookup_work_counter".to_string(),
                dependencies: Rc::new(vec![]),
            })])
        }
        GeneratedPartitionCrateKind::GeneratedLayeredCoreCrate => Rc::new(vec![]),
        GeneratedPartitionCrateKind::GeneratedEmitCoreCrate => Rc::new(vec![]),
    }
}

pub fn stage0_partition_row_to_spec_outcome(
    row: Rc<GeneratedPartitionCrateRow>,
) -> Rc<Stage0PartitionRowSpecOutcome> {
    match (*stage0_partition_row_dependencies_outcome(row.clone())).clone() {
        Stage0PartitionRowDepsOutcome::Stage0PartitionRowDepsRefused { cause: cause, .. } => {
            Rc::new(
                Stage0PartitionRowSpecOutcome::Stage0PartitionRowSpecRefused {
                    cause: cause.clone(),
                },
            )
        }
        Stage0PartitionRowDepsOutcome::Stage0PartitionRowDepsOk { deps: deps, .. } => {
            Rc::new(Stage0PartitionRowSpecOutcome::Stage0PartitionRowSpecOk {
                spec: Rc::new(Stage0CrateSpec {
                    package_name: row.package_name.clone(),
                    crate_dir: row.crate_dir.clone(),
                    kind: stage0_partition_row_kind(row.clone()),
                    header_doc: stage0_partition_row_header_doc(row.clone()),
                    modules: row.modules.clone(),
                    reexport_packages: row.reexport_packages.clone(),
                    dependencies: deps.clone(),
                    features: stage0_partition_row_features(row.clone()),
                    carries_non_empty_wrappers: row.carries_non_empty_wrappers.clone(),
                }),
            })
        }
    }
}

pub fn render_stage0_crate_dep(dep: Rc<CargoDependency>) -> String {
    match (*dep.source.clone()).clone() {
        CargoDepSource::RegistryDep {
            version, features, ..
        } => emit_cargo_dep(dep.name.clone(), version.clone(), features.clone()),
        CargoDepSource::LocalPathDep { path: path, .. } => v1_rt::concat(
            v1_rt::concat(
                v1_rt::concat(dep.name.clone(), " = { path = \"".to_string()),
                path.clone(),
            ),
            "\" }\n".to_string(),
        ),
    }
}

pub fn render_stage0_crate_feature(feature: Rc<CargoFeature>) -> String {
    if ((feature.dependencies.clone().len() as i64) == 0) {
        v1_rt::concat(feature.name.clone(), " = []\n".to_string())
    } else {
        {
            let dep_names = Rc::new({
                let mut __result = Vec::new();
                for d in feature.dependencies.clone().iter().cloned() {
                    __result.push(v1_rt::concat(
                        v1_rt::concat("\"".to_string(), d.clone()),
                        "\"".to_string(),
                    ));
                }
                __result
            })
            .join(&", ".to_string());
            v1_rt::concat(
                v1_rt::concat(
                    v1_rt::concat(feature.name.clone(), " = [".to_string()),
                    dep_names.clone(),
                ),
                "]\n".to_string(),
            )
        }
    }
}

pub fn render_stage0_crate_features_section(features: Rc<Vec<Rc<CargoFeature>>>) -> String {
    if ((features.clone().len() as i64) == 0) {
        "".to_string()
    } else {
        v1_rt::concat(
            v1_rt::concat("\n[features]\n".to_string(), "default = []\n".to_string()),
            Rc::new(
                features
                    .clone()
                    .iter()
                    .cloned()
                    .map(render_stage0_crate_feature)
                    .collect::<Vec<_>>(),
            )
            .join(&"".to_string()),
        )
    }
}

pub fn emit_stage0_crate_manifest(spec: Rc<Stage0CrateSpec>) -> Rc<TextFile> {
    {
        let deps = Rc::new(
            spec.dependencies
                .clone()
                .iter()
                .cloned()
                .map(render_stage0_crate_dep)
                .collect::<Vec<_>>(),
        )
        .join(&"".to_string());
        let content = v1_rt::concat(
            v1_rt::concat(
                v1_rt::concat(
                    v1_rt::concat(
                        render_cargo_package_header_prefix(spec.package_name.clone()),
                        "\nedition = \"2021\"".to_string(),
                    ),
                    render_stage0_crate_features_section(spec.features.clone()),
                ),
                "\n\n[dependencies]\n".to_string(),
            ),
            deps.clone(),
        );
        Rc::new(TextFile {
            path: v1_rt::concat(spec.crate_dir.clone(), "/Cargo.toml".to_string()),
            content: content.clone(),
        })
    }
}

pub fn stage0_crate_mod_include(module_basename: String) -> String {
    v1_rt::concat(
        v1_rt::concat(
            v1_rt::concat(
                v1_rt::concat(
                    v1_rt::concat(
                        v1_rt::concat(
                            "#[rustfmt::skip]\n".to_string(),
                            "#[path = \"../../stage0/src/".to_string(),
                        ),
                        module_basename.clone(),
                    ),
                    ".rs\"]\n".to_string(),
                ),
                "pub mod ".to_string(),
            ),
            module_basename.clone(),
        ),
        ";".to_string(),
    )
}

pub fn render_stage0_foundation_lib(spec: Rc<Stage0CrateSpec>) -> String {
    {
        let includes = Rc::new({
            let mut __result = Vec::new();
            for m in spec.modules.clone().iter().cloned() {
                __result.push(stage0_crate_mod_include(m.clone()));
            }
            __result
        })
        .join(&"\n".to_string());
        let head = v1_rt::concat(
            v1_rt::concat(
                v1_rt::concat(
                    v1_rt::concat(spec.header_doc.clone(), "\n\n".to_string()),
                    stage0_crate_allow_block(),
                ),
                "\n\n".to_string(),
            ),
            includes.clone(),
        );
        if spec.carries_non_empty_wrappers.clone() {
            v1_rt::concat(
                v1_rt::concat(
                    v1_rt::concat(head.clone(), "\n\n".to_string()),
                    emit_non_empty_wrappers(),
                ),
                "\n".to_string(),
            )
        } else {
            v1_rt::concat(head.clone(), "\n".to_string())
        }
    }
}

pub fn render_stage0_layered_core_lib(spec: Rc<Stage0CrateSpec>) -> String {
    {
        let sorted_reexports = Rc::new({
            let mut __sorted: Vec<_> = spec.reexport_packages.clone().iter().cloned().collect();
            __sorted.sort_by(|a: &String, b: &String| {
                let __ka =
                    (|pkg: String| stage0_package_name_to_rust_ident(pkg.clone()))(a.clone());
                let __kb =
                    (|pkg: String| stage0_package_name_to_rust_ident(pkg.clone()))(b.clone());
                __ka.partial_cmp(&__kb).unwrap_or(std::cmp::Ordering::Equal)
            });
            __sorted
        });
        let reexports = Rc::new({
            let mut __result = Vec::new();
            for pkg in sorted_reexports.clone().iter().cloned() {
                __result.push(v1_rt::concat(
                    v1_rt::concat(
                        "pub use ".to_string(),
                        stage0_package_name_to_rust_ident(pkg.clone()),
                    ),
                    "::*;".to_string(),
                ));
            }
            __result
        })
        .join(&"\n".to_string());
        let includes = Rc::new({
            let mut __result = Vec::new();
            for m in spec.modules.clone().iter().cloned() {
                __result.push(stage0_crate_mod_include(m.clone()));
            }
            __result
        })
        .join(&"\n".to_string());
        v1_rt::concat(
            v1_rt::concat(
                v1_rt::concat(
                    v1_rt::concat(
                        v1_rt::concat(
                            v1_rt::concat(
                                v1_rt::concat(spec.header_doc.clone(), "\n\n".to_string()),
                                stage0_crate_allow_block(),
                            ),
                            "\n\n".to_string(),
                        ),
                        reexports.clone(),
                    ),
                    "\n\n".to_string(),
                ),
                includes.clone(),
            ),
            "\n".to_string(),
        )
    }
}

pub fn stage0_emit_shell_module_reexports_outcome(
    modules: Rc<Vec<String>>,
) -> Rc<Stage0EmitShellReexportsOutcome> {
    modules.clone().iter().cloned().fold(
        Rc::new(
            Stage0EmitShellReexportsOutcome::Stage0EmitShellReexportsOk {
                lines: Rc::new(vec![]),
            },
        ),
        |acc: Rc<Stage0EmitShellReexportsOutcome>, module_basename: String| match (*acc).clone() {
            Stage0EmitShellReexportsOutcome::Stage0EmitShellReexportsRefused {
                cause: cause,
                ..
            } => Rc::new(
                Stage0EmitShellReexportsOutcome::Stage0EmitShellReexportsRefused {
                    cause: cause.clone(),
                },
            ),
            Stage0EmitShellReexportsOutcome::Stage0EmitShellReexportsOk {
                lines: lines, ..
            } => {
                match (*stage0_lookup_module_owner_package_name(module_basename.clone())).clone() {
                    Stage0ModuleOwnerLookup::Stage0ModuleOwnerFound {
                        package_name: owner,
                        ..
                    } => Rc::new(
                        Stage0EmitShellReexportsOutcome::Stage0EmitShellReexportsOk {
                            lines: v1_rt::concat(
                                lines.clone(),
                                Rc::new(vec![v1_rt::concat(
                                    v1_rt::concat(
                                        v1_rt::concat(
                                            v1_rt::concat(
                                                v1_rt::concat(
                                                    v1_rt::concat(
                                                        "pub mod ".to_string(),
                                                        module_basename.clone(),
                                                    ),
                                                    " {\n    pub use ".to_string(),
                                                ),
                                                stage0_package_name_to_rust_ident(owner.clone()),
                                            ),
                                            "::".to_string(),
                                        ),
                                        module_basename.clone(),
                                    ),
                                    "::*;\n}".to_string(),
                                )]),
                            ),
                        },
                    ),
                    Stage0ModuleOwnerLookup::Stage0ModuleOwnerRefused { cause: cause, .. } => {
                        Rc::new(
                            Stage0EmitShellReexportsOutcome::Stage0EmitShellReexportsRefused {
                                cause: cause.clone(),
                            },
                        )
                    }
                }
            }
        },
    )
}

pub fn render_stage0_emit_core_lib_outcome(
    spec: Rc<Stage0CrateSpec>,
) -> Rc<Stage0CrateLibEmitOutcome> {
    match (*stage0_emit_shell_module_reexports_outcome(spec.modules.clone())).clone() {
    Stage0EmitShellReexportsOutcome::Stage0EmitShellReexportsRefused { cause: cause, .. } => Rc::new(Stage0CrateLibEmitOutcome::Stage0CrateLibEmitRefused {
    cause: cause.clone(),
}),
    Stage0EmitShellReexportsOutcome::Stage0EmitShellReexportsOk { lines: lines, .. } => Rc::new(Stage0CrateLibEmitOutcome::Stage0CrateLibEmitOk {
    file: Rc::new(TextFile {
    path: v1_rt::concat(spec.crate_dir.clone(), "/src/lib.rs".to_string()),
    content: v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(v1_rt::concat(spec.header_doc.clone(), "\n\n".to_string()), stage0_crate_allow_block()), "\n\n".to_string()), "pub use v1_stage0_runtime::{NonEmptyBTreeSet, NonEmptyVec};".to_string()), "\n\n".to_string()), lines.clone().join(&"\n\n".to_string())), "\n\n".to_string()), "#[rustfmt::skip]\n#[path = \"../../stage0/src/v1_compiler_emit_core_support.rs\"]\npub mod v1_compiler_emit_core_support;".to_string()), "\n\n".to_string()), "pub use v1_compiler_emit_core_support::*;".to_string()), "\n".to_string()),
}),
}),
}
}

pub fn stage0_partition_lookups_valid() -> bool {
    match (*stage0_crate_boundary_emit_outcome()).clone() {
        Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitOk { files: _, .. } => true,
        Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitRefused { cause: _, .. } => false,
    }
}

pub fn emit_stage0_crate_lib_outcome(spec: Rc<Stage0CrateSpec>) -> Rc<Stage0CrateLibEmitOutcome> {
    match spec.kind.clone() {
        Stage0CrateKind::FoundationCrate => {
            Rc::new(Stage0CrateLibEmitOutcome::Stage0CrateLibEmitOk {
                file: Rc::new(TextFile {
                    path: v1_rt::concat(spec.crate_dir.clone(), "/src/lib.rs".to_string()),
                    content: render_stage0_foundation_lib(spec.clone()),
                }),
            })
        }
        Stage0CrateKind::LayeredCoreCrate => {
            Rc::new(Stage0CrateLibEmitOutcome::Stage0CrateLibEmitOk {
                file: Rc::new(TextFile {
                    path: v1_rt::concat(spec.crate_dir.clone(), "/src/lib.rs".to_string()),
                    content: render_stage0_layered_core_lib(spec.clone()),
                }),
            })
        }
        Stage0CrateKind::EmitCoreCrate => render_stage0_emit_core_lib_outcome(spec.clone()),
    }
}

pub fn stage0_crate_plan_outcome() -> Rc<Stage0CratePlanOutcome> {
    generated_partition_crate_rows().iter().cloned().fold(
        Rc::new(Stage0CratePlanOutcome::Stage0CratePlanOk {
            plan: Rc::new(Stage0CratePlan {
                crates: Rc::new(vec![]),
            }),
        }),
        |acc: Rc<Stage0CratePlanOutcome>, row: _| match (*acc).clone() {
            Stage0CratePlanOutcome::Stage0CratePlanRefused { cause: cause, .. } => {
                Rc::new(Stage0CratePlanOutcome::Stage0CratePlanRefused {
                    cause: cause.clone(),
                })
            }
            Stage0CratePlanOutcome::Stage0CratePlanOk { plan: plan, .. } => {
                match (*stage0_partition_row_to_spec_outcome(row.clone())).clone() {
                    Stage0PartitionRowSpecOutcome::Stage0PartitionRowSpecRefused {
                        cause: cause,
                        ..
                    } => Rc::new(Stage0CratePlanOutcome::Stage0CratePlanRefused {
                        cause: cause.clone(),
                    }),
                    Stage0PartitionRowSpecOutcome::Stage0PartitionRowSpecOk {
                        spec: spec, ..
                    } => Rc::new(Stage0CratePlanOutcome::Stage0CratePlanOk {
                        plan: Rc::new(Stage0CratePlan {
                            crates: v1_rt::concat(plan.crates.clone(), Rc::new(vec![spec.clone()])),
                        }),
                    }),
                }
            }
        },
    )
}

pub fn emit_stage0_crate_boundary_files_outcome(
    plan: Rc<Stage0CratePlan>,
) -> Rc<Stage0CrateBoundaryEmitOutcome> {
    plan.crates.clone().iter().cloned().fold(
        Rc::new(Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitOk {
            files: Rc::new(vec![]),
        }),
        |acc: Rc<Stage0CrateBoundaryEmitOutcome>, spec: Rc<Stage0CrateSpec>| match (*acc).clone() {
            Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitRefused {
                cause: cause, ..
            } => Rc::new(
                Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitRefused {
                    cause: cause.clone(),
                },
            ),
            Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitOk { files: files, .. } => {
                match (*emit_stage0_crate_lib_outcome(spec.clone())).clone() {
                    Stage0CrateLibEmitOutcome::Stage0CrateLibEmitRefused {
                        cause: cause, ..
                    } => Rc::new(
                        Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitRefused {
                            cause: stage0_map_module_owner_refusal_to_boundary(cause.clone()),
                        },
                    ),
                    Stage0CrateLibEmitOutcome::Stage0CrateLibEmitOk { file: lib_file, .. } => {
                        Rc::new(Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitOk {
                            files: v1_rt::concat(
                                files.clone(),
                                Rc::new(vec![
                                    emit_stage0_crate_manifest(spec.clone()),
                                    lib_file.clone(),
                                ]),
                            ),
                        })
                    }
                }
            }
        },
    )
}

pub fn stage0_crate_boundary_emit_outcome() -> Rc<Stage0CrateBoundaryEmitOutcome> {
    match (*stage0_crate_plan_outcome()).clone() {
        Stage0CratePlanOutcome::Stage0CratePlanRefused { cause: cause, .. } => Rc::new(
            Stage0CrateBoundaryEmitOutcome::Stage0CrateBoundaryEmitRefused {
                cause: stage0_map_package_dir_refusal_to_boundary(cause.clone()),
            },
        ),
        Stage0CratePlanOutcome::Stage0CratePlanOk { plan: plan, .. } => {
            emit_stage0_crate_boundary_files_outcome(plan.clone())
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct FoundationCrate;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct LayeredCoreCrate;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct EmitCoreCrate;
