// Generated by v1 compiler -- do not edit.
// Source module: v1.compiler.infer_sigs

pub use crate::std_induction::SubValueRelation;
use crate::std_induction::SubValueRelation::*;
pub use crate::v1_compiler_infer_types::emit_map_has;
use crate::v1_rt;
use crate::v1_rt::Witness;
use crate::v1_rt::Witness::{Holds, Violates};
use crate::v1_rt::{VecCompat, VecJoin};
use crate::v1_std_core::CompilerDiagnostic::MissingAnnotation;
use crate::v1_std_core::ExprData::ExprCall;
pub use crate::v1_std_core::{authored_name_at, expr_call_func_at, make_error_node, no_span};
pub use crate::v1_std_core::{
    CompilerDiagnostic, DeclaredFuncSig, ErrorNode, ExprData, NewlineIndex, Node,
};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::sync::Arc;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolvedFuncSig {
    pub name: String,
    pub params: Arc<Vec<Arc<Node>>>,
    pub inferred: Arc<Node>,
    pub is_async: bool,
    pub output_provenance: Arc<Vec<Arc<HashMap<String, Arc<SubValueRelation>>>>>,
    pub variant_provenance:
        Arc<HashMap<String, Arc<HashMap<String, Arc<HashMap<String, Arc<SubValueRelation>>>>>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolvedFuncEnv {
    pub name: String,
    pub local: Arc<HashMap<String, Arc<ResolvedFuncSig>>>,
    pub parents: Arc<Vec<Arc<ResolvedFuncEnv>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveFuncSigsResult {
    pub func_env: Arc<ResolvedFuncEnv>,
    pub diagnostics: Arc<Vec<Arc<ErrorNode>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SigsAccum {
    pub signatures: Arc<HashMap<String, Arc<ResolvedFuncSig>>>,
    pub diagnostics: Arc<Vec<Arc<ErrorNode>>>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CallEdge {
    pub caller: String,
    pub callee: String,
}

pub fn sigs_env_flat_parents_note() -> String {
    thread_local! {
        static CACHED: String = {
            "Cost shape (§6 bare-minimum cost): ResolvedFuncEnv.parents is the module's transitive import closure held FLAT — precedence-ordered (first = highest precedence: the last direct import's closure first, then earlier imports'; own local always wins before any parent), deduped by env name keeping the first occurrence. The prior shape nested each parent env recursively and lookup walked the shared import DAG as a TREE with no visited state, so a shared ancestor was probed once per PATH, not per module (measured: identical 541 signature requests cost 53.3M env probes, and 902.8M after one merge widened the host-effect closure by 54 modules — 16.95x from visibility alone), with a quadratic parents-prefix copy per recursion step. Flattening at the two assembly points (resolve_func_sigs at typecheck time; rewire_func_env_parent_links post-fold) makes lookup one ordered scan over closure members' own local maps: probes are bounded by distinct closure modules, never paths. The name dedup is load-bearing: without it flat lists compose additively along every import path and the list length re-becomes the path count. Shadowing is preserved exactly — the old deep-first, last-import-first walk linearizes to closure-of-last-import before closure-of-earlier-imports, and a member's own local precedes its parents' contributions.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FlattenAccum {
    pub seen: Arc<HashMap<String, bool>>,
    pub out: Arc<Vec<Arc<ResolvedFuncEnv>>>,
}

pub fn flatten_parent_envs(
    direct_parents: Arc<Vec<Arc<ResolvedFuncEnv>>>,
) -> Arc<Vec<Arc<ResolvedFuncEnv>>> {
    {
        let ordered = Arc::new({
            let mut __result = Vec::new();
            for p in v1_rt::reverse(direct_parents.clone()).iter().cloned() {
                __result.extend(
                    (*v1_rt::concat(Arc::new(vec![p.clone()]), p.parents.clone()))
                        .iter()
                        .cloned(),
                );
            }
            __result
        });
        let dedup = ordered.clone().iter().cloned().fold(
            Arc::new(FlattenAccum {
                seen: v1_rt::rc_empty_map::<String, bool>(),
                out: Arc::new(vec![]),
            }),
            |acc: Arc<FlattenAccum>, p: Arc<ResolvedFuncEnv>| {
                if emit_map_has(acc.seen.clone(), p.name.clone()) {
                    acc.clone()
                } else {
                    Arc::new(FlattenAccum {
                        seen: v1_rt::rc_map_insert(acc.seen.clone(), p.name.clone(), true),
                        out: v1_rt::rc_list_push(acc.out.clone(), p.clone()),
                    })
                }
            },
        );
        dedup.out.clone()
    }
}

pub fn lookup_resolved_sig(
    env: Arc<ResolvedFuncEnv>,
    name: String,
) -> Option<Arc<ResolvedFuncSig>> {
    match v1_rt::map_get(&env.local.clone(), name.clone()) {
        Some(sig) => Some(sig.clone()),
        None => env.parents.clone().iter().cloned().fold(
            none_resolved_sig(),
            |acc: Option<Arc<ResolvedFuncSig>>, p: Arc<ResolvedFuncEnv>| match acc.clone() {
                Some(sig) => Some(sig.clone()),
                None => v1_rt::map_get(&p.local.clone(), name.clone()),
            },
        ),
    }
}

pub fn none_resolved_sig() -> Option<Arc<ResolvedFuncSig>> {
    None
}

pub fn collect_func_call_edges(
    items: Arc<Vec<Arc<Node>>>,
    local_func_set: Arc<HashMap<String, bool>>,
    source_indices: Arc<HashMap<String, Arc<NewlineIndex>>>,
) -> Arc<Vec<Arc<CallEdge>>> {
    Arc::new({
        let mut __result = Vec::new();
        for item in items.clone().iter().cloned() {
            __result.extend(
                (*if (((item.params.clone().len() as i64) > 0) && (item.body.clone() != None)) {
                    collect_calls_in_expr(
                        authored_name_at(source_indices.clone(), item.clone()),
                        item.body.clone().clone().unwrap(),
                        local_func_set.clone(),
                        source_indices.clone(),
                    )
                } else {
                    Arc::new(vec![])
                })
                .iter()
                .cloned(),
            );
        }
        __result
    })
}

pub fn collect_calls_in_expr(
    caller: String,
    texpr: Arc<Node>,
    local_func_set: Arc<HashMap<String, bool>>,
    source_indices: Arc<HashMap<String, Arc<NewlineIndex>>>,
) -> Arc<Vec<Arc<CallEdge>>> {
    stacker::maybe_grow(512 * 1024, 2 * 1024 * 1024, || {
        let this_edges = match (*texpr.expr_data.clone()).clone() {
            ExprData::ExprCall { .. } => {
                let f = expr_call_func_at(texpr.clone(), source_indices.clone());
                if emit_map_has(local_func_set.clone(), f.clone()) {
                    Arc::new(vec![Arc::new(CallEdge {
                        caller: caller.clone(),
                        callee: f.clone(),
                    })])
                } else {
                    Arc::new(vec![])
                }
            }
            _ => Arc::new(vec![]),
        };
        let child_edges = Arc::new({
            let mut __result = Vec::new();
            for child in texpr.children.clone().iter().cloned() {
                __result.extend(
                    (*collect_calls_in_expr(
                        caller.clone(),
                        child.clone(),
                        local_func_set.clone(),
                        source_indices.clone(),
                    ))
                    .iter()
                    .cloned(),
                );
            }
            __result
        });
        let result = v1_rt::concat(this_edges.clone(), child_edges.clone());
        result
    })
}

pub fn func_reaches_self(
    root: String,
    current: String,
    call_edges: Arc<Vec<Arc<CallEdge>>>,
    visited: Arc<HashMap<String, bool>>,
) -> bool {
    stacker::maybe_grow(512 * 1024, 2 * 1024 * 1024, || {
        if emit_map_has(visited.clone(), current.clone()) {
            false
        } else {
            {
                let next_visited = v1_rt::rc_map_insert(visited.clone(), current.clone(), true);
                let callees = Arc::new({
                    let mut __result = Vec::new();
                    for e in Arc::new({
                        let mut __result = Vec::new();
                        for e in call_edges.clone().iter().cloned() {
                            if (e.caller.clone() == current.clone()) {
                                __result.push(e);
                            }
                        }
                        __result
                    })
                    .iter()
                    .cloned()
                    {
                        __result.push(e.callee.clone());
                    }
                    __result
                });
                {
                    let mut __found = false;
                    for c in callees.clone().iter().cloned() {
                        if if (c.clone() == root.clone()) {
                            true
                        } else {
                            func_reaches_self(
                                root.clone(),
                                c.clone(),
                                call_edges.clone(),
                                next_visited.clone(),
                            )
                        } {
                            __found = true;
                            break;
                        }
                    }
                    __found
                }
            }
        }
    })
}

pub fn build_name_set(names: Arc<Vec<String>>) -> Arc<HashMap<String, bool>> {
    names.clone().iter().cloned().fold(
        v1_rt::rc_empty_map::<String, bool>(),
        |acc: Arc<HashMap<String, bool>>, name: String| {
            v1_rt::rc_map_insert(acc, name.clone(), true)
        },
    )
}

pub fn declared_to_resolved(dsig: Arc<DeclaredFuncSig>) -> Arc<ResolvedFuncSig> {
    Arc::new(ResolvedFuncSig {
        name: dsig.name.clone(),
        params: dsig.params.clone(),
        inferred: dsig.inferred.clone().clone().unwrap(),
        is_async: dsig.is_async.clone(),
        output_provenance: dsig.output_provenance.clone(),
        variant_provenance: dsig.variant_provenance.clone(),
    })
}

pub fn merge_remaining_declared(
    declared_sigs: Arc<HashMap<String, Arc<DeclaredFuncSig>>>,
    resolved: Arc<HashMap<String, Arc<ResolvedFuncSig>>>,
) -> Arc<HashMap<String, Arc<ResolvedFuncSig>>> {
    Arc::new(v1_rt::map_values(&declared_sigs))
        .iter()
        .cloned()
        .fold(
            resolved.clone(),
            |acc: Arc<HashMap<String, Arc<ResolvedFuncSig>>>, dsig: Arc<DeclaredFuncSig>| {
                if (dsig.inferred.clone() != None) {
                    v1_rt::rc_map_insert(
                        acc.clone(),
                        dsig.name.clone(),
                        declared_to_resolved(dsig.clone()),
                    )
                } else {
                    acc.clone()
                }
            },
        )
}

pub fn topo_resolve_loop(
    mut remaining: Arc<Vec<String>>,
    mut resolved: Arc<HashMap<String, Arc<ResolvedFuncSig>>>,
    mut declared_sigs: Arc<HashMap<String, Arc<DeclaredFuncSig>>>,
    mut call_edges: Arc<Vec<Arc<CallEdge>>>,
    mut local_func_set: Arc<HashMap<String, bool>>,
    mut module_name: String,
    mut diagnostics: Arc<Vec<Arc<ErrorNode>>>,
    mut parent_envs: Arc<Vec<Arc<ResolvedFuncEnv>>>,
    mut fuel: i64,
) -> Arc<ResolveFuncSigsResult> {
    loop {
        if ((remaining.clone().len() as i64) == 0) {
            {
                let all_resolved = Arc::new(v1_rt::map_values(&declared_sigs))
                    .iter()
                    .cloned()
                    .fold(
                        resolved.clone(),
                        |acc: Arc<HashMap<String, Arc<ResolvedFuncSig>>>,
                         dsig: Arc<DeclaredFuncSig>| {
                            if (dsig.inferred.clone() != None) {
                                v1_rt::rc_map_insert(
                                    acc.clone(),
                                    dsig.name.clone(),
                                    declared_to_resolved(dsig.clone()),
                                )
                            } else {
                                acc.clone()
                            }
                        },
                    );
                return Arc::new(ResolveFuncSigsResult {
                    func_env: Arc::new(ResolvedFuncEnv {
                        name: module_name.clone(),
                        local: all_resolved.clone(),
                        parents: parent_envs.clone(),
                    }),
                    diagnostics: diagnostics.clone(),
                });
            }
        }
        let ready = Arc::new({
            let mut __result = Vec::new();
            for fn_name in remaining.clone().iter().cloned() {
                if {
                    let local_callees = Arc::new({
                        let mut __result = Vec::new();
                        for c in Arc::new({
                            let mut __result = Vec::new();
                            for e in Arc::new({
                                let mut __result = Vec::new();
                                for e in call_edges.clone().iter().cloned() {
                                    if (e.caller.clone() == fn_name.clone()) {
                                        __result.push(e);
                                    }
                                }
                                __result
                            })
                            .iter()
                            .cloned()
                            {
                                __result.push(e.callee.clone());
                            }
                            __result
                        })
                        .iter()
                        .cloned()
                        {
                            if emit_map_has(local_func_set.clone(), c.clone()) {
                                __result.push(c);
                            }
                        }
                        __result
                    });
                    {
                        let mut __all = true;
                        for c in local_callees.clone().iter().cloned() {
                            if !(v1_rt::map_get(&resolved, c.clone()) != None) {
                                __all = false;
                                break;
                            }
                        }
                        __all
                    }
                } {
                    __result.push(fn_name);
                }
            }
            __result
        });
        if ((ready.clone().len() as i64) == 0) {
            {
                let cycle_accum = remaining.clone().iter().cloned().fold(
                    Arc::new(SigsAccum {
                        signatures: resolved.clone(),
                        diagnostics: Arc::new(vec![]),
                    }),
                    |acc: Arc<SigsAccum>, fn_name: String| match v1_rt::map_get(
                        &declared_sigs,
                        fn_name.clone(),
                    ) {
                        Some(dsig) => {
                            if (dsig.inferred.clone() != None) {
                                Arc::new(SigsAccum {
                                    signatures: v1_rt::rc_map_insert(
                                        acc.signatures.clone(),
                                        fn_name.clone(),
                                        declared_to_resolved(dsig.clone()),
                                    ),
                                    diagnostics: acc.diagnostics.clone(),
                                })
                            } else {
                                Arc::new(SigsAccum {
                                    signatures: acc.signatures.clone(),
                                    diagnostics: v1_rt::rc_list_push(
                                        acc.diagnostics.clone(),
                                        make_error_node(
                                            Arc::new(CompilerDiagnostic::MissingAnnotation {
                                                fn_name: fn_name.clone(),
                                                what: "return type (recursive)".to_string(),
                                                span: no_span(),
                                            }),
                                            module_name.clone(),
                                        ),
                                    ),
                                })
                            }
                        }
                        None => acc.clone(),
                    },
                );
                let all_resolved = Arc::new(v1_rt::map_values(&declared_sigs))
                    .iter()
                    .cloned()
                    .fold(
                        cycle_accum.signatures.clone(),
                        |acc: Arc<HashMap<String, Arc<ResolvedFuncSig>>>,
                         dsig: Arc<DeclaredFuncSig>| {
                            if (dsig.inferred.clone() != None) {
                                v1_rt::rc_map_insert(
                                    acc.clone(),
                                    dsig.name.clone(),
                                    declared_to_resolved(dsig.clone()),
                                )
                            } else {
                                acc.clone()
                            }
                        },
                    );
                return Arc::new(ResolveFuncSigsResult {
                    func_env: Arc::new(ResolvedFuncEnv {
                        name: module_name.clone(),
                        local: all_resolved.clone(),
                        parents: parent_envs.clone(),
                    }),
                    diagnostics: v1_rt::concat(
                        diagnostics.clone(),
                        cycle_accum.diagnostics.clone(),
                    ),
                });
            }
        }
        let ready_accum = ready.clone().iter().cloned().fold(
            Arc::new(SigsAccum {
                signatures: resolved.clone(),
                diagnostics: diagnostics.clone(),
            }),
            |acc: Arc<SigsAccum>, fn_name: String| match v1_rt::map_get(
                &declared_sigs,
                fn_name.clone(),
            ) {
                Some(dsig) => {
                    if (dsig.inferred.clone() != None) {
                        Arc::new(SigsAccum {
                            signatures: v1_rt::rc_map_insert(
                                acc.signatures.clone(),
                                fn_name.clone(),
                                declared_to_resolved(dsig.clone()),
                            ),
                            diagnostics: acc.diagnostics.clone(),
                        })
                    } else {
                        Arc::new(SigsAccum {
                            signatures: acc.signatures.clone(),
                            diagnostics: v1_rt::rc_list_push(
                                acc.diagnostics.clone(),
                                make_error_node(
                                    Arc::new(CompilerDiagnostic::MissingAnnotation {
                                        fn_name: fn_name.clone(),
                                        what: "return type".to_string(),
                                        span: no_span(),
                                    }),
                                    module_name.clone(),
                                ),
                            ),
                        })
                    }
                }
                None => acc.clone(),
            },
        );
        let ready_set = ready.clone().iter().cloned().fold(
            v1_rt::rc_empty_map::<String, bool>(),
            |acc: Arc<HashMap<String, bool>>, fn_name: String| {
                v1_rt::rc_map_insert(acc, fn_name.clone(), true)
            },
        );
        let next_remaining = Arc::new({
            let mut __result = Vec::new();
            for fn_name in remaining.clone().iter().cloned() {
                if (emit_map_has(ready_set.clone(), fn_name.clone()) == false) {
                    __result.push(fn_name);
                }
            }
            __result
        });
        {
            let __tco_0 = next_remaining.clone();
            let __tco_1 = ready_accum.signatures.clone();
            let __tco_2 = ready_accum.diagnostics.clone();
            let __tco_3 = (fuel - 1);
            remaining = __tco_0;
            resolved = __tco_1;
            diagnostics = __tco_2;
            fuel = __tco_3;
            continue;
        }
    }
}

pub fn resolve_func_sigs(
    declared_sigs: Arc<HashMap<String, Arc<DeclaredFuncSig>>>,
    parent_envs: Arc<Vec<Arc<ResolvedFuncEnv>>>,
    items: Arc<Vec<Arc<Node>>>,
    module_name: String,
    source_indices: Arc<HashMap<String, Arc<NewlineIndex>>>,
) -> Arc<ResolveFuncSigsResult> {
    {
        let local_func_names = Arc::new({
            let mut __result = Vec::new();
            for item in Arc::new({
                let mut __result = Vec::new();
                for item in items.clone().iter().cloned() {
                    if (((item.params.clone().len() as i64) > 0) && (item.body.clone() != None)) {
                        __result.push(item);
                    }
                }
                __result
            })
            .iter()
            .cloned()
            {
                __result.push(authored_name_at(source_indices.clone(), item.clone()));
            }
            __result
        });
        let local_func_set = build_name_set(local_func_names.clone());
        let call_edges = collect_func_call_edges(
            items.clone(),
            local_func_set.clone(),
            source_indices.clone(),
        );
        topo_resolve_loop(
            local_func_names.clone(),
            v1_rt::rc_empty_map::<String, Arc<ResolvedFuncSig>>(),
            declared_sigs.clone(),
            call_edges.clone(),
            local_func_set.clone(),
            module_name.clone(),
            Arc::new(vec![]),
            flatten_parent_envs(parent_envs.clone()),
            (local_func_names.clone().len() as i64),
        )
    }
}
