// Generated by v1 compiler -- do not edit.
// Source module: v1.tests.claim.carrier_realization_census

use self::CensusOutcome::*;
use self::DeclarationIdentityObservation::*;
use self::LegacyKeyObservation::*;
use crate::std_coercion::ReferenceIdentityUnavailableCause::{
    DeclarationNodeCarriesNoSpan, NoResolutionBoundAtReference, ResolvedNodeIsNotADeclaration,
};
use crate::std_coercion::TypeDeclarationProvenance::DeclarationIdentityAbsent;
use crate::std_coercion::TypeRealizationDecision::{RealizationRefused, Realized, Unrealized};
use crate::std_coercion::TypeReferenceIdentity::{
    ReferenceIdentityUnavailable, ReferenceIsTheDeclaration, ReferenceIsTypeVariableBinder,
    ReferenceResolvedToDeclaration,
};
pub use crate::std_coercion::{
    ReferenceIdentityUnavailableCause, TypeDeclarationProvenance, TypeRealizationDecision,
    TypeReferenceIdentity,
};
pub use crate::std_decl_ref::declaration_ref_display_key;
pub use crate::std_decl_ref::DeclarationRef;
pub use crate::std_types::{Bool, List, Map};
pub use crate::v1_compiler_artifact::RenderTarget;
use crate::v1_compiler_artifact::RenderTarget::Rust;
pub use crate::v1_compiler_coercion::type_realization_decision;
pub use crate::v1_compiler_compile::compile_to_resolved;
pub use crate::v1_compiler_compile::{ResolvedPipelineResult, SourceFile};
pub use crate::v1_compiler_emit_core_support::is_type_def_item;
pub use crate::v1_compiler_emit_rust::{function_value_params, is_host_text_carrier_type};
pub use crate::v1_compiler_infer::declared_return_type_node;
use crate::v1_compiler_infer_env::TypeNodeUnidentifiedCause::{
    TypeNodeAuthoredNameEmpty, TypeNodeCarriesNoSpan, TypeNodeNameDeclaredNowhere,
    TypeNodeQualifierMatchesNoDeclarer, TypeNodeSpanDeclaresNothing,
};
use crate::v1_compiler_infer_env::TypeReferenceDeclarationReading::{
    TypeReferenceIsKernelType, TypeReferenceIsTypeVariable, TypeReferenceNamesDeclaration,
    TypeReferenceUnidentified,
};
pub use crate::v1_compiler_infer_env::{lookup_type_for, type_reference_declaration_reading};
pub use crate::v1_compiler_infer_env::{
    TypeEnv, TypeNodeUnidentifiedCause, TypeReferenceDeclarationReading,
};
pub use crate::v1_compiler_infer_items::{ResolvedGraph, TypedModule};
pub use crate::v1_compiler_infer_types::{child_type_node, is_coproduct_type};
use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::v1_std_core::Connective::Arrow;
use crate::v1_std_core::InferredNode::Resolved;
use crate::v1_std_core::ParsedModuleItemKind::ModuleItemTypeDeclaration;
pub use crate::v1_std_core::{
    authored_name_at, declaration_provenance_of, param_node_type_expr, provenance_reported_file,
    type_reference_identity, type_reference_provenance,
};
pub use crate::v1_std_core::{Connective, InferredNode, NewlineIndex, Node, ParsedModuleItemKind};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum DeclarationIdentityObservation {
    IdentityFromInference {
        provenance: Rc<TypeDeclarationProvenance>,
    },
    IdentityFromEnvironment {
        provenance: Rc<TypeDeclarationProvenance>,
    },
    IdentitiesAgree {
        provenance: Rc<TypeDeclarationProvenance>,
    },
    IdentitiesDisagree {
        inferred: String,
        environment: String,
    },
    IdentityUnavailableBoth,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum LegacyKeyObservation {
    LegacyFallbackUsed { reference_file: String },
    LegacyKeyResolved { decl_file: String },
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(tag = "_variant")]
pub enum CensusOutcome {
    Agrees,
    DivergesWithExactIdentity,
    IdentityUnavailable,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TypedCarrierRow {
    pub module_file: String,
    pub enclosing_decl: String,
    pub position_kind: String,
    pub authored_name: String,
    pub identity: Rc<DeclarationIdentityObservation>,
    pub legacy: Rc<LegacyKeyObservation>,
    pub split: Rc<TypeReferenceIdentity>,
    pub decl_identity: Rc<TypeReferenceDeclarationReading>,
    pub legacy_base: String,
    pub authority_base: String,
    pub outcome: CensusOutcome,
    pub recorded_declaration: Option<Rc<DeclarationRef>>,
}

pub fn identity_observation(
    inferred: Rc<TypeDeclarationProvenance>,
    environment: Rc<TypeDeclarationProvenance>,
) -> Rc<DeclarationIdentityObservation> {
    {
        let inf = crate::v1_std_core::provenance_reported_file(inferred.clone());
        let env = crate::v1_std_core::provenance_reported_file(environment.clone());
        if ((inf.clone() == "".to_string()) && (env.clone() == "".to_string())) {
            Rc::new(DeclarationIdentityObservation::IdentityUnavailableBoth)
        } else {
            if (inf.clone() == "".to_string()) {
                Rc::new(DeclarationIdentityObservation::IdentityFromEnvironment {
                    provenance: environment.clone(),
                })
            } else {
                if (env.clone() == "".to_string()) {
                    Rc::new(DeclarationIdentityObservation::IdentityFromInference {
                        provenance: inferred.clone(),
                    })
                } else {
                    if (inf.clone() == env.clone()) {
                        Rc::new(DeclarationIdentityObservation::IdentitiesAgree {
                            provenance: inferred.clone(),
                        })
                    } else {
                        Rc::new(DeclarationIdentityObservation::IdentitiesDisagree {
                            inferred: inf.clone(),
                            environment: env.clone(),
                        })
                    }
                }
            }
        }
    }
}

pub fn inferred_identity_provenance(n: Rc<Node>) -> Rc<TypeDeclarationProvenance> {
    match n.inferred.clone().as_deref().cloned() {
        Some(InferredNode::Resolved { node: rt, .. }) => {
            crate::v1_std_core::declaration_provenance_of(rt.clone())
        }
        _ => Rc::new(TypeDeclarationProvenance::DeclarationIdentityAbsent),
    }
}

pub fn environment_identity_provenance(
    env: Rc<TypeEnv>,
    n: Rc<Node>,
) -> Rc<TypeDeclarationProvenance> {
    match crate::v1_compiler_infer_env::lookup_type_for(env.clone(), n.clone()) {
        Some(d) => crate::v1_std_core::declaration_provenance_of(d.clone()),
        std::option::Option::None => Rc::new(TypeDeclarationProvenance::DeclarationIdentityAbsent),
    }
}

pub fn legacy_observation(had_inference: bool, key: String) -> Rc<LegacyKeyObservation> {
    if had_inference.clone() {
        Rc::new(LegacyKeyObservation::LegacyKeyResolved {
            decl_file: key.clone(),
        })
    } else {
        Rc::new(LegacyKeyObservation::LegacyFallbackUsed {
            reference_file: key.clone(),
        })
    }
}

pub fn identity_query_provenance(
    o: Rc<DeclarationIdentityObservation>,
) -> Rc<TypeDeclarationProvenance> {
    match (*o.clone()).clone() {
        DeclarationIdentityObservation::IdentityFromInference { provenance: d, .. } => d.clone(),
        DeclarationIdentityObservation::IdentityFromEnvironment { provenance: d, .. } => d.clone(),
        DeclarationIdentityObservation::IdentitiesAgree { provenance: d, .. } => d.clone(),
        DeclarationIdentityObservation::IdentitiesDisagree { .. } => {
            Rc::new(TypeDeclarationProvenance::DeclarationIdentityAbsent)
        }
        DeclarationIdentityObservation::IdentityUnavailableBoth => {
            Rc::new(TypeDeclarationProvenance::DeclarationIdentityAbsent)
        }
    }
}

pub fn legacy_claims_text(n: Rc<Node>, si: Rc<HashMap<String, Rc<NewlineIndex>>>) -> bool {
    crate::v1_compiler_emit_rust::is_host_text_carrier_type(n.clone(), si.clone())
}

pub fn authority_realizes(name: String, provenance: Rc<TypeDeclarationProvenance>) -> bool {
    match (*crate::v1_compiler_coercion::type_realization_decision(
        RenderTarget::Rust,
        name.clone(),
        provenance.clone(),
    ))
    .clone()
    {
        TypeRealizationDecision::Realized { .. } => true,
        TypeRealizationDecision::Unrealized => false,
        TypeRealizationDecision::RealizationRefused { cause: _, .. } => false,
    }
}

pub fn legacy_base_label(n: Rc<Node>, si: Rc<HashMap<String, Rc<NewlineIndex>>>) -> String {
    if crate::v1_compiler_emit_rust::is_host_text_carrier_type(n.clone(), si.clone()) {
        "String".to_string()
    } else {
        "<not-short-circuited>".to_string()
    }
}

pub fn authority_base_of(name: String, provenance: Rc<TypeDeclarationProvenance>) -> String {
    match (*crate::v1_compiler_coercion::type_realization_decision(
        RenderTarget::Rust,
        name.clone(),
        provenance.clone(),
    ))
    .clone()
    {
        TypeRealizationDecision::Realized { checkpoint: cp, .. } => cp.target_type.clone(),
        TypeRealizationDecision::Unrealized => "<structural>".to_string(),
        TypeRealizationDecision::RealizationRefused { cause: _, .. } => "<refused>".to_string(),
    }
}

pub fn outcome_of(claims_text: bool, realizes: bool, query_file: String) -> CensusOutcome {
    if (query_file.clone() == "".to_string()) {
        CensusOutcome::IdentityUnavailable
    } else {
        if (claims_text.clone() && !realizes.clone()) {
            CensusOutcome::DivergesWithExactIdentity
        } else {
            CensusOutcome::Agrees
        }
    }
}

pub fn typed_decision_row(
    module_file: String,
    enclosing: String,
    position_kind: String,
    n: Rc<Node>,
    decl_identity: Rc<TypeReferenceDeclarationReading>,
    env: Rc<TypeEnv>,
    si: Rc<HashMap<String, Rc<NewlineIndex>>>,
) -> Rc<TypedCarrierRow> {
    {
        let inferred = inferred_identity_provenance(n.clone());
        let environment = environment_identity_provenance(env.clone(), n.clone());
        let legacy_key = crate::v1_std_core::provenance_reported_file(
            crate::v1_std_core::type_reference_provenance(n.clone()),
        );
        let identity = identity_observation(inferred.clone(), environment.clone());
        let query_provenance = identity_query_provenance(identity.clone());
        let query_file = crate::v1_std_core::provenance_reported_file(query_provenance.clone());
        let name = crate::v1_std_core::authored_name_at(si.clone(), n.clone());
        let claims_text = legacy_claims_text(n.clone(), si.clone());
        Rc::new(TypedCarrierRow {
            module_file: module_file.clone(),
            enclosing_decl: enclosing.clone(),
            position_kind: position_kind.clone(),
            authored_name: name.clone(),
            identity: identity.clone(),
            legacy: legacy_observation(
                (crate::v1_std_core::provenance_reported_file(inferred.clone()) != "".to_string()),
                legacy_key.clone(),
            ),
            split: crate::v1_std_core::type_reference_identity(n.clone()),
            decl_identity: decl_identity.clone(),
            legacy_base: legacy_base_label(n.clone(), si.clone()),
            authority_base: authority_base_of(name.clone(), query_provenance.clone()),
            recorded_declaration: n.declaration.clone(),
            outcome: outcome_of(
                claims_text.clone(),
                authority_realizes(name.clone(), query_provenance.clone()),
                query_file.clone(),
            ),
        })
    }
}

pub fn no_typed_rows() -> Rc<Vec<Rc<TypedCarrierRow>>> {
    Rc::new(vec![])
}

pub fn typed_occurrence_rows(
    module_file: String,
    enclosing: String,
    position_kind: String,
    n: Rc<Node>,
    env: Rc<TypeEnv>,
    si: Rc<HashMap<String, Rc<NewlineIndex>>>,
) -> Rc<Vec<Rc<TypedCarrierRow>>> {
    stacker::maybe_grow(512 * 1024, 2 * 1024 * 1024, || {
        let node_is_arrow = match n.connective.clone() {
            Connective::Arrow => true,
            _ => false,
        };
        if node_is_arrow.clone() {
            {
                let param_rows = n.params.clone().iter().cloned().fold(
                    no_typed_rows(),
                    |acc: _, p: Rc<Node>| {
                        v1_rt::concat(
                            acc,
                            typed_occurrence_rows(
                                module_file.clone(),
                                enclosing.clone(),
                                v1_rt::concat(position_kind.clone(), "/fn_type_param".to_string()),
                                crate::v1_std_core::param_node_type_expr(p.clone()),
                                env.clone(),
                                si.clone(),
                            ),
                        )
                    },
                );
                let return_rows = match n.inferred.clone().as_deref().cloned() {
                    Some(InferredNode::Resolved { node: rt, .. }) => typed_occurrence_rows(
                        module_file.clone(),
                        enclosing.clone(),
                        v1_rt::concat(position_kind.clone(), "/fn_type_return".to_string()),
                        rt.clone(),
                        env.clone(),
                        si.clone(),
                    ),
                    _ => no_typed_rows(),
                };
                v1_rt::concat(param_rows.clone(), return_rows.clone())
            }
        } else {
            {
                let is_declaration = match n.module_item_kind.clone() {
                    ParsedModuleItemKind::ModuleItemTypeDeclaration => true,
                    _ => false,
                };
                let decl_identity =
                    crate::v1_compiler_infer_env::type_reference_declaration_reading(
                        n.clone(),
                        si.clone(),
                        env.clone(),
                    );
                let is_kernel_mint = match (*decl_identity.clone()).clone() {
                    TypeReferenceDeclarationReading::TypeReferenceIsKernelType {
                        name: _, ..
                    } => true,
                    _ => false,
                };
                let arg_children = if (is_declaration.clone() || is_kernel_mint.clone()) {
                    Rc::new(vec![])
                } else {
                    n.children.clone()
                };
                let arg_rows =
                    arg_children
                        .iter()
                        .cloned()
                        .fold(no_typed_rows(), |acc: _, a: Rc<Node>| {
                            v1_rt::concat(
                                acc,
                                typed_occurrence_rows(
                                    module_file.clone(),
                                    enclosing.clone(),
                                    v1_rt::concat(position_kind.clone(), "/type_arg".to_string()),
                                    a.clone(),
                                    env.clone(),
                                    si.clone(),
                                ),
                            )
                        });
                v1_rt::concat(
                    Rc::new(vec![typed_decision_row(
                        module_file.clone(),
                        enclosing.clone(),
                        position_kind.clone(),
                        n.clone(),
                        decl_identity.clone(),
                        env.clone(),
                        si.clone(),
                    )]),
                    arg_rows.clone(),
                )
            }
        }
    })
}

pub fn typed_field_rows(
    module_file: String,
    enclosing: String,
    fields: Rc<Vec<Rc<Node>>>,
    env: Rc<TypeEnv>,
    si: Rc<HashMap<String, Rc<NewlineIndex>>>,
) -> Rc<Vec<Rc<TypedCarrierRow>>> {
    fields
        .iter()
        .cloned()
        .fold(no_typed_rows(), |acc: _, fld: Rc<Node>| {
            v1_rt::concat(
                acc,
                typed_occurrence_rows(
                    module_file.clone(),
                    enclosing.clone(),
                    "declaration_field".to_string(),
                    crate::v1_compiler_infer_types::child_type_node(fld.clone()),
                    env.clone(),
                    si.clone(),
                ),
            )
        })
}

pub fn typed_item_rows(
    module_file: String,
    item: Rc<Node>,
    env: Rc<TypeEnv>,
    si: Rc<HashMap<String, Rc<NewlineIndex>>>,
) -> Rc<Vec<Rc<TypedCarrierRow>>> {
    {
        let enclosing = crate::v1_std_core::authored_name_at(si.clone(), item.clone());
        let decl_rows = if !crate::v1_compiler_emit_core_support::is_type_def_item(item.clone()) {
            no_typed_rows()
        } else {
            if crate::v1_compiler_infer_types::is_coproduct_type(item.clone()) {
                item.children.clone().iter().cloned().fold(
                    no_typed_rows(),
                    |acc: _, variant: Rc<Node>| {
                        v1_rt::concat(
                            acc,
                            typed_field_rows(
                                module_file.clone(),
                                enclosing.clone(),
                                variant.children.clone(),
                                env.clone(),
                                si.clone(),
                            ),
                        )
                    },
                )
            } else {
                typed_field_rows(
                    module_file.clone(),
                    enclosing.clone(),
                    item.children.clone(),
                    env.clone(),
                    si.clone(),
                )
            }
        };
        let param_rows_t = if (item.body.clone() == std::option::Option::None) {
            no_typed_rows()
        } else {
            crate::v1_compiler_emit_rust::function_value_params(item.params.clone())
                .iter()
                .cloned()
                .fold(no_typed_rows(), |acc: _, prm: Rc<Node>| {
                    v1_rt::concat(
                        acc,
                        typed_occurrence_rows(
                            module_file.clone(),
                            enclosing.clone(),
                            "fn_signature_param".to_string(),
                            crate::v1_std_core::param_node_type_expr(prm.clone()),
                            env.clone(),
                            si.clone(),
                        ),
                    )
                })
        };
        let return_rows = if ((item.body.clone() == std::option::Option::None)
            || crate::v1_compiler_emit_core_support::is_type_def_item(item.clone()))
        {
            no_typed_rows()
        } else {
            typed_occurrence_rows(
                module_file.clone(),
                enclosing.clone(),
                "fn_signature_return".to_string(),
                crate::v1_compiler_infer::declared_return_type_node(item.clone()),
                env.clone(),
                si.clone(),
            )
        };
        v1_rt::concat(
            v1_rt::concat(decl_rows.clone(), param_rows_t.clone()),
            return_rows.clone(),
        )
    }
}

pub fn typed_module_rows(
    m: Rc<TypedModule>,
    si: Rc<HashMap<String, Rc<NewlineIndex>>>,
) -> Rc<Vec<Rc<TypedCarrierRow>>> {
    {
        let module_file = crate::v1_std_core::authored_name_at(si.clone(), m.module.clone());
        m.items
            .clone()
            .iter()
            .cloned()
            .fold(no_typed_rows(), |acc: _, item: Rc<Node>| {
                v1_rt::concat(
                    acc,
                    typed_item_rows(
                        module_file.clone(),
                        item.clone(),
                        m.type_env.clone(),
                        si.clone(),
                    ),
                )
            })
    }
}

pub fn identity_label(o: Rc<DeclarationIdentityObservation>) -> String {
    match (*o.clone()).clone() {
        DeclarationIdentityObservation::IdentityFromInference { provenance: _, .. } => {
            "FromInference".to_string()
        }
        DeclarationIdentityObservation::IdentityFromEnvironment { provenance: _, .. } => {
            "FromEnvironment".to_string()
        }
        DeclarationIdentityObservation::IdentitiesAgree { provenance: _, .. } => {
            "Agree".to_string()
        }
        DeclarationIdentityObservation::IdentitiesDisagree { .. } => "DISAGREE".to_string(),
        DeclarationIdentityObservation::IdentityUnavailableBoth => "UnavailableBoth".to_string(),
    }
}

pub fn identity_file_label(o: Rc<DeclarationIdentityObservation>) -> String {
    match (*o.clone()).clone() {
        DeclarationIdentityObservation::IdentityFromInference { provenance: d, .. } => {
            crate::v1_std_core::provenance_reported_file(d.clone())
        }
        DeclarationIdentityObservation::IdentityFromEnvironment { provenance: d, .. } => {
            crate::v1_std_core::provenance_reported_file(d.clone())
        }
        DeclarationIdentityObservation::IdentitiesAgree { provenance: d, .. } => {
            crate::v1_std_core::provenance_reported_file(d.clone())
        }
        DeclarationIdentityObservation::IdentitiesDisagree {
            inferred: i,
            environment: e,
            ..
        } => v1_rt::concat(v1_rt::concat(i.clone(), " != ".to_string()), e.clone()),
        DeclarationIdentityObservation::IdentityUnavailableBoth => "".to_string(),
    }
}

pub fn legacy_label(l: Rc<LegacyKeyObservation>) -> String {
    match (*l.clone()).clone() {
        LegacyKeyObservation::LegacyFallbackUsed {
            reference_file: f, ..
        } => v1_rt::concat("FALLBACK:".to_string(), f.clone()),
        LegacyKeyObservation::LegacyKeyResolved { decl_file: d, .. } => {
            v1_rt::concat("resolved:".to_string(), d.clone())
        }
    }
}

pub fn split_cause_label(c: ReferenceIdentityUnavailableCause) -> String {
    match c.clone() {
        ReferenceIdentityUnavailableCause::NoResolutionBoundAtReference => {
            "NoResolutionBoundAtReference".to_string()
        }
        ReferenceIdentityUnavailableCause::ResolvedNodeIsNotADeclaration => {
            "ResolvedNodeIsNotADeclaration".to_string()
        }
        ReferenceIdentityUnavailableCause::DeclarationNodeCarriesNoSpan => {
            "DeclarationNodeCarriesNoSpan".to_string()
        }
    }
}

pub fn split_label(i: Rc<TypeReferenceIdentity>) -> String {
    match (*i.clone()).clone() {
        TypeReferenceIdentity::ReferenceResolvedToDeclaration { provenance: p, .. } => {
            v1_rt::concat(
                "ResolvedToDeclaration:".to_string(),
                crate::v1_std_core::provenance_reported_file(p.clone()),
            )
        }
        TypeReferenceIdentity::ReferenceIsTheDeclaration { provenance: p, .. } => v1_rt::concat(
            "IsTheDeclaration:".to_string(),
            crate::v1_std_core::provenance_reported_file(p.clone()),
        ),
        TypeReferenceIdentity::ReferenceIsTypeVariableBinder { binder_name: b, .. } => {
            v1_rt::concat("TypeVariableBinder:".to_string(), b.clone())
        }
        TypeReferenceIdentity::ReferenceIdentityUnavailable { cause: c, .. } => {
            v1_rt::concat("Unavailable:".to_string(), split_cause_label(c.clone()))
        }
    }
}

pub fn unidentified_cause_label(c: Rc<TypeNodeUnidentifiedCause>) -> String {
    match (*c.clone()).clone() {
        TypeNodeUnidentifiedCause::TypeNodeAuthoredNameEmpty => "AuthoredNameEmpty".to_string(),
        TypeNodeUnidentifiedCause::TypeNodeNameDeclaredNowhere { name: _, .. } => {
            "NameDeclaredNowhere".to_string()
        }
        TypeNodeUnidentifiedCause::TypeNodeSpanDeclaresNothing { name: _, .. } => {
            "SpanDeclaresNothing".to_string()
        }
        TypeNodeUnidentifiedCause::TypeNodeCarriesNoSpan { name: _, .. } => {
            "CarriesNoSpan".to_string()
        }
        TypeNodeUnidentifiedCause::TypeNodeQualifierMatchesNoDeclarer { qualified: _, .. } => {
            "QualifierMatchesNoDeclarer".to_string()
        }
    }
}

pub fn decl_identity_label(r: Rc<TypeReferenceDeclarationReading>) -> String {
    match (*r.clone()).clone() {
        TypeReferenceDeclarationReading::TypeReferenceNamesDeclaration {
            declaration: d, ..
        } => v1_rt::concat(
            "Declaration:".to_string(),
            crate::std_decl_ref::declaration_ref_display_key(d.clone()),
        ),
        TypeReferenceDeclarationReading::TypeReferenceIsKernelType { name: k, .. } => {
            v1_rt::concat("Kernel:".to_string(), k.clone())
        }
        TypeReferenceDeclarationReading::TypeReferenceIsTypeVariable { id: v, .. } => {
            v1_rt::concat("TypeVariable:".to_string(), v.clone())
        }
        TypeReferenceDeclarationReading::TypeReferenceUnidentified {
            authored: a,
            resolved: r2,
            ..
        } => match r2.clone() {
            Some(rc) => v1_rt::concat(
                v1_rt::concat(
                    v1_rt::concat(
                        "Unidentified:".to_string(),
                        unidentified_cause_label(a.clone()),
                    ),
                    "/resolved:".to_string(),
                ),
                unidentified_cause_label(rc.clone()),
            ),
            std::option::Option::None => v1_rt::concat(
                v1_rt::concat(
                    "Unidentified:".to_string(),
                    unidentified_cause_label(a.clone()),
                ),
                "/resolved:none".to_string(),
            ),
        },
    }
}

pub fn recorded_declaration_label(d: Option<Rc<DeclarationRef>>) -> String {
    match d.clone() {
        Some(r) => v1_rt::concat(
            "Declaration:".to_string(),
            crate::std_decl_ref::declaration_ref_display_key(r.clone()),
        ),
        std::option::Option::None => "none".to_string(),
    }
}

pub fn outcome_label(o: CensusOutcome) -> String {
    match o.clone() {
        CensusOutcome::Agrees => "Agrees".to_string(),
        CensusOutcome::DivergesWithExactIdentity => "DivergesWithExactIdentity".to_string(),
        CensusOutcome::IdentityUnavailable => "IdentityUnavailable".to_string(),
    }
}

pub fn tsv_escape(v: String) -> String {
    v1_rt::replace(
        v1_rt::replace(v.clone(), "\t".to_string(), "\\t".to_string()),
        "\n".to_string(),
        "\\n".to_string(),
    )
}

pub fn typed_census_header() -> String {
    "module_file\tenclosing_decl\tposition_kind\tauthored_name\tidentity\tidentity_file\tlegacy_key\tsplit_identity\tdecl_identity\tlegacy_base\tauthority_base\toutcome\trecorded_declaration".to_string()
}

pub fn typed_row_tsv(r: Rc<TypedCarrierRow>) -> String {
    Rc::new(vec![
        tsv_escape(r.module_file.clone()),
        tsv_escape(r.enclosing_decl.clone()),
        tsv_escape(r.position_kind.clone()),
        tsv_escape(r.authored_name.clone()),
        identity_label(r.identity.clone()),
        tsv_escape(identity_file_label(r.identity.clone())),
        tsv_escape(legacy_label(r.legacy.clone())),
        tsv_escape(split_label(r.split.clone())),
        tsv_escape(decl_identity_label(r.decl_identity.clone())),
        tsv_escape(r.legacy_base.clone()),
        tsv_escape(r.authority_base.clone()),
        outcome_label(r.outcome.clone()),
        recorded_declaration_label(r.recorded_declaration.clone()),
    ])
    .join(&"\t".to_string())
}

pub fn typed_census_tsv(rows: Rc<Vec<Rc<TypedCarrierRow>>>) -> String {
    rows.iter()
        .cloned()
        .fold(typed_census_header(), |acc: String, r: _| {
            v1_rt::concat(
                v1_rt::concat(acc, "\n".to_string()),
                typed_row_tsv(r.clone()),
            )
        })
}

pub fn typed_census_from_sources(sources: Rc<Vec<Rc<SourceFile>>>) -> String {
    {
        let result = crate::v1_compiler_compile::compile_to_resolved(sources.clone());
        match result.graph.clone() {
            std::option::Option::None => {
                "REFUSED\tcompile_to_resolved produced no graph".to_string()
            }
            Some(g) => typed_census_tsv(g.modules.clone().iter().cloned().fold(
                no_typed_rows(),
                |acc: _, m: Rc<TypedModule>| {
                    v1_rt::concat(
                        acc,
                        typed_module_rows(m.clone(), result.source_indices.clone()),
                    )
                },
            )),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Agrees;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct DivergesWithExactIdentity;
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct IdentityUnavailable;
