// Generated by v1 compiler -- do not edit.
// Source module: v1.tests.claim.reference_derived_closure_witness_test

pub use crate::std_occurrence_binding_candidates::cross_file_binding_closure_row;
use crate::std_occurrence_binding_candidates::BoundReferencePopulation::ReferencePopulationRefused;
use crate::std_occurrence_binding_candidates::DeclarationExposureGrounding::ModuleLocalMemberExposure;
use crate::std_occurrence_binding_candidates::ReferenceBindingProjection::{
    ReferenceBindingProjectionAmbiguous, ReferenceBindingProjectionUnbound,
};
pub use crate::std_occurrence_binding_candidates::{
    BoundReferencePopulation, CrossFileBindingClosureRow, CrossFileBindingProvenance,
    DeclarationExposureGrounding, DirectFileDependency, ReferenceBindingProjection,
};
pub use crate::std_occurrence_identity::{OccurrenceId, OccurrenceProjection, OccurrenceTransport};
use crate::std_reference_derived_closure::ReferenceDerivedClosureFixedPoint::{
    ClosureFixedPointExhausted, ClosureFixedPointRefused, ClosureFixedPointSettled,
};
use crate::std_reference_derived_closure::ReferenceDerivedClosureRefusal::{
    ClosureBindingRefused, ClosureNoEntryAdmitted,
};
use crate::std_reference_derived_closure::ReferenceDerivedClosureStep::{
    ClosureStepAdvanced, ClosureStepRefused, ClosureStepSettled,
};
pub use crate::std_reference_derived_closure::{
    reference_derived_closure_fixed_point, reference_derived_closure_initial,
    reference_derived_closure_step,
};
pub use crate::std_reference_derived_closure::{
    ParsedFileSupply, ReferenceDerivedClosureFixedPoint, ReferenceDerivedClosureRefusal,
    ReferenceDerivedClosureState, ReferenceDerivedClosureStep,
};
use crate::std_types::Bool::*;
pub use crate::std_types::{Bool, FilePath, List, NonEmptyStr};
pub use crate::v1_gunbc_occurrence_binding_parser_walk::ParsedOccurrenceBindingSource;
use crate::v1_gunbc_occurrence_binding_parser_walk::ParsedOccurrenceBindingSource::{
    ParsedOccurrenceBindingSourceReady, ParsedOccurrenceBindingSourceRefused,
};
pub use crate::v1_gunbc_occurrence_binding_parser_walk::{
    occurrence_binding_inputs_from_transport, parse_authored_occurrence_binding_source,
};
use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

pub fn rdc_note() -> String {
    thread_local! {
        static CACHED: String = {
            "THE LOADER FIXED POINT over the ordinary source-file universe.\n\nTWO POPULATIONS, NOT ONE. The candidate index is built over the WHOLE universe of parsed source files; the references BOUND are selected by the file they belong to, from the admitted closure only. That separation is what makes discovery possible: the declaration that a bare reference binds to is visible before the file carrying it is in the closure, and the edge derived from that binding is what admits the file. Collapsing the two deadlocks -- an unadmitted provider has no declaration in the index, so the reference is Unbound, so no provider file is derived, so nothing is ever admitted.\n\nA module-to-file index cannot substitute: storage realization says where a module lives and never which module declares a name.".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_consumer_path() -> String {
    thread_local! {
        static CACHED: String = {
            "dag/test/fixture/reference_derived_closure/consumer.dag".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_provider_path() -> String {
    thread_local! {
        static CACHED: String = {
            "src/v2/std/live_tree.dag".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_second_provider_path() -> String {
    thread_local! {
        static CACHED: String = {
            "dag/test/fixture/reference_derived_closure/second_provider.dag".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_unrelated_path() -> String {
    thread_local! {
        static CACHED: String = {
            "dag/test/fixture/reference_derived_closure/unrelated.dag".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_consumer_module() -> String {
    thread_local! {
        static CACHED: String = {
            "test.fixture.reference_derived_closure.consumer".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_later_path() -> String {
    thread_local! {
        static CACHED: String = {
            "dag/test/fixture/reference_derived_closure/later.dag".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_later_consumer_path() -> String {
    thread_local! {
        static CACHED: String = {
            "dag/test/fixture/reference_derived_closure/later_consumer.dag".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_early_path() -> String {
    thread_local! {
        static CACHED: String = {
            "dag/test/fixture/reference_derived_closure/early.dag".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_early_consumer_path() -> String {
    thread_local! {
        static CACHED: String = {
            "dag/test/fixture/reference_derived_closure/early_consumer.dag".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn rdc_later_source() -> String {
    (((((((((((("module test.fixture.reference_derived_closure.later\n".to_string()
        + &"\n".to_string())
        + &"type EarlyInLater\n".to_string())
        + &"  = EarlyOne\n".to_string())
        + &"  | EarlyTwo\n".to_string())
        + &"\n".to_string())
        + &"fn uses(y: LaterInLater) -> LaterInLater {\n".to_string())
        + &"  y\n".to_string())
        + &"}\n".to_string())
        + &"\n".to_string())
        + &"type LaterInLater\n".to_string())
        + &"  = LaterOne\n".to_string())
        + &"  | LaterTwo\n".to_string())
}

pub fn rdc_early_source() -> String {
    (((((((("module test.fixture.reference_derived_closure.early\n".to_string()
        + &"\n".to_string())
        + &"type EarlyOnly\n".to_string())
        + &"  = OnlyOne\n".to_string())
        + &"  | OnlyTwo\n".to_string())
        + &"\n".to_string())
        + &"fn uses(z: EarlyOnly) -> EarlyOnly {\n".to_string())
        + &"  z\n".to_string())
        + &"}\n".to_string())
}

pub fn rdc_early_consumer_source() -> String {
    (((("module test.fixture.reference_derived_closure.early_consumer\n".to_string()
        + &"\n".to_string())
        + &"fn reads(e: early.EarlyOnly) -> early.EarlyOnly {\n".to_string())
        + &"  e\n".to_string())
        + &"}\n".to_string())
}

pub fn rdc_later_consumer_source() -> String {
    (((("module test.fixture.reference_derived_closure.later_consumer\n".to_string()
        + &"\n".to_string())
        + &"fn reads(e: later.EarlyInLater) -> later.EarlyInLater {\n".to_string())
        + &"  e\n".to_string())
        + &"}\n".to_string())
}

pub fn rdc_consumer_source() -> String {
    (((("module test.fixture.reference_derived_closure.consumer\n".to_string()
        + &"\n".to_string())
        + &"fn reads(d: live_tree.LiveTreeDisposition) -> live_tree.LiveTreeDisposition {\n"
            .to_string())
        + &"  d\n".to_string())
        + &"}\n".to_string())
}

pub fn rdc_provider_source() -> String {
    (((("module v2.std.live_tree\n".to_string() + &"\n".to_string())
        + &"type LiveTreeDisposition\n".to_string())
        + &"  = ReadsLiveTree\n".to_string())
        + &"  | HermeticOnly\n".to_string())
}

pub fn rdc_second_provider_source() -> String {
    (((("module test.fixture.reference_derived_closure.live_tree\n".to_string()
        + &"\n".to_string())
        + &"type LiveTreeDisposition\n".to_string())
        + &"  = SecondOne\n".to_string())
        + &"  | SecondTwo\n".to_string())
}

pub fn rdc_unrelated_source() -> String {
    ((("module test.fixture.reference_derived_closure.unrelated\n".to_string()
        + &"\n".to_string())
        + &"type UnrelatedSubject\n".to_string())
        + &"  = OnlyOne\n".to_string())
}

pub fn rdc_source_for(path: String) -> Option<String> {
    match (path.clone() == rdc_consumer_path()) {
        true => Some(rdc_consumer_source()),
        false => match (path.clone() == rdc_provider_path()) {
            true => Some(rdc_provider_source()),
            false => match (path.clone() == rdc_second_provider_path()) {
                true => Some(rdc_second_provider_source()),
                false => match (path.clone() == rdc_unrelated_path()) {
                    true => Some(rdc_unrelated_source()),
                    false => match (path.clone() == rdc_later_path()) {
                        true => Some(rdc_later_source()),
                        false => match (path.clone() == rdc_later_consumer_path()) {
                            true => Some(rdc_later_consumer_source()),
                            false => match (path.clone() == rdc_early_path()) {
                                true => Some(rdc_early_source()),
                                false => match (path.clone() == rdc_early_consumer_path()) {
                                    true => Some(rdc_early_consumer_source()),
                                    false => None,
                                },
                            },
                        },
                    },
                },
            },
        },
    }
}

pub fn rdc_grounding_for(path: String) -> DeclarationExposureGrounding {
    DeclarationExposureGrounding::ModuleLocalMemberExposure
}

pub fn rdc_supply_for(path: String) -> Option<Rc<ParsedFileSupply>> {
    match rdc_source_for(path.clone()) {
        None => None,
        Some(source) => {
            match (*parse_authored_occurrence_binding_source(path.clone(), source.clone())).clone()
            {
                ParsedOccurrenceBindingSource::ParsedOccurrenceBindingSourceRefused => None,
                ParsedOccurrenceBindingSource::ParsedOccurrenceBindingSourceReady {
                    transport: t,
                    module_path,
                    ..
                } => Some(Rc::new(ParsedFileSupply {
                    file: path.clone(),
                    row: cross_file_binding_closure_row(
                        t.clone(),
                        occurrence_binding_inputs_from_transport(
                            module_path.clone(),
                            t.clone(),
                            rdc_grounding_for(path.clone()),
                        ),
                        module_path.clone(),
                        path.clone(),
                    ),
                })),
            }
        }
    }
}

pub fn rdc_no_supply() -> Rc<Vec<Rc<ParsedFileSupply>>> {
    Rc::new(vec![])
}

pub fn rdc_universe(paths: Rc<Vec<String>>) -> Rc<Vec<Rc<ParsedFileSupply>>> {
    paths.clone().iter().cloned().fold(
        rdc_no_supply(),
        |acc: Rc<Vec<Rc<ParsedFileSupply>>>, path: String| match rdc_supply_for(path.clone()) {
            None => acc.clone(),
            Some(row) => v1_rt::concat(acc.clone(), Rc::new(vec![row.clone()])),
        },
    )
}

pub fn rdc_step(entry: String, universe: Rc<Vec<String>>) -> Rc<ReferenceDerivedClosureStep> {
    reference_derived_closure_step(reference_derived_closure_initial(
        entry.clone(),
        rdc_universe(universe.clone()),
    ))
}

pub fn rdc_fixed_point(
    entry: String,
    universe: Rc<Vec<String>>,
) -> Rc<ReferenceDerivedClosureFixedPoint> {
    reference_derived_closure_fixed_point(entry.clone(), rdc_universe(universe.clone()))
}

pub fn rdc_ordinary_universe() -> Rc<Vec<String>> {
    Rc::new(vec![rdc_consumer_path(), rdc_provider_path()])
}

pub fn rdc_edges_name_provider(edges: Rc<Vec<Rc<DirectFileDependency>>>) -> bool {
    edges
        .clone()
        .iter()
        .cloned()
        .fold(false, |found: bool, e: Rc<DirectFileDependency>| {
            (found || (e.provider_file.clone() == rdc_provider_path()))
        })
}

pub fn rdc_files_contain(files: Rc<Vec<String>>, path: String) -> bool {
    files
        .clone()
        .iter()
        .cloned()
        .fold(false, |found: bool, f: String| {
            (found || (f.clone() == path.clone()))
        })
}

pub fn witness_consumer_alone_discovers_the_provider_file_as_pending() -> bool {
    match (*rdc_step(rdc_consumer_path(), rdc_ordinary_universe())).clone() {
        ReferenceDerivedClosureStep::ClosureStepAdvanced {
            state,
            newly_pending,
            edges,
            provenance,
            ..
        } => {
            ((((((((newly_pending.clone().len() as i64) == 1)
                && rdc_files_contain(newly_pending.clone(), rdc_provider_path()))
                && rdc_files_contain(state.admitted_files.clone(), rdc_consumer_path()))
                && ((state.admitted_files.clone().len() as i64) == 2))
                && ((edges.clone().len() as i64) == 1))
                && rdc_edges_name_provider(edges.clone()))
                && ((provenance.clone().len() as i64) >= 1))
        }
        _ => false,
    }
}

pub fn witness_second_step_over_the_advanced_state_settles() -> bool {
    match (*rdc_step(rdc_consumer_path(), rdc_ordinary_universe())).clone() {
        ReferenceDerivedClosureStep::ClosureStepAdvanced {
            state: advanced, ..
        } => match (*reference_derived_closure_step(advanced.clone())).clone() {
            ReferenceDerivedClosureStep::ClosureStepSettled { state, edges, .. } => {
                ((((state.admitted_files.clone().len() as i64) == 2)
                    && ((edges.clone().len() as i64) == 1))
                    && rdc_edges_name_provider(edges.clone()))
            }
            _ => false,
        },
        _ => false,
    }
}

pub fn witness_fixed_point_settles_in_two_iterations_over_two_files() -> bool {
    match (*rdc_fixed_point(rdc_consumer_path(), rdc_ordinary_universe())).clone() {
        ReferenceDerivedClosureFixedPoint::ClosureFixedPointSettled {
            admitted_files: admitted,
            edges,
            iterations,
            ..
        } => {
            ((((((iterations.clone() == 2) && ((admitted.clone().len() as i64) == 2))
                && rdc_files_contain(admitted.clone(), rdc_consumer_path()))
                && rdc_files_contain(admitted.clone(), rdc_provider_path()))
                && ((edges.clone().len() as i64) == 1))
                && rdc_edges_name_provider(edges.clone()))
        }
        _ => false,
    }
}

pub fn witness_mentions_keep_receipts_while_edges_dedupe_without_a_self_edge() -> bool {
    match (*rdc_fixed_point(rdc_consumer_path(), rdc_ordinary_universe())).clone() {
        ReferenceDerivedClosureFixedPoint::ClosureFixedPointSettled {
            edges, provenance, ..
        } => {
            (((((provenance.clone().len() as i64) == 3) && ((edges.clone().len() as i64) == 1))
                && edges.clone().iter().cloned().fold(
                    true,
                    |ok: bool, e: Rc<DirectFileDependency>| {
                        (ok && !(e.consumer_file.clone() == e.provider_file.clone()))
                    },
                ))
                && provenance.clone().iter().cloned().fold(
                    false,
                    |found: bool, row: Rc<CrossFileBindingProvenance>| {
                        (found || (row.consumer_file.clone() == row.provider_file.clone()))
                    },
                ))
        }
        _ => false,
    }
}

pub fn witness_provider_outside_the_universe_refuses_as_unbound() -> bool {
    match (*rdc_step(rdc_consumer_path(), Rc::new(vec![rdc_consumer_path()]))).clone() {
        ReferenceDerivedClosureStep::ClosureStepRefused {
            refusal: refusal, ..
        } => match (*refusal.clone()).clone() {
            ReferenceDerivedClosureRefusal::ClosureBindingRefused {
                population,
                first_failure_locus: locus,
                failure_count,
                ..
            } => match (*population.clone()).clone() {
                BoundReferencePopulation::ReferencePopulationRefused {
                    first_failure: failure,
                    ..
                } => {
                    ((((locus.authored_name.clone()
                        == "live_tree.LiveTreeDisposition".to_string())
                        && (locus.diagnostic_span.clone().start.clone() > 0))
                        && (failure_count.clone() >= 1))
                        && match (*failure.clone()).clone() {
                            ReferenceBindingProjection::ReferenceBindingProjectionUnbound {
                                occurrence: _,
                                ..
                            } => true,
                            _ => false,
                        })
                }
                _ => false,
            },
            _ => false,
        },
        _ => false,
    }
}

pub fn witness_entry_absent_from_the_universe_refuses() -> bool {
    match (*rdc_step(rdc_consumer_path(), Rc::new(vec![rdc_provider_path()]))).clone() {
        ReferenceDerivedClosureStep::ClosureStepRefused {
            refusal: refusal, ..
        } => match (*refusal.clone()).clone() {
            ReferenceDerivedClosureRefusal::ClosureNoEntryAdmitted => true,
            _ => false,
        },
        _ => false,
    }
}

pub fn witness_two_declaring_files_refuse_as_ambiguous_naming_both() -> bool {
    match (*rdc_step(
        rdc_consumer_path(),
        Rc::new(vec![
            rdc_consumer_path(),
            rdc_provider_path(),
            rdc_second_provider_path(),
        ]),
    ))
    .clone()
    {
        ReferenceDerivedClosureStep::ClosureStepRefused {
            refusal: refusal, ..
        } => match (*refusal.clone()).clone() {
            ReferenceDerivedClosureRefusal::ClosureBindingRefused {
                population,
                first_failure_locus: locus,
                failure_count,
                ..
            } => match (*population.clone()).clone() {
                BoundReferencePopulation::ReferencePopulationRefused {
                    first_failure: failure,
                    ..
                } => match (*failure.clone()).clone() {
                    ReferenceBindingProjection::ReferenceBindingProjectionAmbiguous {
                        candidates,
                        ..
                    } => {
                        (((locus.authored_name.clone()
                            == "live_tree.LiveTreeDisposition".to_string())
                            && (failure_count.clone() >= 1))
                            && !(candidates
                                .first
                                .clone()
                                .containment
                                .clone()
                                .terminal
                                .clone()
                                .value
                                .clone()
                                == candidates
                                    .second
                                    .clone()
                                    .containment
                                    .clone()
                                    .terminal
                                    .clone()
                                    .value
                                    .clone()))
                    }
                    _ => false,
                },
                _ => false,
            },
            _ => false,
        },
        _ => false,
    }
}

pub fn witness_unreferenced_universe_file_is_not_admitted() -> bool {
    match (*rdc_fixed_point(
        rdc_consumer_path(),
        Rc::new(vec![
            rdc_consumer_path(),
            rdc_provider_path(),
            rdc_unrelated_path(),
        ]),
    ))
    .clone()
    {
        ReferenceDerivedClosureFixedPoint::ClosureFixedPointSettled {
            admitted_files: admitted,
            edges,
            ..
        } => {
            ((((admitted.clone().len() as i64) == 2)
                && !rdc_files_contain(admitted.clone(), rdc_unrelated_path()))
                && ((edges.clone().len() as i64) == 1))
        }
        _ => false,
    }
}

pub fn rdc_binding_refusal_locus(
    outcome: Rc<ReferenceDerivedClosureFixedPoint>,
) -> Option<Rc<OccurrenceProjection>> {
    match (*outcome.clone()).clone() {
        ReferenceDerivedClosureFixedPoint::ClosureFixedPointRefused { refusal, .. } => {
            match (*refusal.clone()).clone() {
                ReferenceDerivedClosureRefusal::ClosureBindingRefused {
                    first_failure_locus: locus,
                    ..
                } => Some(locus.clone()),
                _ => None,
            }
        }
        _ => None,
    }
}

pub fn witness_later_declaration_refuses_identically_under_both_entries() -> bool {
    {
        let universe = Rc::new(vec![rdc_later_consumer_path(), rdc_later_path()]);
        match rdc_binding_refusal_locus(rdc_fixed_point(rdc_later_path(), universe.clone())) {
            None => false,
            Some(as_entry) => match rdc_binding_refusal_locus(rdc_fixed_point(
                rdc_later_consumer_path(),
                universe.clone(),
            )) {
                None => false,
                Some(as_provider) => {
                    ((((as_entry.authored_name.clone() == "LaterInLater".to_string())
                        && (as_provider.authored_name.clone() == as_entry.authored_name.clone()))
                        && (as_provider.diagnostic_span.clone().start.clone()
                            == as_entry.diagnostic_span.clone().start.clone()))
                        && (as_provider.diagnostic_span.clone().end.clone()
                            == as_entry.diagnostic_span.clone().end.clone()))
                }
            },
        }
    }
}

pub fn witness_earlier_declaration_binds_under_both_entries() -> bool {
    {
        let universe = Rc::new(vec![rdc_early_consumer_path(), rdc_early_path()]);
        match (*rdc_fixed_point(rdc_early_path(), universe.clone())).clone() {
            ReferenceDerivedClosureFixedPoint::ClosureFixedPointSettled {
                admitted_files: alone,
                ..
            } => match (*rdc_fixed_point(rdc_early_consumer_path(), universe.clone())).clone() {
                ReferenceDerivedClosureFixedPoint::ClosureFixedPointSettled {
                    admitted_files: reached,
                    ..
                } => {
                    (((rdc_files_contain(alone.clone(), rdc_early_path())
                        && !rdc_files_contain(alone.clone(), rdc_early_consumer_path()))
                        && rdc_files_contain(reached.clone(), rdc_early_path()))
                        && rdc_files_contain(reached.clone(), rdc_early_consumer_path()))
                }
                _ => false,
            },
            _ => false,
        }
    }
}
