// Generated by v1 compiler -- do not edit.
// Source module: v1.tests.claim.caret_parse_smoke_test

pub use crate::v1_compiler_artifact::RenderTarget;
use crate::v1_compiler_artifact::RenderTarget::Rust;
pub use crate::v1_compiler_compile::SourceFile;
pub use crate::v1_compiler_compile::{compile_sources, compile_to_resolved};
pub use crate::v1_compiler_dag_collect_support::expr_data_variant;
pub use crate::v1_compiler_parse::{parse_caret_expr, parse_expr, parse_module, token_stream_new};
pub use crate::v1_compiler_parse::{ParseContext, TokenStream};
pub use crate::v1_compiler_tokenize::tokenize;
use crate::v1_rt;
use crate::v1_rt::{VecCompat, VecJoin};
use crate::v1_std_core::TokenShape::{ShCaret, ShEof, ShIdent, ShLParen};
pub use crate::v1_std_core::{
    diagnostic_to_message, empty_intern_table, expr_call_func_at, is_error_diagnostic,
};
pub use crate::v1_std_core::{ErrorNode, NewlineIndex, Node, TokenShape};
use crate::NonEmptyBTreeSet;
use crate::NonEmptyVec;
use im::{vector as vec, HashMap, OrdSet as BTreeSet, Vector as Vec};
use std::rc::Rc;

pub fn caret_parse_smoke_parser_transport_enrollment() -> String {
    thread_local! {
        static CACHED: String = {
            "Scheduled per PR through gunbc.ci_layer_roots v1_claim_scoped_witness_entries and v1_claim_scoped_witness_batch, enrolled by scoped_witness_batches; v2.workflow.ci_floor_plan gunbc_ci_floor_ordinary_batches folds those generic instances into the floor. The scoped batch supplies exactly dag plus src/v1 without widening ordinary witness discovery. Local reproduction: target/release/claim_batch --source-root dag --source-root src/v1 --entry src/v1/tests/claim/caret_parse_smoke_test.dag --functions w_caret_tokenizes_as_sh_caret,w_caret_paren_tokenizes_as_caret_then_lparen,w_parse_caret_ident_produces_literal,w_parse_caret_paren_produces_discriminant_call,w_parse_expr_caret_paren_full_pipeline,w_parse_expr_caret_var_arg_produces_discriminant_call,w_parse_module_let_caret_paren. The native compile and emit claims remain on cargo test -p v1-compiler --lib caret_parse_smoke_native_compile_emit_witnesses until v1.compile_sources is interpreter-runnable (same map_keys gap as probe_emit_interp.dag).".to_string()
        };
    }
    CACHED.with(|c: &String| c.clone())
}

pub fn caret_parse_ctx() -> Rc<ParseContext> {
    {
        let empty = v1_rt::rc_empty_map::<String, Rc<NewlineIndex>>();
        Rc::new(ParseContext {
            source_indices: empty.clone(),
            intern_table: empty_intern_table(),
            occurrence_allocator: None,
            occurrence_index: None,
            declaration_occurrences: None,
            reference_occurrences: None,
        })
    }
}

pub fn caret_probe5b_source() -> String {
    v1_rt::concat(
        "module caret.probe5b\n\n".to_string(),
        v1_rt::concat(
            "fn probe() -> Bool {\n".to_string(),
            v1_rt::concat(
                "  let sugar = ^(1)\n".to_string(),
                v1_rt::concat("  true\n".to_string(), "}\n".to_string()),
            ),
        ),
    )
}

pub fn caret_emit_tag_source() -> String {
    v1_rt::concat(
        "module caret.emit_tag\n\n".to_string(),
        v1_rt::concat(
            "fn caret_tag() -> Bool {\n".to_string(),
            v1_rt::concat(
                "  let t = ^caret_emit_tag\n".to_string(),
                v1_rt::concat("  t == ^caret_emit_tag\n".to_string(), "}\n".to_string()),
            ),
        ),
    )
}

pub fn caret_emit_disc_source() -> String {
    v1_rt::concat(
        "module caret.emit_disc\n\n".to_string(),
        v1_rt::concat(
            "type CaretShape\n".to_string(),
            v1_rt::concat(
                "  = CaretAlpha { x: Int }\n\n".to_string(),
                v1_rt::concat(
                    "fn caret_disc() -> String {\n".to_string(),
                    v1_rt::concat(
                        "  let v = CaretAlpha { x: 1 }\n".to_string(),
                        v1_rt::concat("  discriminant(v: ^(v))\n".to_string(), "}\n".to_string()),
                    ),
                ),
            ),
        ),
    )
}

pub fn caret_source_file(path: String, content: String) -> Rc<SourceFile> {
    Rc::new(SourceFile {
        path: path.clone(),
        content: content.clone(),
    })
}

pub fn caret_compile_rust_emitted(source: Rc<SourceFile>) -> String {
    {
        let result = compile_sources(Rc::new(vec![source.clone()]), RenderTarget::Rust);
        Rc::new({
            let mut __result = Vec::new();
            for f in result.files.clone().iter().cloned() {
                __result.push(f.content.clone());
            }
            __result
        })
        .join(&"\n".to_string())
    }
}

pub fn caret_compile_rust_has_no_errors(source: Rc<SourceFile>) -> bool {
    {
        let result = compile_sources(Rc::new(vec![source.clone()]), RenderTarget::Rust);
        ({
            let mut __found = false;
            for d in result.diagnostics.clone().iter().cloned() {
                if is_error_diagnostic(d.diagnostic.clone()) {
                    __found = true;
                    break;
                }
            }
            __found
        } == false)
    }
}

pub fn caret_diagnostics_contain_pattern(
    diagnostics: Rc<Vec<Rc<ErrorNode>>>,
    pattern: String,
) -> bool {
    {
        let mut __found = false;
        for d in diagnostics.clone().iter().cloned() {
            if v1_rt::contains(diagnostic_to_message(d.diagnostic.clone()), pattern.clone()) {
                __found = true;
                break;
            }
        }
        __found
    }
}

pub fn caret_token_stream_only_eof_remains(stream: Rc<TokenStream>) -> bool {
    {
        let remaining = Rc::new(
            stream
                .all
                .clone()
                .iter()
                .cloned()
                .skip(stream.pos.clone() as usize)
                .collect::<Vec<_>>(),
        );
        {
            let mut __all = true;
            for t in remaining.clone().iter().cloned() {
                if !(t.shape.clone() == TokenShape::ShEof) {
                    __all = false;
                    break;
                }
            }
            __all
        }
    }
}

pub fn caret_expr_is_symbol_literal(expr: Rc<Node>) -> bool {
    (expr_data_variant(expr.expr_data.clone()) == "ExprLiteral".to_string())
}

pub fn caret_expr_is_discriminant_call(expr: Rc<Node>) -> bool {
    ((expr_data_variant(expr.expr_data.clone()) == "ExprCall".to_string())
        && (expr_call_func_at(
            expr.clone(),
            v1_rt::rc_empty_map::<String, Rc<NewlineIndex>>(),
        ) == "discriminant".to_string()))
}

pub fn w_caret_tokenizes_as_sh_caret() -> bool {
    {
        let tokens = tokenize("^foo".to_string(), "test.dag".to_string());
        match tokens.clone().first().cloned() {
            Some(t1) => match tokens.clone().iter().cloned().skip(1 as usize).next() {
                Some(t2) => {
                    ((t1.shape.clone() == TokenShape::ShCaret)
                        && (t2.shape.clone() == TokenShape::ShIdent))
                }
                None => false,
            },
            None => false,
        }
    }
}

pub fn w_caret_paren_tokenizes_as_caret_then_lparen() -> bool {
    {
        let tokens = tokenize("^(alpha)".to_string(), "test.dag".to_string());
        match tokens.clone().first().cloned() {
            Some(t1) => match tokens.clone().iter().cloned().skip(1 as usize).next() {
                Some(t2) => {
                    ((t1.shape.clone() == TokenShape::ShCaret)
                        && (t2.shape.clone() == TokenShape::ShLParen))
                }
                None => false,
            },
            None => false,
        }
    }
}

pub fn w_parse_caret_ident_produces_literal() -> bool {
    {
        let tokens = tokenize("^foo_tag".to_string(), "test.dag".to_string());
        let r = parse_caret_expr(token_stream_new(tokens.clone()), caret_parse_ctx());
        ((r.err.clone() == None) && caret_expr_is_symbol_literal(r.expr.clone()))
    }
}

pub fn w_parse_caret_paren_produces_discriminant_call() -> bool {
    {
        let tokens = tokenize("^(alpha)".to_string(), "test.dag".to_string());
        let r = parse_caret_expr(token_stream_new(tokens.clone()), caret_parse_ctx());
        ((r.err.clone() == None) && caret_expr_is_discriminant_call(r.expr.clone()))
    }
}

pub fn w_parse_expr_caret_paren_full_pipeline() -> bool {
    {
        let tokens = tokenize("^(alpha)".to_string(), "test.dag".to_string());
        let r = parse_expr(token_stream_new(tokens.clone()), caret_parse_ctx());
        (((r.err.clone() == None) && caret_token_stream_only_eof_remains(r.tokens.clone()))
            && caret_expr_is_discriminant_call(r.expr.clone()))
    }
}

pub fn w_parse_expr_caret_var_arg_produces_discriminant_call() -> bool {
    {
        let tokens = tokenize("^(alpha)".to_string(), "test.dag".to_string());
        let r = parse_expr(token_stream_new(tokens.clone()), caret_parse_ctx());
        ((r.err.clone() == None) && caret_expr_is_discriminant_call(r.expr.clone()))
    }
}

pub fn w_parse_module_let_caret_paren() -> bool {
    {
        let tokens = tokenize(caret_probe5b_source(), "caret_probe5b.dag".to_string());
        let r = parse_module(token_stream_new(tokens.clone()), caret_parse_ctx());
        (r.err.clone() == None)
    }
}

pub fn w_compile_to_resolved_caret_probe5b_has_no_caret_function_error() -> bool {
    {
        let result = compile_to_resolved(Rc::new(vec![caret_source_file(
            "caret_probe5b.dag".to_string(),
            caret_probe5b_source(),
        )]));
        (caret_diagnostics_contain_pattern(result.diagnostics.clone(), "function '^'".to_string())
            == false)
    }
}

pub fn w_emit_caret_ident_symbol_literal() -> bool {
    {
        let source = caret_source_file("caret_emit_tag.dag".to_string(), caret_emit_tag_source());
        (caret_compile_rust_has_no_errors(source.clone())
            && v1_rt::contains(
                caret_compile_rust_emitted(source.clone()),
                "\"caret_emit_tag\"".to_string(),
            ))
    }
}

pub fn w_emit_caret_paren_discriminant_sugar() -> bool {
    {
        let source = caret_source_file("caret_emit_disc.dag".to_string(), caret_emit_disc_source());
        (((caret_compile_rust_has_no_errors(source.clone())
            && v1_rt::contains(
                caret_compile_rust_emitted(source.clone()),
                "CaretAlpha".to_string(),
            ))
            && (caret_diagnostics_contain_pattern(
                compile_sources(Rc::new(vec![source.clone()]), RenderTarget::Rust)
                    .diagnostics
                    .clone(),
                "function '^'".to_string(),
            ) == false))
            && (v1_rt::contains(
                caret_compile_rust_emitted(source.clone()),
                "compile_error".to_string(),
            ) == false))
    }
}
