// Build script: enumerate every `*.dag` file in `src/v3/spec/` and
// generate a Rust array of `(path, content)` pairs the bootstrap
// loader consumes. Adding a new per-target language spec file
// (e.g. `python.dag`) becomes a pure file-system change — no
// Rust edits to `bootstrap.rs`, no fixture-array maintenance.
//
// **Why a build script.** The pre-unwind shape used hardcoded
// `const RUST_DAG: &str = include_str!("../../spec/rust.dag");`
// constants in `bootstrap.rs`. PR #445 review flagged this as a
// duplicate-authority bug: the on-disk spec files and the Rust
// fixture array are two parallel representations of the same set,
// and adding a new target requires editing both. This script
// removes the parallel representation by deriving the array from
// the spec directory.
//
// **Load order.** The v3 lowerer doesn't strictly enforce import
// resolution at M1(3), but later spec files that reference
// declarations from earlier ones (e.g. rust.dag importing v3_l1's
// `Bind` marker) must follow them in load order. The script
// hardcodes one rule: `v3_l1.dag` (the substrate marker file)
// loads first; everything else follows in alphabetical order. The
// rule is the only special case because v3_l1 is the file every
// per-target spec depends on. If a future spec file introduces a
// dependency that needs sorting, this script grows a topological
// pass; until then, the simple rule is sufficient.
//
// **Output**: writes a Rust file `OUT_DIR/v3_specs.rs` containing:
//
//   pub static V3_SPECS: &[(&str, &str)] = &[
//       ("src/v3/spec/v3_l1.dag", include_str!("...")),
//       ("src/v3/spec/rust.dag",  include_str!("...")),
//   ];
//
// `bootstrap.rs` uses `include!(concat!(env!("OUT_DIR"),
// "/v3_specs.rs"));` to pull the array in. The `include_str!`
// calls inside the generated file resolve at compile time against
// absolute paths, so the runtime is still hermetic — no
// filesystem access at `Dag::new()` time.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Resolve the spec directory relative to CARGO_MANIFEST_DIR
    // (which points at src/v3/compiler/). The spec dir is
    // src/v3/spec/, two levels up and across.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by Cargo");
    let manifest_path = PathBuf::from(&manifest_dir);
    // src/v3/compiler → src/v3/spec
    let spec_dir = manifest_path
        .parent()
        .expect("compiler dir has parent")
        .join("spec");

    // Tell Cargo to re-run the script if any file in the spec dir
    // changes. Without this, adding a new spec file wouldn't
    // trigger a rebuild and the loader would silently miss it.
    println!(
        "cargo:rerun-if-changed={}",
        spec_dir.display()
    );

    let mut entries: Vec<PathBuf> = fs::read_dir(&spec_dir)
        .unwrap_or_else(|e| {
            panic!("failed to read spec dir {}: {}", spec_dir.display(), e)
        })
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("dag"))
        .collect();

    // Special-case load order: v3_l1.dag first (it declares the
    // substrate markers every per-target spec file imports),
    // everything else alphabetically. This is a one-line bias,
    // not a full topological sort — keeps the script simple while
    // still producing a deterministic, dependency-respecting load
    // order for the current spec set.
    entries.sort_by(|a, b| {
        let a_name = a.file_name().and_then(|s| s.to_str()).unwrap_or("");
        let b_name = b.file_name().and_then(|s| s.to_str()).unwrap_or("");
        let key = |name: &str| -> (u8, String) {
            if name == "v3_l1.dag" {
                (0, name.to_string())
            } else {
                (1, name.to_string())
            }
        };
        key(a_name).cmp(&key(b_name))
    });

    // Generate the Rust source. Each entry becomes a
    // `(path_string, include_str!(absolute_path))` tuple. The
    // path string is the project-relative path used for
    // diagnostic spans (e.g. "src/v3/spec/rust.dag"); the
    // `include_str!` argument is an absolute path so the macro
    // resolves regardless of where the generated file lands.
    let mut generated = String::from(
        "// AUTO-GENERATED by build.rs. Do not edit.\n\
         //\n\
         // Spec files enumerated from src/v3/spec/*.dag. Adding a\n\
         // new per-target language spec is a pure file-system\n\
         // change — drop the .dag file in src/v3/spec/ and the\n\
         // build script picks it up at the next compile.\n\
         pub static V3_SPECS: &[(&str, &str)] = &[\n",
    );
    for path in &entries {
        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .expect("entry has utf-8 file name");
        let display_path = format!("src/v3/spec/{}", file_name);
        let abs_path = path.canonicalize().unwrap_or_else(|e| {
            panic!("failed to canonicalize {}: {}", path.display(), e)
        });
        generated.push_str(&format!(
            "    (\"{}\", include_str!(\"{}\")),\n",
            display_path,
            abs_path.display()
        ));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by Cargo");
    let out_path = Path::new(&out_dir).join("v3_specs.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", out_path.display(), e));
}
