// Build script: enumerate every `*.dag` file in the v3-only staged
// directories and generate Rust arrays of `(path, content)` pairs
// the bootstrap loader consumes.
//
// Three generated arrays exist:
//   - `STAGED_FILES`   for `src/v3/std/*.dag`
//   - `V3_SPECS`       for `src/v3/spec/*.dag`
//   - `COMPILER_FILES` for `src/v3/compiler/*.dag` (except `tokenize.dag`; see below)
//
// Adding a new staged std/spec/compiler file becomes a pure file-system
// change — no Rust edits to `bootstrap.rs`, no fixture-array
// maintenance, no skip-list drift.
//
// **Why a build script.** The pre-unwind shape used hardcoded
// `const RUST_DAG: &str = include_str!("../../spec/rust.dag");`
// constants in `bootstrap.rs`. PR #445 review flagged this as a
// duplicate-authority bug: the on-disk spec files and the Rust
// fixture array are two parallel representations of the same set,
// and adding a new target requires editing both. This script
// removes the parallel representation by deriving the arrays from
// the staged directories.
//
// **Load order.** The v3 lowerer doesn't strictly enforce import
// resolution at M1(3), but later spec files that reference
// declarations from earlier ones (e.g. rust.dag importing v3_l1's
// `Bind` marker) must follow them in load order. The script
// hardcodes one rule: `v3_l1.dag` (the substrate marker file)
// loads first; everything else follows in alphabetical order. The
// rule is the only special case because v3_l1 is the file every
// per-target spec depends on. If a future spec file introduces a
// dependency that needs sorting, this script grows a topological
// pass; until then, the simple rule is sufficient.
//
// **Output**: writes three Rust files:
//
//   pub static STAGED_FILES: &[(&str, &str)] = &[
//       ("src/v3/std/list.dag", include_str!("...")),
//   ];
//
//   pub static V3_SPECS: &[(&str, &str)] = &[
//       ("src/v3/spec/v3_l1.dag", include_str!("...")),
//       ("src/v3/spec/rust.dag",  include_str!("...")),
//   ];
//
//   pub static COMPILER_FILES: &[(&str, &str)] = &[
//       ("src/v3/compiler/pipeline.dag", include_str!("...")),
//   ];
//   `tokenize.dag` is intentionally omitted: it is tokenizer authority for
//   `regen_tokenize` and must not be folded into the bootstrap Dag (duplicate
//   declarations when `compile_to_dag` parses it).
//
// `bootstrap.rs` uses `include!(concat!(env!("OUT_DIR"), ...))` to
// pull the arrays in. The `include_str!` calls inside the generated
// files resolve at compile time against absolute paths, so the
// runtime is still hermetic — no filesystem access at `Dag::new()`
// time.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn collect_dag_entries(dir: &Path, prioritized: &[&str]) -> Vec<PathBuf> {
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", dir.display(), e))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("dag"))
        .collect();

    entries.sort_by(|a, b| {
        let a_name = a.file_name().and_then(|s| s.to_str()).unwrap_or("");
        let b_name = b.file_name().and_then(|s| s.to_str()).unwrap_or("");
        let priority_key = |name: &str| -> (usize, String) {
            let rank = prioritized
                .iter()
                .position(|candidate| *candidate == name)
                .unwrap_or(prioritized.len());
            (rank, name.to_string())
        };
        priority_key(a_name).cmp(&priority_key(b_name))
    });

    entries
}

fn generate_static(
    static_name: &str,
    dir_label: &str,
    display_prefix: &str,
    entries: &[PathBuf],
) -> String {
    let mut generated = format!(
        "// AUTO-GENERATED by build.rs. Do not edit.\n\
         //\n\
         // Files enumerated from {dir_label}/*.dag. Adding a new\n\
         // staged file is a pure file-system change.\n\
         pub static {static_name}: &[(&str, &str)] = &[\n"
    );
    for path in entries {
        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .expect("entry has utf-8 file name");
        let display_path = format!("{display_prefix}/{file_name}");
        let abs_path = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("failed to canonicalize {}: {}", path.display(), e));
        generated.push_str(&format!(
            "    (\"{}\", include_str!(\"{}\")),\n",
            display_path,
            abs_path.display()
        ));
    }
    generated.push_str("];\n");
    generated
}

fn main() {
    // Resolve the staged directories relative to CARGO_MANIFEST_DIR
    // (which points at src/v3/compiler/). std/ and spec/ live one
    // level up; compiler-staged files live in the manifest dir itself.
    let manifest_dir =
        env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set by Cargo");
    let manifest_path = PathBuf::from(&manifest_dir);
    let v3_dir = manifest_path.parent().expect("compiler dir has parent");
    let std_dir = v3_dir.join("std");
    let spec_dir = v3_dir.join("spec");
    let compiler_dir = manifest_path.clone();

    // Tell Cargo to re-run the script if any staged std/spec/compiler file
    // changes. Without this, adding a new file wouldn't trigger a
    // rebuild and bootstrap would silently miss it.
    println!("cargo:rerun-if-changed={}", std_dir.display());
    println!("cargo:rerun-if-changed={}", spec_dir.display());
    println!("cargo:rerun-if-changed={}", compiler_dir.display());

    // Structural-recursion termination analysis walks a recursing
    // argument back to its declared Disj connective (see
    // `structural_binding_info_for_variant` in `lower.rs`). The walk
    // only succeeds after the declaring file has been phase-2 lowered,
    // so `std/list.dag` (declares `List<element> = Empty | Cons {...}`)
    // and `std/substrate.dag` (declares `Behavior = Value | Transform
    // | Branch | Loop | Bind`) must land before any sibling std file
    // that recursively descends over those variants. Without this
    // priority list, alphabetical order puts `algebra.dag` and
    // `dimensions.dag` ahead of `list.dag`/`substrate.dag`, and their
    // recursive helpers fail termination against placeholder
    // connectives.
    // `substrate_minimal` + `effects` before full `substrate` so `substrate.dag`
    // can import `WorkflowEffect` for reflected `lane2_workflow` without a
    // module cycle (`effects` still needs `PortId` / list primitives first).
    let staged_entries = collect_dag_entries(
        &std_dir,
        &[
            "list.dag",
            "substrate_minimal.dag",
            "effects.dag",
            "substrate.dag",
        ],
    );
    let spec_entries = collect_dag_entries(&spec_dir, &["v3_l1.dag"]);
    let mut compiler_entries = collect_dag_entries(&compiler_dir, &["pipeline.dag"]);
    // `tokenize.dag` is SG-1 tokenizer authority consumed by `regen_tokenize`; it is not part
    // of the runtime bootstrap Dag (would duplicate declarations when `compile_to_dag` parses it).
    compiler_entries.retain(|p| {
        p.file_name()
            .and_then(|s| s.to_str())
            .map(|n| n != "tokenize.dag")
            .unwrap_or(true)
    });
    let staged_generated =
        generate_static("STAGED_FILES", "src/v3/std", "src/v3/std", &staged_entries);
    let specs_generated = generate_static("V3_SPECS", "src/v3/spec", "src/v3/spec", &spec_entries);
    let compiler_generated = generate_static(
        "COMPILER_FILES",
        "src/v3/compiler",
        "src/v3/compiler",
        &compiler_entries,
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by Cargo");
    let out_dir = Path::new(&out_dir);
    let staged_out = out_dir.join("v3_staged_files.rs");
    fs::write(&staged_out, staged_generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", staged_out.display(), e));
    let specs_out = out_dir.join("v3_specs.rs");
    fs::write(&specs_out, specs_generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", specs_out.display(), e));
    let compiler_out = out_dir.join("v3_compiler_files.rs");
    fs::write(&compiler_out, compiler_generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", compiler_out.display(), e));

    // SG-0 producer-owned generated manifest. The census at
    // `tests/integration/sg0_census_test.rs` reads this list as the
    // sole authority for "which .rs files under src/v3/compiler are
    // generated." Every codegen driver (the `regen_*` binaries plus
    // the ignored `emit_lens_provenance_snapshot` test) imports the
    // same manifest and asserts its output path is in it before
    // writing — so a typo in a regen output path fails loud rather
    // than silently writing to an uncounted path.
    //
    // The manifest lives only in OUT_DIR — it is ephemeral,
    // reconstructed every build from this list. A hand-edited
    // manifest file is clobbered on the next `cargo build`; the
    // spoof surface collapses to this `REGEN_OUTPUTS` literal,
    // reviewed alongside any real producer change.
    //
    // Paths are workspace-relative and sorted for determinism. They
    // match exactly what the regen drivers write to disk as
    // committed Rust.
    const REGEN_OUTPUTS: &[&str] = &[
        "src/v3/compiler/src/dag_branch_generated.rs",
        "src/v3/compiler/src/dag_cluster_generated.rs",
        "src/v3/compiler/src/dag_cost_generated.rs",
        "src/v3/compiler/src/dag_scalar_generated.rs",
        "src/v3/compiler/src/diagnostics_generated.rs",
        "src/v3/compiler/src/infer_helpers_generated.rs",
        "src/v3/compiler/src/lens_cost_generated.rs",
        "src/v3/compiler/src/lens_cost_symbolic_generated.rs",
        "src/v3/compiler/src/lens_provenance_generated.rs",
        "src/v3/compiler/src/lens_structural_resolution_generated.rs",
        "src/v3/compiler/src/lens_unused_parameters_generated.rs",
        "src/v3/compiler/src/serialize_generated.rs",
        "src/v3/compiler/src/types_generated.rs",
    ];
    let mut manifest = String::from(
        "// AUTO-GENERATED by build.rs. Do not edit.\n\
         //\n\
         // Paths (workspace-relative) of every .rs file under\n\
         // src/v3/compiler that is produced by a codegen authority\n\
         // (regen_* binaries today; build.rs-driven include_str!\n\
         // projections if that surface ever grows into src/).\n\
         pub static GENERATED_FILES: &[&str] = &[\n",
    );
    for path in REGEN_OUTPUTS {
        manifest.push_str(&format!("    \"{path}\",\n"));
    }
    manifest.push_str("];\n");
    let manifest_out = out_dir.join("v3_generated_files.rs");
    fs::write(&manifest_out, manifest)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", manifest_out.display(), e));
}
