#!/usr/bin/env python3
"""Doc-reference resolver + doc-chain diagram — enforcement for the doc authority rule.

Two jobs, both derived from the *actual* Markdown links (no hand-maintained map):

1. RESOLVE — every Markdown link to a repo-relative path must resolve to a file that
   exists. This is the standing detection that keeps the doc tree from silently
   re-accreting dangling references — the failure mode that left doc-authority.md
   itself citing a ROADMAP structure that no longer exists.

2. GRAPH — render the doc *chain* (which doc references which) as a Mermaid diagram,
   computed from the real links, and embed it in docs/thesis/doc-authority.md between
   markers. The diagram is generated, never hand-drawn, so the "actual chain" shown
   next to the declared authority DAG can be checked against reality (`--check-graph`).

Usage:
  check_doc_refs.py --all                 # resolve: scan every tracked .md (census)
  check_doc_refs.py FILE [FILE ...]       # resolve: scan specific files
  check_doc_refs.py --changed BASE        # resolve: scan .md changed vs BASE (CI: --changed origin/main)
  check_doc_refs.py --graph               # print the doc-chain Mermaid block to stdout
  check_doc_refs.py --write-graph         # regenerate the embedded block in doc-authority.md
  check_doc_refs.py --check-graph         # fail if the embedded block is stale (CI drift gate)

Exit 0 on success; 1 on any dangling reference / stale embedded graph.

Graph scope: root-level .md + docs/**.md (the doc tree proper; component-local
READMEs under src/ and dsl/ are excluded as noise). Only doc->doc edges are drawn —
an A->B edge means "A links to B" (A defers to / cites B). Determinism (sorted nodes
and edges) is required so --check-graph is a stable byte comparison.
"""
import os
import re
import subprocess
import sys

# [text](target) and ![alt](target). Capture the target up to the first ) or space.
LINK_RE = re.compile(r"!?\[[^\]]*\]\(\s*([^)\s]+)")
SKIP_PREFIXES = ("http://", "https://", "mailto:", "#", "tel:")

AUTHORITY_DOC = "docs/thesis/doc-authority.md"
BEGIN = "<!-- BEGIN doc-chain (generated by `scripts/check_doc_refs.py --write-graph`; do not hand-edit) -->"
END = "<!-- END doc-chain -->"


def repo_root() -> str:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True,
    )
    return out.stdout.strip()


def tracked_md(root: str) -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "*.md"],
        capture_output=True, text=True, check=True, cwd=root,
    )
    files = [f for f in out.stdout.splitlines() if f]
    return [f for f in files if not f.startswith(("target/", "node_modules/"))]


def changed_md(root: str, base: str) -> list[str]:
    out = subprocess.run(
        ["git", "diff", "--name-only", "--diff-filter=d", f"{base}...HEAD"],
        capture_output=True, text=True, check=True, cwd=root,
    )
    return [f for f in out.stdout.splitlines() if f.endswith(".md")]


def iter_links(root: str, relpath: str):
    """Yield (line_no, raw_target, resolved_repo_relpath) for each repo-relative link."""
    base_dir = os.path.dirname(relpath)
    with open(os.path.join(root, relpath), encoding="utf-8") as fh:
        for line_no, line in enumerate(fh, 1):
            for raw in LINK_RE.findall(line):
                target = raw.split("#", 1)[0]  # drop anchor
                if not target or target.startswith(SKIP_PREFIXES):
                    continue
                resolved = os.path.normpath(os.path.join(base_dir, target))
                yield line_no, target, resolved


def dangling_in_file(root: str, relpath: str) -> list[tuple[int, str]]:
    out = []
    for line_no, target, resolved in iter_links(root, relpath):
        if not os.path.exists(os.path.join(root, resolved)):
            out.append((line_no, target))
    return out


def resolve(root: str, files: list[str]) -> int:
    total = 0
    for relpath in files:
        for line_no, target in dangling_in_file(root, relpath):
            print(f"{relpath}:{line_no}: dangling reference -> {target}")
            total += 1
    n = len(files)
    if total:
        print(f"\nFAIL: {total} dangling reference(s) across {n} file(s).", file=sys.stderr)
        return 1
    print(f"OK: all references resolve across {n} file(s).")
    return 0


# --- doc-chain graph -------------------------------------------------------

def graph_files(root: str) -> set[str]:
    """Root-level .md + docs/**.md — the doc tree proper (excl. src/, dsl/ READMEs)."""
    return {
        f for f in tracked_md(root)
        if "/" not in f or f.startswith("docs/")
    }


def doc_chain_edges(root: str) -> list[tuple[str, str]]:
    files = graph_files(root)
    edges = set()
    for src in files:
        for _, _, resolved in iter_links(root, src):
            if resolved in files and resolved != src:
                edges.add((src, resolved))
    return sorted(edges)


def _node_id(path: str) -> str:
    return "d_" + re.sub(r"[^0-9a-zA-Z]", "_", path)


def _area(path: str) -> str:
    if "/" not in path:
        return "(root)"
    parts = path.split("/")
    return "/".join(parts[:-1]) if len(parts) > 2 else parts[0]


def render_mermaid(root: str) -> str:
    edges = doc_chain_edges(root)
    nodes = sorted({n for e in edges for n in e})
    areas: dict[str, list[str]] = {}
    for n in nodes:
        areas.setdefault(_area(n), []).append(n)
    lines = ["```mermaid", "flowchart LR"]
    for area in sorted(areas):
        lines.append(f'  subgraph area_{re.sub(r"[^0-9a-zA-Z]", "_", area)}["{area}"]')
        for n in sorted(areas[area]):
            lines.append(f'    {_node_id(n)}["{n}"]')
        lines.append("  end")
    for src, dst in edges:
        lines.append(f"  {_node_id(src)} --> {_node_id(dst)}")
    lines.append("```")
    return "\n".join(lines)


def _generated_region(root: str) -> str:
    return f"{BEGIN}\n\n{render_mermaid(root)}\n\n{END}"


def _region_re() -> "re.Pattern[str]":
    return re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)


def write_graph(root: str) -> int:
    path = os.path.join(root, AUTHORITY_DOC)
    content = open(path, encoding="utf-8").read()
    if not _region_re().search(content):
        print(f"ERROR: doc-chain markers not found in {AUTHORITY_DOC}; add the "
              f"BEGIN/END markers first.", file=sys.stderr)
        return 2
    content = _region_re().sub(lambda _: _generated_region(root), content)
    open(path, "w", encoding="utf-8").write(content)
    print(f"OK: regenerated doc-chain in {AUTHORITY_DOC}.")
    return 0


def check_graph(root: str) -> int:
    path = os.path.join(root, AUTHORITY_DOC)
    content = open(path, encoding="utf-8").read()
    m = _region_re().search(content)
    if not m:
        print(f"ERROR: doc-chain markers not found in {AUTHORITY_DOC}.", file=sys.stderr)
        return 2
    if m.group(0).strip() != _generated_region(root).strip():
        print(f"FAIL: embedded doc-chain in {AUTHORITY_DOC} is stale. "
              f"Run: python3 scripts/check_doc_refs.py --write-graph", file=sys.stderr)
        return 1
    print(f"OK: embedded doc-chain in {AUTHORITY_DOC} is current.")
    return 0


def main(argv: list[str]) -> int:
    root = repo_root()
    if not argv:
        print(__doc__)
        return 2
    mode = argv[0]
    if mode == "--all":
        return resolve(root, tracked_md(root))
    if mode == "--changed":
        if len(argv) < 2:
            print("usage: check_doc_refs.py --changed BASE", file=sys.stderr)
            return 2
        return resolve(root, changed_md(root, argv[1]))
    if mode == "--graph":
        print(render_mermaid(root))
        return 0
    if mode == "--write-graph":
        return write_graph(root)
    if mode == "--check-graph":
        return check_graph(root)
    return resolve(root, argv)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
