#!/usr/bin/env bash
# scripts/layering-imports-scan.sh — host transport for layering-imports gate.
#
# Enumerates leading `import <module>` lines from std/ and extdeps/ layer roots
# into an ephemeral manifest (module v2.test.workflow.host_layering_import_manifest).
# Replaces the deleted tools/layering_imports_scan Rust host (#5048).
#
# Usage: layering-imports-scan.sh <repo_root> <manifest_path>

set -euo pipefail

ROOT="${1:?repo_root required}"
MANIFEST="${2:?manifest path required}"

mkdir -p "$(dirname "$MANIFEST")"

dag_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

first_fact=1

append_fact() {
  local layer="$1"
  local path="$2"
  local mod="$3"
  local esc_path esc_mod
  esc_path=$(dag_escape "$path")
  esc_mod=$(dag_escape "$mod")
  if [ "$first_fact" -eq 1 ]; then
    first_fact=0
  else
    printf ',\n' >>"$MANIFEST.tmp"
  fi
  printf '  LayerImportFact {\n    layer: %s,\n    path: "%s",\n    import_module: "%s"\n  }' \
    "$layer" "$esc_path" "$esc_mod" >>"$MANIFEST.tmp"
}

scan_root() {
  local layer="$1"
  local rel="$2"
  local base="$ROOT/$rel"
  [ -d "$base" ] || return 0
  local f relpath line mod
  while IFS= read -r f; do
    relpath="${f#"$ROOT"/}"
    while IFS= read -r line; do
      mod=$(printf '%s' "$line" | sed -n 's/^[[:space:]]*import[[:space:]]\+\([A-Za-z0-9_.]\+\).*/\1/p')
      [ -n "$mod" ] || continue
      append_fact "$layer" "$relpath" "$mod"
    done < <(grep -E '^[[:space:]]*import[[:space:]]+[A-Za-z0-9_.]+' "$f" 2>/dev/null || true)
  done < <(find "$base" -type f -name '*.dag' | sort)
}

: >"$MANIFEST.tmp"
{
  printf '%s\n' '// GENERATED by scripts/layering-imports-scan.sh — ephemeral. DO NOT COMMIT.'
  printf '%s\n' 'module v2.test.workflow.host_layering_import_manifest'
  printf '%s\n' ''
  printf '%s\n' 'import v2.std.collection { List }'
  printf '%s\n' 'import v2.lens.layering_imports { LayerExtdeps, LayerImportFact, LayerStd }'
  printf '%s\n' ''
  printf '%s\n' 'data host_layer_import_facts: List<LayerImportFact> = ['
} >>"$MANIFEST.tmp"

scan_root LayerStd src/v2/std
scan_root LayerStd dsl/std
scan_root LayerExtdeps src/v2/extdeps
scan_root LayerExtdeps dsl/extdeps

printf '\n]\n' >>"$MANIFEST.tmp"
mv "$MANIFEST.tmp" "$MANIFEST"
