#!/usr/bin/env bash
# Regenerate stage0 using the v2 compiler (self-compile).
#
# This replaces the v1 assemble_stage0 binary. The v2 compiler compiles
# its own .dag source to produce new stage0 Rust code.
#
# Usage: ./scripts/regenerate-stage0.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STAGE0_DIR="$ROOT/src/v2/stage0"

echo "=== Building stage0 (v2-compiler) ==="
cargo build -p v2-compiler --release

# Use `cargo run` to invoke the binary — this works regardless of whether
# cargo is native or containerized (via Docker wrapper in ~/ctrl/scripts/cargo).
# Direct binary path ($ROOT/target/release/v2-compiler) fails when cargo
# runs in a Docker container with a volume-mounted target directory.
STAGE0_CMD="cargo run -p v2-compiler --release --"

# Prepare sources and output under the workspace root so the Docker
# container (which mounts the workspace) can access them.
SOURCES_DIR="$ROOT/.regen-sources"
OUTPUT_DIR="$ROOT/.regen-output"
rm -rf "$SOURCES_DIR" "$OUTPUT_DIR"
mkdir -p "$SOURCES_DIR" "$OUTPUT_DIR"
trap "rm -rf $SOURCES_DIR $OUTPUT_DIR" EXIT

# Copy v2 compiler .dag files
for f in "$ROOT"/src/v2/*.dag; do
    cp "$f" "$SOURCES_DIR/"
done

# Copy language extdeps
for lang in rust python go; do
    mkdir -p "$SOURCES_DIR/dsl/extdeps/languages/$lang"
    cp "$ROOT/dsl/extdeps/languages/$lang/emit.dag" "$SOURCES_DIR/dsl/extdeps/languages/$lang/"
done

# Copy std types and their transitive imports
mkdir -p "$SOURCES_DIR/dsl/std"
cp "$ROOT/dsl/std/types.dag" "$SOURCES_DIR/dsl/std/"
cp "$ROOT/dsl/std/algebra.dag" "$SOURCES_DIR/dsl/std/"
cp "$ROOT/dsl/std/syntax.dag" "$SOURCES_DIR/dsl/std/"

# Copy dag language extdep (imported by tokenize and parse)
mkdir -p "$SOURCES_DIR/dsl/extdeps/languages/dag"
cp "$ROOT/dsl/extdeps/languages/dag/syntax.dag" "$SOURCES_DIR/dsl/extdeps/languages/dag/"

echo "=== Compiling .dag source with v2 compiler ==="
$STAGE0_CMD compile --source-dir "$SOURCES_DIR" --output-dir "$OUTPUT_DIR"

# Generate lib.rs from emitted modules + hand-maintained extras
{
    echo '// Generated by v2 compiler -- do not edit.'
    echo ''
    echo '#![allow(unused_imports, unused_variables, unused_mut, unused_parens, dead_code, unreachable_patterns, non_shorthand_field_patterns, suspicious_double_ref_op, clippy::all)]'
    echo ''
    # Declare all compiler-generated modules
    for f in "$OUTPUT_DIR"/src/*.rs; do
        mod=$(basename "$f" .rs)
        [ "$mod" = "lib" ] && continue
        [ "$mod" = "main" ] && continue
        echo "pub mod $mod;"
    done
    # Hand-maintained modules
    echo 'pub mod v2_rt;'
    echo ''
    echo '#[cfg(test)]'
    echo 'mod generated_tests;'
} > "$OUTPUT_DIR/src/lib.rs"

# Copy hand-maintained files from committed stage0
cp "$STAGE0_DIR/src/v2_rt.rs" "$OUTPUT_DIR/src/v2_rt.rs" 2>/dev/null || true
cp "$STAGE0_DIR/src/generated_tests.rs" "$OUTPUT_DIR/src/generated_tests.rs" 2>/dev/null || true

echo "=== Copying to stage0 ==="
for f in "$OUTPUT_DIR"/src/*.rs; do
    cp "$f" "$STAGE0_DIR/src/$(basename "$f")"
done

echo "=== Verifying stage0 compiles ==="
if cargo check -p v2-compiler 2>&1 | tail -5; then
    echo "=== Done. Stage0 regenerated via v2 self-compile. ==="
else
    echo ""
    echo "=== Stage0 has compilation errors. ==="
    cargo check -p v2-compiler 2>&1 | grep "^error" | wc -l
    echo " errors remaining."
    exit 1
fi
