// Generated by v2 compiler -- do not edit.
// Source module: std.syntax

use std::collections::HashMap;
use std::rc::Rc;
use crate::v2_rt;
use crate::NonEmptyVec;
use crate::NonEmptyBTreeSet;
use BinOp::*;
use LiteralValue::*;
use BodyKind::*;
use ItemFormKind::*;

#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum BinOp {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Eq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
    And,
    Or,
    NullCoalesce,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum LiteralValue {
    LitStr {
        value: String,
    },
    LitInt {
        value: i64,
    },
    LitFloat {
        value: String,
    },
    LitBool {
        value: bool,
    },
    LitNull,
}

#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum BodyKind {
    ExprBody,
    BlockBody,
    TypeBody,
    ValueBody,
    NoBody,
    ServiceBody,
    ResourceBody,
}

#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "_variant")]
pub enum ItemFormKind {
    FuncForm,
    StructForm,
    EnumForm,
    TypeAliasForm,
    ModuleForm,
    OtherForm,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ItemForm {
    pub kind: ItemFormKind,
    pub keyword: String,
    pub has_type_params: bool,
    pub has_params: bool,
    pub has_return_type: bool,
    pub return_required: bool,
    pub has_uses: bool,
    pub body_kind: BodyKind,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct OperatorSpec {
    pub symbol: String,
    pub left_bp: i64,
    pub right_bp: i64,
    pub binop: Option<BinOp>,
    pub algebra_field: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SyntaxSpec {
    pub item_forms: Rc<Vec<Rc<ItemForm>>>,
    pub operators: Rc<Vec<Rc<OperatorSpec>>>,
    pub keyword_literals: Rc<HashMap<String, Rc<LiteralValue>>>,
    pub keyword_set: Rc<HashMap<String, bool>>,
}
