// Generated by v2 compiler -- do not edit.
// Source module: v2.compiler.infer_method

use std::collections::HashMap;
use std::rc::Rc;
use crate::v2_rt;
use crate::NonEmptyVec;
use crate::NonEmptyBTreeSet;
pub use crate::std_types::{SourceSpan};
pub use crate::v2_std_core::{Node, make_span, with_optional_cardinality, unit_type, bool_type, string_type, int_type, InferredNode, Connective, Cardinality, ExprData};
use crate::v2_std_core::InferredNode::{TypeVariable, Resolved};
use crate::v2_std_core::Connective::{NoConnective};
use crate::v2_std_core::Cardinality::{Required};
use crate::v2_std_core::ExprData::{NoExprData};
pub use crate::v2_compiler_infer_types::{make_container_type, make_map_type};

pub fn type_variable_node(id: String) -> Rc<Node> {
    Rc::new(Node {
    name: "".to_string(),
    span: make_span(0, 0),
    ident_span: None,
    children: Rc::new(vec![]),
    connective: Connective::NoConnective,
    params: Rc::new(vec![]),
    inferred: Some(Rc::new(InferredNode::TypeVariable {
    id: id,
})),
    return_cardinality: Cardinality::Required,
    uses: Rc::new(vec![]),
    body: None,
    transport: None,
    properties: Rc::new(vec![]),
    type_annotation: None,
    is_self_recursive: false,
    has_non_tail_self_call: false,
    match_pattern: None,
    expr_data: Rc::new(ExprData::NoExprData),
})
}

pub fn map_of_type_variables() -> Rc<Node> {
    make_map_type(type_variable_node("map_key".to_string()), type_variable_node("map_value".to_string()))
}

pub fn list_of_type_variable(id: String) -> Rc<Node> {
    make_container_type("List".to_string(), type_variable_node(id))
}

pub fn list_of_element(element: Rc<Node>) -> Rc<Node> {
    make_container_type("List".to_string(), element)
}

pub fn seed_node_map(key: String, value: Rc<Node>) -> Rc<HashMap<String, Rc<Node>>> {
    v2_rt::rc_map_insert(v2_rt::rc_empty_map::<Rc<Node>>(), key, value)
}

pub fn builtin_function_registry() -> Rc<HashMap<String, Rc<Node>>> {
    {
        let m = seed_node_map("count".to_string(), int_type());
let m = v2_rt::rc_map_insert(m.clone(), "string_length".to_string(), int_type());
let m = v2_rt::rc_map_insert(m.clone(), "code_point".to_string(), int_type());
let m = v2_rt::rc_map_insert(m.clone(), "to_int".to_string(), int_type());
let m = v2_rt::rc_map_insert(m.clone(), "scan_while".to_string(), int_type());
let m = v2_rt::rc_map_insert(m.clone(), "scan_string_end".to_string(), int_type());
let m = v2_rt::rc_map_insert(m.clone(), "scan_to_eol".to_string(), int_type());
let m = v2_rt::rc_map_insert(m.clone(), "skip_horizontal_ws".to_string(), int_type());
let m = v2_rt::rc_map_insert(m.clone(), "parse_int".to_string(), with_optional_cardinality(&int_type()));
let m = v2_rt::rc_map_insert(m.clone(), "char_at".to_string(), string_type());
let m = v2_rt::rc_map_insert(m.clone(), "substring".to_string(), string_type());
let m = v2_rt::rc_map_insert(m.clone(), "from_code_point".to_string(), string_type());
let m = v2_rt::rc_map_insert(m.clone(), "chars_to_string".to_string(), string_type());
let m = v2_rt::rc_map_insert(m.clone(), "to_string".to_string(), string_type());
let m = v2_rt::rc_map_insert(m.clone(), "concat".to_string(), string_type());
let m = v2_rt::rc_map_insert(m.clone(), "map_insert".to_string(), map_of_type_variables());
let m = v2_rt::rc_map_insert(m.clone(), "map_merge".to_string(), map_of_type_variables());
let m = v2_rt::rc_map_insert(m.clone(), "with".to_string(), map_of_type_variables());
let m = v2_rt::rc_map_insert(m.clone(), "map_contains_key".to_string(), bool_type());
let m = v2_rt::rc_map_insert(m.clone(), "map_has".to_string(), bool_type());
let m = v2_rt::rc_map_insert(m.clone(), "emit_map_has".to_string(), bool_type());
let m = v2_rt::rc_map_insert(m.clone(), "lookup".to_string(), with_optional_cardinality(&type_variable_node("map_value".to_string())));
let m = v2_rt::rc_map_insert(m.clone(), "map_get".to_string(), with_optional_cardinality(&type_variable_node("map_value".to_string())));
let m = v2_rt::rc_map_insert(m.clone(), "Some".to_string(), with_optional_cardinality(&type_variable_node("some_inner".to_string())));
let m = v2_rt::rc_map_insert(m.clone(), "map_keys".to_string(), list_of_type_variable("collection_element".to_string()));
let m = v2_rt::rc_map_insert(m.clone(), "map_values".to_string(), list_of_type_variable("collection_element".to_string()));
let m = v2_rt::rc_map_insert(m.clone(), "reverse".to_string(), list_of_type_variable("collection_element".to_string()));
let m = v2_rt::rc_map_insert(m.clone(), "list_push".to_string(), list_of_type_variable("collection_element".to_string()));
m.clone()
}
}

pub fn infer_builtin_call_type(name: String) -> Option<Rc<Node>> {
    v2_rt::map_get(&builtin_function_registry(), name)
}

pub fn resolve_builtin_call_type(name: String) -> Rc<Node> {
    match infer_builtin_call_type(name) {
    Some(v) => v.clone(),
    None => unit_type(),
}
}
