// Generated by v2 compiler -- do not edit.
// Source module: v2.compiler.infer_lookup

use std::collections::HashMap;
use std::rc::Rc;
use crate::v2_rt;

#[derive(Debug, Clone, PartialEq)]
pub struct NonEmptyVec<T>(Vec<T>);

impl<T> NonEmptyVec<T> {
    pub fn new(items: Vec<T>) -> Result<Self, &'static str> {
        if items.is_empty() {
            Err("NonEmptyVec requires at least one element")
        } else {
            Ok(Self(items))
        }
    }

    pub fn as_slice(&self) -> &[T] {
        &self.0
    }

    pub fn into_vec(self) -> Vec<T> {
        self.0
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct NonEmptyBTreeSet<T: Ord>(std::collections::BTreeSet<T>);

impl<T: Ord> NonEmptyBTreeSet<T> {
    pub fn new(items: std::collections::BTreeSet<T>) -> Result<Self, &'static str> {
        if items.is_empty() {
            Err("NonEmptyBTreeSet requires at least one element")
        } else {
            Ok(Self(items))
        }
    }

    pub fn as_set(&self) -> &std::collections::BTreeSet<T> {
        &self.0
    }

    pub fn into_set(self) -> std::collections::BTreeSet<T> {
        self.0
    }
}
pub use crate::v2_std_core::{Node, param_node_type_expr, InferredNode, NodeType, Cardinality, MethodSemantics, FieldAccessStyle, FieldValueShape, FieldSummary, with_optional_cardinality, with_required_cardinality, Connective};
use crate::v2_std_core::InferredNode::{Resolved, TypeVariable};
use crate::v2_std_core::NodeType::{Typed, InferError, InferVariable, Untyped};
use crate::v2_std_core::Cardinality::{Required, CardOptional};
use crate::v2_std_core::MethodSemantics::{PlainMethodSemantics, AlgebraMethodSemantics, ServiceMethodSemantics};
use crate::v2_std_core::FieldAccessStyle::{OptionalUnwrap};
use crate::v2_std_core::FieldValueShape::{PlainValue, OptionalValue};
use crate::v2_std_core::Connective::{Conj, Disj, NoConnective};
pub use crate::std_algebra::{CollectionSizeEffect, CostShape, AlgebraFieldTemplate, kernel_algebra_profile, algebra_templates_for_profile};
use crate::std_algebra::CollectionSizeEffect::*;
use crate::std_algebra::CostShape::*;
pub use crate::v2_compiler_infer_types::{child_inferred_or_name, nominal_type_ref, normalize_access_type_node, node_is_keyed_collection, method_receiver_element_node, rt_type, rt_node, emit_map_has, enrich_kernel_type};
pub use crate::v2_compiler_infer_env::{TypeEnv, TypeBinding, is_recursive_type, lookup_type, lookup_type_for};
pub use crate::v2_compiler_infer_emit_info::{build_struct_field_summaries, build_enum_field_summaries};
pub use crate::v2_compiler_infer_sigs::{ResolvedFuncSig, ResolvedFuncEnv};
pub use crate::v2_compiler_infer_service::{OpEntry, ServiceMethodResult, check_service_method_call_node};

pub fn is_type_variable(inferred: Rc<InferredNode>) -> bool {
    match (*inferred).clone() {
    InferredNode::TypeVariable { .. } => true,
    _ => false,
}
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct KnownMethodResolution {
    pub semantics: Option<Rc<MethodSemantics>>,
    pub result_type: Option<Rc<Node>>,
}

pub fn lookup_in_scope(locals: Rc<HashMap<String, Rc<TypeBinding>>>, name: String) -> Option<Rc<Node>> {
    match v2_rt::map_get(&locals, name) {
    Some(binding) => Some(binding.resolved.clone()),
    None => None,
}
}

pub fn lookup_func_sig(func_env: Rc<ResolvedFuncEnv>, name: String) -> Option<Rc<ResolvedFuncSig>> {
    v2_rt::map_get(&func_env.signatures.clone(), name)
}

pub fn lookup_field_type_node(n: Rc<Node>, field_name: String) -> Option<Rc<Node>> {
    stacker::maybe_grow(512 * 1024, 2 * 1024 * 1024, || {
        {
            let is_optional = (n.return_cardinality.clone() == Cardinality::CardOptional);
if is_optional {
                {
                    let inner = with_required_cardinality(n.clone());
if (field_name.clone().as_str() == "value".to_string().as_str()) {
                        Some(inner)
} else {
                        match lookup_field_type_node(inner, field_name.clone()) {
    Some(inner_result) => Some(with_optional_cardinality(inner_result.clone())),
    None => None,
}
}
}
} else {
                {
                    let has_structure = (n.connective.clone() != Connective::NoConnective);
if has_structure {
                        {
                            let is_product = (n.connective.clone() == Connective::Conj);
if is_product {
                                match Rc::new({ let mut __result = Vec::new(); for c in n.children.clone().iter().cloned() { if (c.name.clone().as_str() == field_name.clone().as_str()) { __result.push(c); } } __result }).first().cloned() {
    Some(field_child) => Some(child_inferred_or_name(field_child.clone())),
    None => None,
}
} else {
                                lookup_coproduct_common_field_node(n.children.clone(), field_name.clone())
}
}
} else {
                        None
}
}
}
}
    })
}

pub fn lookup_coproduct_common_field_node(variants: Rc<Vec<Rc<Node>>>, field_name: String) -> Option<Rc<Node>> {
    {
        let found_in_all = { let mut __all = true; for v in variants.clone().iter().cloned() { if !({ let mut __found = false; for c in v.children.clone().iter().cloned() { if (c.name.clone().as_str() == field_name.clone().as_str()) { __found = true; break; } } __found }) { __all = false; break; } } __all };
let first_field = if found_in_all {
            match variants.clone().first().cloned() {
    Some(first_variant) => Rc::new({ let mut __result = Vec::new(); for c in first_variant.children.clone().iter().cloned() { if (c.name.clone().as_str() == field_name.clone().as_str()) { __result.push(c); } } __result }).first().cloned(),
    None => None,
}
} else {
            None
};
match first_field {
    Some(field_child) => Some(child_inferred_or_name(field_child.clone())),
    None => None,
}
}
}

pub fn resolve_scrutinee_type_node(env: Rc<TypeEnv>, n: Rc<Node>) -> Rc<Node> {
    resolve_scrutinee_type_node_seen(env, n, v2_rt::rc_empty_map::<bool>())
}

pub fn resolve_scrutinee_type_node_seen(env: Rc<TypeEnv>, n: Rc<Node>, seen: Rc<HashMap<String, bool>>) -> Rc<Node> {
    stacker::maybe_grow(512 * 1024, 2 * 1024 * 1024, || {
        {
            let n_is_type_var = if (n.inferred.clone() != None) {
                is_type_variable(n.inferred.clone().clone().unwrap())
} else {
                false
};
if n_is_type_var {
                return n.clone()
}
let normed = normalize_access_type_node(n.clone());
if ((normed.connective.clone() == Connective::NoConnective) && ((normed.children.clone().len() as i64) == 0)) {
                {
                    let canonical = normed.name.clone();
if (normed.inferred.clone() != None) {
                        {
                            let next_seen = if (canonical.clone().as_str() == "".to_string().as_str()) {
                                seen.clone()
} else {
                                v2_rt::rc_map_insert(seen.clone(), canonical.clone(), true)
};
match (*rt_node(normed.clone())).clone() {
    NodeType::Typed { node: target, .. } => if ((((target.name.clone().as_str() == normed.name.clone().as_str()) && (target.inferred.clone() == None)) && (target.connective.clone() == Connective::NoConnective)) && ((target.children.clone().len() as i64) == 0)) {
                                normed.clone()
} else {
                                resolve_scrutinee_type_node_seen(env.clone(), target.clone(), next_seen)
},
    NodeType::InferError { .. } => normed.clone(),
    NodeType::InferVariable { .. } => normed.clone(),
    NodeType::Untyped => normed.clone(),
}
}
} else {
                        if ((canonical.clone().as_str() != "".to_string().as_str()) && emit_map_has(seen.clone(), canonical.clone())) {
                            nominal_type_ref(normed.name.clone())
} else {
                            {
                                let next_seen = if (canonical.clone().as_str() == "".to_string().as_str()) {
                                    seen.clone()
} else {
                                    v2_rt::rc_map_insert(seen.clone(), canonical.clone(), true)
};
match lookup_type_for(env.clone(), normed.clone()) {
    Some(resolved) => if ((((resolved.name.clone().as_str() == normed.name.clone().as_str()) && (resolved.inferred.clone() == None)) && (resolved.connective.clone() == Connective::NoConnective)) && ((resolved.children.clone().len() as i64) == 0)) {
                                    normed.clone()
} else {
                                    {
                                        let result = resolve_scrutinee_type_node_seen(env.clone(), resolved.clone(), next_seen);
let is_optional = (normed.return_cardinality.clone() == Cardinality::CardOptional);
if is_optional {
                                            with_optional_cardinality(result)
} else {
                                            result
}
}
},
    None => normed.clone(),
}
}
}
}
}
} else {
                normed.clone()
}
}
    })
}

pub fn map_value_type_in_env(type_node: Rc<Node>, env: Rc<TypeEnv>) -> Option<Rc<Node>> {
    {
        let normed = normalize_access_type_node(type_node);
let resolved = resolve_scrutinee_type_node(env, normed);
let map_type = normalize_access_type_node(resolved);
if (node_is_keyed_collection(map_type.clone()) && ((map_type.children.clone().len() as i64) >= 2)) {
            match map_type.children.clone().get(1 as usize).cloned() {
    Some(value_type) => Some(value_type.clone()),
    None => None,
}
} else {
            None
}
}
}

pub fn map_key_type_in_env(type_node: Rc<Node>, env: Rc<TypeEnv>) -> Option<Rc<Node>> {
    {
        let normed = normalize_access_type_node(type_node);
let resolved = resolve_scrutinee_type_node(env, normed);
let map_type = normalize_access_type_node(resolved);
if (node_is_keyed_collection(map_type.clone()) && ((map_type.children.clone().len() as i64) >= 1)) {
            match map_type.children.clone().first().cloned() {
    Some(key_type) => Some(key_type.clone()),
    None => None,
}
} else {
            None
}
}
}

pub fn field_summary_for_type(base_type: Rc<Node>, env: Rc<TypeEnv>, field: String) -> Option<Rc<FieldSummary>> {
    stacker::maybe_grow(512 * 1024, 2 * 1024 * 1024, || {
        {
            let resolved = resolve_scrutinee_type_node(env.clone(), base_type);
let normed = normalize_access_type_node(resolved.clone());
let normed_opt = (normed.return_cardinality.clone() == Cardinality::CardOptional);
if ((field.clone().as_str() == "value".to_string().as_str()) && normed_opt.clone()) {
                Some(Rc::new(FieldSummary {
    access_style: FieldAccessStyle::OptionalUnwrap,
    value_shape: FieldValueShape::PlainValue,
}))
} else {
                if normed_opt.clone() {
                    {
                        let inner = with_required_cardinality(normed.clone());
match field_summary_for_type(inner, env.clone(), field.clone()) {
    Some(inner_summary) => Some(Rc::new(FieldSummary {
    access_style: inner_summary.access_style.clone(),
    value_shape: FieldValueShape::OptionalValue,
})),
    None => None,
}
}
} else {
                    {
                        let no_structure = (resolved.connective.clone() == Connective::NoConnective);
if no_structure {
                            None
} else {
                            {
                                let is_product = (resolved.connective.clone() == Connective::Conj);
if is_product {
                                    v2_rt::map_get(&build_struct_field_summaries(resolved.children.clone()), field.clone())
} else {
                                    v2_rt::map_get(&build_enum_field_summaries(resolved.children.clone()), field.clone())
}
}
}
}
}
}
}
    })
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct MethodFieldResult {
    pub field_node: Rc<Node>,
    pub result_type: Rc<Node>,
    pub size_effect: Option<CollectionSizeEffect>,
    pub cost_shape: Option<Rc<CostShape>>,
    pub algebra_template: Option<Rc<AlgebraFieldTemplate>>,
}

pub fn lookup_field_in_product(product: Rc<Node>, method_name: String) -> Option<Rc<MethodFieldResult>> {
    {
        let matching = Rc::new({ let mut __result = Vec::new(); for c in product.children.clone().iter().cloned() { if (c.name.clone().as_str() == method_name.clone().as_str()) { __result.push(c); } } __result });
match matching.first().cloned() {
    Some(field) => match field.inferred.clone().as_deref().cloned() {
    Some(InferredNode::Resolved { node: rt, .. }) => if ((rt.params.clone().len() as i64) > 0) {
            match rt.inferred.clone().as_deref().cloned() {
    Some(InferredNode::Resolved { node: return_type, .. }) => Some(Rc::new(MethodFieldResult {
    field_node: field.clone(),
    result_type: return_type.clone(),
    size_effect: None,
    cost_shape: None,
    algebra_template: None,
})),
    _ => Some(Rc::new(MethodFieldResult {
    field_node: field.clone(),
    result_type: rt.clone(),
    size_effect: None,
    cost_shape: None,
    algebra_template: None,
})),
}
} else {
            Some(Rc::new(MethodFieldResult {
    field_node: field.clone(),
    result_type: rt.clone(),
    size_effect: None,
    cost_shape: None,
    algebra_template: None,
}))
},
    _ => None,
},
    None => None,
}
}
}

pub fn lookup_structural_method(receiver_type: Rc<Node>, method_name: String) -> Option<Rc<MethodFieldResult>> {
    {
        let is_product = (receiver_type.connective.clone() == Connective::Conj);
if is_product {
            {
                let direct = lookup_field_in_product(receiver_type.clone(), method_name.clone());
match direct.clone() {
    Some(_) => direct.clone(),
    None => None,
}
}
} else {
            {
                let enriched = enrich_kernel_type(receiver_type.name.clone(), receiver_type.clone());
if ((enriched.connective.clone() == Connective::Conj) && ((enriched.children.clone().len() as i64) > 0)) {
                    {
                        let base_result = lookup_field_in_product(enriched.clone(), method_name.clone());
match base_result.clone() {
    Some(mfr) => {
                            let profile = v2_rt::map_get(&kernel_algebra_profile(), receiver_type.name.clone());
let template_match = match profile {
    Some(p) => {
                                let templates = algebra_templates_for_profile(p.clone());
Rc::new({ let mut __result = Vec::new(); for t in templates.iter().cloned() { if (t.name.clone().as_str() == method_name.clone().as_str()) { __result.push(t); } } __result }).first().cloned()
},
    None => None,
};
match template_match {
    Some(t) => Some(Rc::new(MethodFieldResult {
    field_node: mfr.field_node.clone(),
    result_type: mfr.result_type.clone(),
    size_effect: t.size_effect.clone(),
    cost_shape: t.cost_shape.clone(),
    algebra_template: Some(t.clone()),
})),
    None => base_result.clone(),
}
},
    None => None,
}
}
} else {
                    None
}
}
}
}
}

pub fn resolve_known_method_node(receiver: Rc<Node>, receiver_type: Rc<Node>, method_name: String, fold_accumulator_type: Option<Rc<Node>>, service_registry: Rc<HashMap<String, Rc<Vec<Rc<OpEntry>>>>>) -> Rc<KnownMethodResolution> {
    {
        let tier0_result = lookup_structural_method(receiver_type.clone(), method_name.clone());
match tier0_result {
    Some(mfr) => {
            let semantics = Rc::new(MethodSemantics::AlgebraMethodSemantics {
    method_def: mfr.field_node.clone(),
    fold_accumulator_type: fold_accumulator_type,
    size_effect: mfr.size_effect.clone(),
    cost_shape: mfr.cost_shape.clone(),
    algebra_template: mfr.algebra_template.clone(),
});
Rc::new(KnownMethodResolution {
    semantics: Some(semantics),
    result_type: Some(mfr.result_type.clone()),
})
},
    None => match check_service_method_call_node(receiver_type.clone(), method_name.clone(), service_registry) {
    Some(svc_result) => Rc::new(KnownMethodResolution {
    semantics: Some(Rc::new(MethodSemantics::ServiceMethodSemantics {
    service_name: receiver_type.name.clone(),
    op_params: svc_result.op_params.clone(),
})),
    result_type: Some(svc_result.result_type.clone()),
}),
    None => Rc::new(KnownMethodResolution {
    semantics: None,
    result_type: None,
}),
},
}
}
}
