//! Library surface for [`gen_gunbc_ci_workflow_dag`](crate) — shared by the CLI binary and
//! `v3-compiler` integration tests (byte-identical drift gate vs `dsl/gunbc/ci_github_actions_workflow.dag`).

use serde_yaml::Value;

/// Full `.dag` module text (including header comments). `source_path_in_header` is echoed in the
/// `@generated` line and must match the committed path when checking drift (for example
/// `.github/workflows/ci.yml`).
pub fn emit_ci_github_actions_workflow_module(
    source_path_in_header: &str,
    raw_yaml: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    let v: Value = serde_yaml::from_str(raw_yaml)?;
    let body = emit_workflow(&v)?;
    let mut out = String::new();
    out.push_str(&format!(
        "// @generated by tools/gen_gunbc_ci_workflow_dag — source: {source_path_in_header}\n"
    ));
    out.push_str(
        "// Regenerate: CTRL_BUILD_WRAP_CARGO=0 cargo run -q -p gen_gunbc_ci_workflow_dag -- .github/workflows/ci.yml > dsl/gunbc/ci_github_actions_workflow.dag\n",
    );
    out.push('\n');
    out.push_str("module gunbc.ci.github_actions_workflow\n");
    out.push('\n');
    out.push_str("import extdeps.github.actions {\n");
    out.push_str("  Workflow, Job, Step, RunStep, UsesStep, ActionRef,\n");
    out.push_str("  WorkflowTrigger, Push, PullRequest,\n");
    out.push_str("  PullRequestActivity, Opened, Synchronize, Reopened, ReadyForReview, Closed,\n");
    out.push_str("  WorkflowPermissions, PermRead, PermWrite, PermNone,\n");
    out.push_str("  ConcurrencySpec, ConcurrencyMappingQueueNotMax,\n");
    out.push_str("  CancelInProgressSpec, CancelInProgressBool,\n");
    out.push_str("  HostedRunner, SelfHosted, RunsOnExpression,\n");
    out.push_str("  RunnerLabel, UbuntuLatest,\n");
    out.push_str("  ShellType, Bash\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str(&format!(
        "data gunbc_ci_github_actions_workflow: Workflow = {body}\n"
    ));
    Ok(out)
}

fn emit_workflow(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let m = v.as_mapping().ok_or("workflow root must be mapping")?;
    let name = str_field(m, "name")?;
    let on = emit_triggers(m.get("on").ok_or("missing on:")?)?;
    let concurrency = emit_concurrency(m.get("concurrency"))?;
    let jobs = emit_jobs(m.get("jobs").ok_or("missing jobs:")?)?;
    let env = emit_env_map(m.get("env"))?;
    let permissions = emit_permissions(m.get("permissions"))?;
    Ok(format!(
        "{{\n  name: {},\n  on: {},\n  concurrency: {},\n  jobs: {},\n  env: {},\n  permissions: {}\n}}",
        dag_string(&name),
        on,
        concurrency,
        jobs,
        env,
        permissions
    ))
}

fn str_field(m: &serde_yaml::Mapping, k: &str) -> Result<String, Box<dyn std::error::Error>> {
    m.get(Value::String(k.to_string()))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .ok_or_else(|| format!("missing string field {k}").into())
}

fn dag_string(s: &str) -> String {
    format!("{:?}", s)
}

fn emit_triggers(on: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let m = on.as_mapping().ok_or("on: must be mapping")?;
    let mut parts: Vec<String> = Vec::new();
    for (k, v) in m {
        let key = k.as_str().ok_or("on: key must be string")?;
        match key {
            "push" => parts.push(emit_push(v)?),
            "pull_request" => parts.push(emit_pull_request(v)?),
            other => return Err(format!("unsupported on.{other}").into()),
        }
    }
    if parts.is_empty() {
        return Err("on: must contain at least one trigger".into());
    }
    Ok(emit_list_literal(&parts))
}

fn emit_push(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let m = v.as_mapping().ok_or("push: mapping")?;
    let branches = string_list_opt(m.get("branches"))?;
    let paths = string_list_opt(m.get("paths"))?;
    Ok(format!(
        "Push {{ branches: {}, paths: {} }}",
        branches, paths
    ))
}

fn emit_pull_request(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let m = v.as_mapping().ok_or("pull_request: mapping")?;
    let branches = string_list_opt(m.get("branches"))?;
    let types = pr_types_list(m.get("types"))?;
    Ok(format!(
        "PullRequest {{ branches: {}, types: {} }}",
        branches, types
    ))
}

fn string_list_opt(v: Option<&Value>) -> Result<String, Box<dyn std::error::Error>> {
    let Some(v) = v else {
        return Ok("[]".to_string());
    };
    let seq = v.as_sequence().ok_or("expected sequence")?;
    let mut xs: Vec<String> = Vec::new();
    for it in seq {
        let s = it.as_str().ok_or("sequence of strings")?;
        xs.push(dag_string(s));
    }
    Ok(emit_list_literal(&xs))
}

fn pr_types_list(v: Option<&Value>) -> Result<String, Box<dyn std::error::Error>> {
    let Some(v) = v else {
        return Ok("[]".to_string());
    };
    let seq = v.as_sequence().ok_or("types must be sequence")?;
    let mut arms: Vec<String> = Vec::new();
    for it in seq {
        let s = it.as_str().ok_or("pr type string")?;
        let arm = match s {
            "opened" => "Opened",
            "synchronize" => "Synchronize",
            "reopened" => "Reopened",
            "ready_for_review" => "ReadyForReview",
            "closed" => "Closed",
            _ => return Err(format!("unknown pull_request type {s}").into()),
        };
        arms.push(arm.to_string());
    }
    Ok(emit_list_literal(&arms))
}

fn emit_list_literal(items: &[String]) -> String {
    if items.is_empty() {
        "[]".to_string()
    } else {
        format!("[{}]", items.join(", "))
    }
}

fn emit_concurrency(v: Option<&Value>) -> Result<String, Box<dyn std::error::Error>> {
    let Some(v) = v else {
        return Ok("none".to_string());
    };
    let m = v.as_mapping().ok_or("concurrency mapping")?;
    let group = str_field(m, "group")?;
    let cip = m.get(Value::String("cancel-in-progress".to_string()));
    let cancel = match cip {
        None => "none".to_string(),
        Some(Value::Bool(true)) => {
            "Some { value: CancelInProgressBool { value: true } }".to_string()
        }
        Some(Value::Bool(false)) => {
            "Some { value: CancelInProgressBool { value: false } }".to_string()
        }
        Some(other) => return Err(format!("unsupported cancel-in-progress: {other:?}").into()),
    };
    Ok(format!(
        "Some {{\n  value: ConcurrencyMappingQueueNotMax {{\n      group: {},\n      cancel_in_progress: {},\n      explicit_single: none\n    }}\n  }}",
        dag_string(&group),
        cancel
    ))
}

fn emit_env_map(v: Option<&Value>) -> Result<String, Box<dyn std::error::Error>> {
    emit_optional_string_map(v)
}

fn emit_optional_string_map(v: Option<&Value>) -> Result<String, Box<dyn std::error::Error>> {
    let Some(v) = v else {
        return Ok("none".to_string());
    };
    let m = v
        .as_mapping()
        .ok_or("optional string map must be a YAML mapping")?;
    if m.is_empty() {
        return Ok("none".to_string());
    }
    Ok(format!("Some {{ value: {} }}", string_map_literal_body(v)?))
}

fn string_map_literal_body(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let m = v.as_mapping().ok_or("map")?;
    if m.is_empty() {
        return Err("internal: string_map_literal_body on empty map".into());
    }
    let mut inner = String::new();
    for (k, val) in m {
        let k = k.as_str().ok_or("map key must be string")?;
        let vs = yaml_scalar_to_dag_string(val)?;
        let key_expr = dag_string(k);
        if !inner.is_empty() {
            inner.push_str(", ");
        }
        inner.push_str(&format!("{key_expr}: {vs}"));
    }
    Ok(format!("{{ {inner} }}"))
}

fn yaml_scalar_to_dag_string(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    Ok(match v {
        Value::String(s) => dag_string(s),
        Value::Bool(b) => dag_string(&b.to_string()),
        Value::Number(n) => dag_string(&n.to_string()),
        // Fail closed: `null` in a string-valued Actions slot is not a faithful scalar — do not
        // fabricate `""` (INVARIANTS P3/M5). Omit the key in YAML or emit an explicit string.
        Value::Null => {
            return Err("YAML null is not a representable GitHub Actions string scalar".into());
        }
        _ => return Err(format!("unsupported scalar {v:?}").into()),
    })
}

fn emit_permissions(v: Option<&Value>) -> Result<String, Box<dyn std::error::Error>> {
    let Some(v) = v else {
        return Ok("none".to_string());
    };
    let m = v.as_mapping().ok_or("permissions mapping")?;
    let contents = perm_level(m.get("contents"))?;
    let pull_requests = perm_level(m.get("pull-requests"))?;
    let issues = perm_level(m.get("issues"))?;
    let actions = perm_level(m.get("actions"))?;
    Ok(format!(
        "Some {{\n  value: {{\n      contents: {},\n      pull_requests: {},\n      issues: {},\n      actions: {}\n    }}\n  }}",
        contents, pull_requests, issues, actions
    ))
}

fn perm_level(v: Option<&Value>) -> Result<&'static str, Box<dyn std::error::Error>> {
    let Some(v) = v else {
        return Ok("PermNone");
    };
    let s = v.as_str().ok_or("permission level string")?;
    match s {
        "read" => Ok("PermRead"),
        "write" => Ok("PermWrite"),
        "none" => Ok("PermNone"),
        _ => Err(format!("unknown permission {s}").into()),
    }
}

fn emit_jobs(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let m = v.as_mapping().ok_or("jobs mapping")?;
    let mut job_exprs: Vec<String> = Vec::new();
    for (k, job) in m {
        let id = k.as_str().ok_or("job id key must be string")?;
        job_exprs.push(emit_job(id, job)?);
    }
    Ok(emit_list_literal(&job_exprs))
}

fn emit_job(id: &str, v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let m = v.as_mapping().ok_or("job mapping")?;
    let name = match m.get(Value::String("name".to_string())) {
        None => "none".to_string(),
        Some(Value::String(s)) => format!("Some {{ value: {} }}", dag_string(s)),
        Some(_) => return Err("job name must be string".into()),
    };
    let runner = emit_runs_on(m.get("runs-on").ok_or("runs-on")?)?;
    let steps = emit_steps(m.get("steps").ok_or("steps")?)?;
    let needs = emit_needs_list(m.get("needs"))?;
    let env = emit_optional_string_map(m.get(Value::String("env".to_string())))?;
    let outputs = emit_optional_string_map(m.get(Value::String("outputs".to_string())))?;
    let if_condition = match m.get(Value::String("if".to_string())) {
        None => "none".to_string(),
        Some(i) => format!("Some {{ value: {} }}", yaml_scalar_to_dag_string(i)?),
    };
    let strategy = match m.get(Value::String("strategy".to_string())) {
        None => "none".to_string(),
        Some(_) => return Err("matrix strategy not supported by generator yet".into()),
    };
    let timeout_minutes = match m.get(Value::String("timeout-minutes".to_string())) {
        None => "none".to_string(),
        Some(Value::Number(n)) => {
            let v = if let Some(u) = n.as_u64() {
                u.to_string()
            } else if let Some(i) = n.as_i64() {
                i.to_string()
            } else {
                return Err("timeout-minutes number".into());
            };
            format!("Some {{ value: {v} }}")
        }
        Some(_) => return Err("timeout-minutes must be number".into()),
    };
    let continue_on_error = match m.get(Value::String("continue-on-error".to_string())) {
        None => "false".to_string(),
        Some(Value::Bool(b)) => b.to_string(),
        Some(_) => return Err("continue-on-error must be bool".into()),
    };
    let job_concurrency = match m.get(Value::String("concurrency".to_string())) {
        None => "none".to_string(),
        Some(_) => return Err("job-level concurrency not supported".into()),
    };
    Ok(format!(
        "{{\n      id: {},\n      name: {},\n      runner: {},\n      steps: {},\n      needs: {},\n      env: {},\n      outputs: {},\n      if_condition: {},\n      strategy: {},\n      timeout_minutes: {},\n      continue_on_error: {},\n      concurrency: {}\n    }}",
        dag_string(id),
        name,
        runner,
        steps,
        needs,
        env,
        outputs,
        if_condition,
        strategy,
        timeout_minutes,
        continue_on_error,
        job_concurrency
    ))
}

fn emit_runs_on(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let s = v.as_str().ok_or("runs-on string")?;
    if s.starts_with("${{") {
        return Ok(format!(
            "RunsOnExpression {{ expression: {} }}",
            dag_string(s)
        ));
    }
    match s {
        "ubuntu-latest" => Ok("HostedRunner { label: UbuntuLatest }".to_string()),
        _ => Ok(format!("SelfHosted {{ labels: [{}] }}", dag_string(s))),
    }
}

fn emit_needs_list(v: Option<&Value>) -> Result<String, Box<dyn std::error::Error>> {
    let Some(v) = v else {
        return Ok("[]".to_string());
    };
    let seq = v.as_sequence().ok_or("needs sequence")?;
    let mut xs: Vec<String> = Vec::new();
    for it in seq {
        let s = it.as_str().ok_or("needs string")?;
        xs.push(dag_string(s));
    }
    Ok(emit_list_literal(&xs))
}

fn emit_steps(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let seq = v.as_sequence().ok_or("steps sequence")?;
    let mut steps: Vec<String> = Vec::new();
    for st in seq {
        steps.push(emit_step(st)?);
    }
    Ok(emit_list_literal(&steps))
}

fn emit_step(v: &Value) -> Result<String, Box<dyn std::error::Error>> {
    let m = v.as_mapping().ok_or("step mapping")?;
    let name = match m.get(Value::String("name".to_string())) {
        None => "none".to_string(),
        Some(Value::String(s)) => format!("Some {{ value: {} }}", dag_string(s)),
        Some(_) => return Err("step name".into()),
    };
    let id = match m.get(Value::String("id".to_string())) {
        None => "none".to_string(),
        Some(Value::String(s)) => format!("Some {{ value: {} }}", dag_string(s)),
        Some(_) => return Err("step id".into()),
    };
    let if_condition = match m.get(Value::String("if".to_string())) {
        None => "none".to_string(),
        Some(i) => format!("Some {{ value: {} }}", yaml_scalar_to_dag_string(i)?),
    };
    let continue_on_error = match m.get(Value::String("continue-on-error".to_string())) {
        None => "false".to_string(),
        Some(Value::Bool(b)) => b.to_string(),
        Some(_) => return Err("continue-on-error bool".into()),
    };
    let timeout_minutes = match m.get(Value::String("timeout-minutes".to_string())) {
        None => "none".to_string(),
        Some(Value::Number(n)) => {
            let v = if let Some(u) = n.as_u64() {
                u.to_string()
            } else if let Some(i) = n.as_i64() {
                i.to_string()
            } else {
                return Err("timeout".into());
            };
            format!("Some {{ value: {v} }}")
        }
        Some(_) => return Err("timeout-minutes".into()),
    };
    if let Some(uses) = m.get(Value::String("uses".to_string())) {
        let uses_s = uses.as_str().ok_or("uses string")?;
        let ar = emit_action_ref(uses_s)?;
        let with = emit_optional_string_map(m.get(Value::String("with".to_string())))?;
        let env = emit_optional_string_map(m.get(Value::String("env".to_string())))?;
        Ok(format!(
            "UsesStep {{\n          name: {},\n          id: {},\n          uses: {},\n          with: {},\n          env: {},\n          if_condition: {},\n          continue_on_error: {},\n          timeout_minutes: {}\n        }}",
            name,
            id,
            ar,
            with,
            env,
            if_condition,
            continue_on_error,
            timeout_minutes
        ))
    } else if let Some(run) = m.get(Value::String("run".to_string())) {
        let run_s = run.as_str().ok_or("run string")?;
        let env = emit_optional_string_map(m.get(Value::String("env".to_string())))?;
        let wd = match m.get(Value::String("working-directory".to_string())) {
            None => "none".to_string(),
            Some(w) => format!("Some {{ value: {} }}", yaml_scalar_to_dag_string(w)?),
        };
        Ok(format!(
            "RunStep {{\n          name: {},\n          id: {},\n          run: {},\n          shell: Bash,\n          env: {},\n          working_directory: {},\n          if_condition: {},\n          continue_on_error: {},\n          timeout_minutes: {}\n        }}",
            name,
            id,
            dag_string(run_s),
            env,
            wd,
            if_condition,
            continue_on_error,
            timeout_minutes
        ))
    } else {
        Err("step must have uses or run".into())
    }
}

fn emit_action_ref(uses: &str) -> Result<String, Box<dyn std::error::Error>> {
    let (owner_repo, ref_part) = uses.rsplit_once('@').ok_or("uses must contain @")?;
    let (owner, repo) = owner_repo.split_once('/').ok_or("uses owner/repo")?;
    Ok(format!(
        "{{ owner: {}, repo: {}, ref: {} }}",
        dag_string(owner),
        dag_string(repo),
        dag_string(ref_part)
    ))
}
