// seed-linked pilot lib — gunbc-emitted closure modules + v2_std_text shim
#![allow(clippy::all, dead_code, unused_imports)]
#![recursion_limit = "256"]

pub mod extdeps_cache_catalog_io;
pub mod extdeps_cache_catalog_placement;
pub mod extdeps_cache_materialization;
pub mod extdeps_cache_types;
pub mod extdeps_external_authority;
pub mod extdeps_realization_compile_stage_memo;
pub mod extdeps_realization_parse_table_memo;
pub mod extdeps_uri;
pub mod std_algebra;
pub mod std_cache_identity;
pub mod std_cache_interface;
pub mod std_content_hash;
pub mod std_decl_ref;
pub mod std_disposition;
pub mod std_effects;
pub mod std_error_primitives;
pub mod std_execution_mode;
pub mod std_http_path;
pub mod std_logic;
pub mod std_magnitude;
pub mod std_materialization_ladder;
pub mod std_measure;
pub mod std_nat;
pub mod std_pareto;
pub mod std_realization;
pub mod std_realization_measurement;
pub mod std_realization_schedule;
pub mod std_realization_width;
pub mod std_types;
pub mod std_verification;
pub mod v1_rt;
pub mod v2_compiler_materialization_carriers;
pub mod v2_std_algebra;
pub mod v2_std_diagnostic;
pub mod v2_std_node;
pub mod v2_std_staging;
pub mod v2_std_text;

pub use v1_compiler::NonEmptyBTreeSet;
pub use v1_compiler::NonEmptyVec;
