use std::collections::{HashMap, HashSet};
use std::env;
use std::fs;

use gunbc_contracts::{BlockContract, PatternContract};
use gunbc_spec::{DomainSpec, InputPortSpec, OutputPortSpec, PortBehaviorSpec, ToolSpec};
use gunbc_test::{Cardinality, ProducesCase};

fn main() {
    let out_path = match parse_out_path() {
        Ok(path) => path,
        Err(msg) => {
            eprintln!("{msg}");
            std::process::exit(2);
        }
    };

    let tools = vec![
        gunbc_gistgen::behavior::tool_spec(),
        gunbc_makegen::behavior::tool_spec(),
    ];

    let mut errors = Vec::new();
    for tool in &tools {
        validate_tool_spec(tool, &mut errors);
    }

    if !errors.is_empty() {
        eprintln!("gunbc-testgen failed with {} error(s):", errors.len());
        for err in errors {
            eprintln!("  - {err}");
        }
        std::process::exit(1);
    }

    let content = "// GENERATED by gunbc-testgen\n";
    if let Err(e) = fs::write(&out_path, content) {
        eprintln!("failed to write {out_path}: {e}");
        std::process::exit(1);
    }
}

fn parse_out_path() -> Result<String, String> {
    let mut args = env::args().skip(1);
    match (args.next(), args.next()) {
        (Some(flag), Some(path)) if flag == "--out" => Ok(path),
        _ => Err("usage: gunbc-testgen --out <path>".into()),
    }
}

fn validate_tool_spec(tool: &ToolSpec, errors: &mut Vec<String>) {
    let type_domains = build_type_domain_map(tool, errors);
    let block_map = build_block_map(tool, errors);
    let port_spec_map = build_port_spec_maps(tool, errors);

    for pattern in &tool.patterns {
        validate_pattern(
            tool,
            pattern,
            &type_domains,
            &block_map,
            &port_spec_map,
            errors,
        );
    }
}

fn build_type_domain_map(
    tool: &ToolSpec,
    errors: &mut Vec<String>,
) -> HashMap<String, DomainSpec> {
    let mut map = HashMap::new();
    for (type_id, domain) in &tool.type_domains {
        if map.insert(type_id.0.to_string(), *domain).is_some() {
            errors.push(format!(
                "[{}] duplicate type domain for '{}'",
                tool.tool_name, type_id.0
            ));
        }
    }
    map
}

fn build_block_map<'a>(
    tool: &'a ToolSpec,
    errors: &mut Vec<String>,
) -> HashMap<&'a str, &'a BlockContract> {
    let mut map = HashMap::new();
    for block in &tool.blocks {
        if map.insert(block.id.as_str(), block).is_some() {
            errors.push(format!(
                "[{}] duplicate block id '{}'",
                tool.tool_name, block.id
            ));
        }
    }
    map
}

fn build_port_spec_maps<'a>(
    tool: &'a ToolSpec,
    errors: &mut Vec<String>,
) -> PortSpecMaps<'a> {
    let mut inputs = HashMap::new();
    let mut outputs = HashMap::new();
    for spec in &tool.ports {
        match spec {
            PortBehaviorSpec::Input(input) => {
                let key = port_key(input.node.0, input.port.0);
                if inputs.insert(key, input).is_some() {
                    errors.push(format!(
                        "[{}] duplicate input spec for {}.{}",
                        tool.tool_name, input.node.0, input.port.0
                    ));
                }
            }
            PortBehaviorSpec::Output(output) => {
                let key = port_key(output.node.0, output.port.0);
                if outputs.insert(key, output).is_some() {
                    errors.push(format!(
                        "[{}] duplicate output spec for {}.{}",
                        tool.tool_name, output.node.0, output.port.0
                    ));
                }
            }
        }
    }
    PortSpecMaps { inputs, outputs }
}

fn validate_pattern(
    tool: &ToolSpec,
    pattern: &PatternContract,
    type_domains: &HashMap<String, DomainSpec>,
    block_map: &HashMap<&str, &BlockContract>,
    port_spec_map: &PortSpecMaps,
    errors: &mut Vec<String>,
) {
    let mut slot_map: HashMap<&str, &BlockContract> = HashMap::new();
    for slot in &pattern.slots {
        let block = match block_map.get(slot.block_id.as_str()) {
            Some(b) => *b,
            None => {
                errors.push(format!(
                    "[{}:{}] unknown block '{}'",
                    tool.tool_name, pattern.name, slot.block_id
                ));
                continue;
            }
        };
        slot_map.insert(slot.node_id.0.as_str(), block);
    }

    let wired_inputs: HashSet<(String, String)> = pattern
        .edges
        .iter()
        .map(|e| (e.to_node.0.clone(), e.to_port.0.clone()))
        .collect();

    let mut node_infos: HashMap<String, NodeInfo> = HashMap::new();
    for slot in &pattern.slots {
        if let Some(block) = slot_map.get(slot.node_id.0.as_str()) {
            let node_id = slot.node_id.0.clone();
            let mut inputs = HashMap::new();
            for input in &block.inputs {
                let spec = match find_input_spec(port_spec_map, &node_id, &input.name.0) {
                    Some(s) => s,
                    None => {
                        errors.push(format!(
                            "[{}:{}] missing port spec for input {}.{}",
                            tool.tool_name, pattern.name, node_id, input.name.0
                        ));
                        continue;
                    }
                };

                let base_domain = match derive_domain(
                    tool,
                    &input.type_id.0,
                    input.optional,
                    spec.domain_override,
                    type_domains,
                ) {
                    Ok(d) => d,
                    Err(e) => {
                        errors.push(format!(
                            "[{}:{}] {}",
                            tool.tool_name, pattern.name, e
                        ));
                        continue;
                    }
                };

                let is_wired = wired_inputs.contains(&(node_id.clone(), input.name.0.clone()));
                let effective_cards = match effective_domain_cards(
                    tool,
                    pattern,
                    &node_id,
                    &input.name.0,
                    base_domain,
                    is_wired,
                ) {
                    Ok(cards) => cards,
                    Err(e) => {
                        errors.push(format!(
                            "[{}:{}] {}",
                            tool.tool_name, pattern.name, e
                        ));
                        continue;
                    }
                };

                let (accepts, rejects) = accepts_rejects_for(spec, &effective_cards);
                inputs.insert(
                    input.name.0.clone(),
                    InputPortInfo {
                        name: input.name.0.clone(),
                        domain_cards: effective_cards,
                        accepts,
                        rejects,
                    },
                );
            }

            let mut outputs = HashMap::new();
            for output in &block.outputs {
                let spec = match find_output_spec(port_spec_map, &node_id, &output.name.0) {
                    Some(s) => s,
                    None => {
                        errors.push(format!(
                            "[{}:{}] missing port spec for output {}.{}",
                            tool.tool_name, pattern.name, node_id, output.name.0
                        ));
                        continue;
                    }
                };

                let output_domain = match derive_domain(
                    tool,
                    &output.type_id.0,
                    output.optional,
                    spec.domain_override,
                    type_domains,
                ) {
                    Ok(d) => d,
                    Err(e) => {
                        errors.push(format!(
                            "[{}:{}] {}",
                            tool.tool_name, pattern.name, e
                        ));
                        continue;
                    }
                };

                let produces = build_produces_map(spec.produces);

                let info = OutputPortInfo {
                    name: output.name.0.clone(),
                    driver_input: spec.driver_input.map(|s| s.0.to_string()),
                    produces,
                    downstream: Vec::new(),
                };

                validate_output_domain(
                    tool,
                    pattern,
                    &info,
                    output_domain,
                    errors,
                );

                outputs.insert(output.name.0.clone(), info);
            }

            node_infos.insert(node_id, NodeInfo { inputs, outputs });
        }
    }

    for edge in &pattern.edges {
        let from_block = match slot_map.get(edge.from_node.0.as_str()) {
            Some(b) => *b,
            None => {
                errors.push(format!(
                    "[{}:{}] unknown from node '{}'",
                    tool.tool_name, pattern.name, edge.from_node.0
                ));
                continue;
            }
        };
        let to_block = match slot_map.get(edge.to_node.0.as_str()) {
            Some(b) => *b,
            None => {
                errors.push(format!(
                    "[{}:{}] unknown to node '{}'",
                    tool.tool_name, pattern.name, edge.to_node.0
                ));
                continue;
            }
        };

        let from_port = match from_block
            .outputs
            .iter()
            .find(|p| p.name == edge.from_port)
        {
            Some(p) => p,
            None => {
                errors.push(format!(
                    "[{}:{}] missing output port {}.{}",
                    tool.tool_name, pattern.name, edge.from_node.0, edge.from_port.0
                ));
                continue;
            }
        };

        let to_port = match to_block
            .inputs
            .iter()
            .find(|p| p.name == edge.to_port)
        {
            Some(p) => p,
            None => {
                errors.push(format!(
                    "[{}:{}] missing input port {}.{}",
                    tool.tool_name, pattern.name, edge.to_node.0, edge.to_port.0
                ));
                continue;
            }
        };

        let output_spec = match find_output_spec(
            port_spec_map,
            &edge.from_node.0,
            &edge.from_port.0,
        ) {
            Some(s) => s,
            None => {
                errors.push(format!(
                    "[{}:{}] missing port spec for output {}.{}",
                    tool.tool_name, pattern.name, edge.from_node.0, edge.from_port.0
                ));
                continue;
            }
        };

        let input_spec = match find_input_spec(
            port_spec_map,
            &edge.to_node.0,
            &edge.to_port.0,
        ) {
            Some(s) => s,
            None => {
                errors.push(format!(
                    "[{}:{}] missing port spec for input {}.{}",
                    tool.tool_name, pattern.name, edge.to_node.0, edge.to_port.0
                ));
                continue;
            }
        };

        let output_domain = match derive_domain(
            tool,
            &from_port.type_id.0,
            from_port.optional,
            output_spec.domain_override,
            type_domains,
        ) {
            Ok(d) => d,
            Err(e) => {
                errors.push(format!(
                    "[{}:{}] {}",
                    tool.tool_name, pattern.name, e
                ));
                continue;
            }
        };

        let input_domain = match derive_domain(
            tool,
            &to_port.type_id.0,
            to_port.optional,
            input_spec.domain_override,
            type_domains,
        ) {
            Ok(d) => d,
            Err(e) => {
                errors.push(format!(
                    "[{}:{}] {}",
                    tool.tool_name, pattern.name, e
                ));
                continue;
            }
        };

        let is_wired = wired_inputs.contains(&(edge.to_node.0.clone(), edge.to_port.0.clone()));
        let input_effective_cards = match effective_domain_cards(
            tool,
            pattern,
            &edge.to_node.0,
            &edge.to_port.0,
            input_domain,
            is_wired,
        ) {
            Ok(cards) => cards,
            Err(e) => {
                errors.push(format!(
                    "[{}:{}] {}",
                    tool.tool_name, pattern.name, e
                ));
                continue;
            }
        };
        let (input_accepts, input_rejects) = accepts_rejects_for(input_spec, &input_effective_cards);

        let node = node_infos
            .get_mut(edge.from_node.0.as_str())
            .expect("node should exist");
        let output_info = match node.outputs.get_mut(edge.from_port.0.as_str()) {
            Some(info) => info,
            None => {
                errors.push(format!(
                    "[{}:{}] output {}.{} missing output spec info",
                    tool.tool_name, pattern.name, edge.from_node.0, edge.from_port.0
                ));
                continue;
            }
        };

        output_info.downstream.push(DownstreamInfo {
            node_id: edge.to_node.0.clone(),
            port: edge.to_port.0.clone(),
            accepts: input_accepts.clone(),
            rejects: input_rejects.clone(),
        });

        validate_output_domain(
            tool,
            pattern,
            output_info,
            output_domain,
            errors,
        );

        validate_accepts_domain(
            tool,
            pattern,
            edge.to_node.0.as_str(),
            edge.to_port.0.as_str(),
            &input_effective_cards,
            &input_accepts,
            &input_rejects,
            errors,
        );
    }

    prove_pattern(tool, pattern, &node_infos, errors);
}

fn validate_output_domain(
    tool: &ToolSpec,
    pattern: &PatternContract,
    output_info: &OutputPortInfo,
    domain: DomainSpec,
    errors: &mut Vec<String>,
) {
    let domain_set: HashSet<Cardinality> = domain.cardinalities().iter().copied().collect();
    for cases in output_info.produces.values() {
        for case in cases {
            if let ProducesCase::Ok(card) = case {
                if !domain_set.contains(card) {
                    errors.push(format!(
                        "[{}:{}] output {} produces {:?} outside domain {:?}",
                        tool.tool_name, pattern.name, output_info.name, card, domain
                    ));
                }
            }
        }
    }
}

fn validate_accepts_domain(
    tool: &ToolSpec,
    pattern: &PatternContract,
    node_id: &str,
    port: &str,
    domain_cards: &[Cardinality],
    accepts: &HashSet<Cardinality>,
    rejects: &HashSet<Cardinality>,
    errors: &mut Vec<String>,
) {
    let domain_set: HashSet<Cardinality> = domain_cards.iter().copied().collect();
    let mut covered = HashSet::new();
    covered.extend(accepts.iter().copied());
    covered.extend(rejects.iter().copied());
    if !domain_set.is_subset(&covered) {
        errors.push(format!(
            "[{}:{}] input {}.{} does not fully cover effective domain {:?}",
            tool.tool_name, pattern.name, node_id, port, domain_cards
        ));
    }
}

fn prove_pattern(
    tool: &ToolSpec,
    pattern: &PatternContract,
    node_infos: &HashMap<String, NodeInfo>,
    errors: &mut Vec<String>,
) {
    for (node_id, node) in node_infos {
        let inputs: Vec<&InputPortInfo> = node.inputs.values().collect();

        for output in node.outputs.values() {
            if output.driver_input.is_none() && !inputs.is_empty() {
                errors.push(format!(
                    "[{}:{}] output {}.{} missing driver input",
                    tool.tool_name, pattern.name, node_id, output.name
                ));
            }
            if let Some(driver) = &output.driver_input {
                if let Some(input) = node.inputs.get(driver) {
                    for card in &input.domain_cards {
                        if !output.produces.contains_key(card) {
                            errors.push(format!(
                                "[{}:{}] output {}.{} missing produces case for {:?}",
                                tool.tool_name, pattern.name, node_id, output.name, card
                            ));
                        }
                    }
                }
            }
        }

        let mut current = HashMap::new();
        walk_combinations(&inputs, 0, &mut current, &mut |combo| {
            for input in &inputs {
                let card = combo.get(&input.name).unwrap();
                if !input.accepts.contains(card) && !input.rejects.contains(card) {
                    errors.push(format!(
                        "[{}:{}] {}.{} does not handle {:?}",
                        tool.tool_name, pattern.name, node_id, input.name, card
                    ));
                }
            }

            for output in node.outputs.values() {
                if let Some(driver) = &output.driver_input {
                    let driver_card = match combo.get(driver) {
                        Some(c) => c,
                        None => {
                            errors.push(format!(
                                "[{}:{}] output {}.{} missing driver input '{}'",
                                tool.tool_name, pattern.name, node_id, output.name, driver
                            ));
                            continue;
                        }
                    };
                    let cases = match output.produces.get(driver_card) {
                        Some(cases) => cases,
                        None => continue,
                    };
                    check_cases(
                        tool,
                        pattern,
                        node_id,
                        output,
                        cases,
                        errors,
                    );
                } else {
                    for cases in output.produces.values() {
                        check_cases(
                            tool,
                            pattern,
                            node_id,
                            output,
                            cases,
                            errors,
                        );
                    }
                }
            }
        });
    }
}

fn walk_combinations<F: FnMut(&HashMap<String, Cardinality>)>(
    inputs: &[&InputPortInfo],
    idx: usize,
    current: &mut HashMap<String, Cardinality>,
    f: &mut F,
) {
    if idx >= inputs.len() {
        f(current);
        return;
    }

    let input = inputs[idx];
    for card in &input.domain_cards {
        current.insert(input.name.clone(), *card);
        walk_combinations(inputs, idx + 1, current, f);
    }
}

fn check_cases(
    tool: &ToolSpec,
    pattern: &PatternContract,
    node_id: &str,
    output: &OutputPortInfo,
    cases: &[ProducesCase],
    errors: &mut Vec<String>,
) {
    for case in cases {
        let out_card = match case {
            ProducesCase::Ok(card) => card,
            ProducesCase::Err => continue,
        };

        for downstream in &output.downstream {
            if downstream.rejects.contains(out_card) {
                continue;
            }
            if downstream.accepts.contains(out_card) {
                continue;
            }
            errors.push(format!(
                "[{}:{}] edge {}.{} -> {}.{} does not handle {:?}",
                tool.tool_name,
                pattern.name,
                node_id,
                output.name,
                downstream.node_id,
                downstream.port,
                out_card
            ));
        }
    }
}

fn build_produces_map(
    produces: fn() -> Vec<(Cardinality, ProducesCase)>,
) -> HashMap<Cardinality, Vec<ProducesCase>> {
    let mut map: HashMap<Cardinality, Vec<ProducesCase>> = HashMap::new();
    for (input_card, case) in produces() {
        map.entry(input_card).or_default().push(case);
    }
    map
}

fn derive_domain(
    tool: &ToolSpec,
    type_id: &str,
    optional: bool,
    override_domain: Option<DomainSpec>,
    type_domains: &HashMap<String, DomainSpec>,
) -> Result<DomainSpec, String> {
    if let Some(domain) = override_domain {
        return Ok(domain);
    }
    let base = type_domains.get(type_id).copied().ok_or_else(|| {
        format!(
            "[{}] missing domain for type '{}'",
            tool.tool_name, type_id
        )
    })?;
    if optional {
        match base {
            DomainSpec::Scalar => Ok(DomainSpec::OptionalScalar),
            DomainSpec::Collection => Ok(DomainSpec::OptionalCollection),
            DomainSpec::OptionalScalar | DomainSpec::OptionalCollection => Ok(base),
        }
    } else {
        Ok(base)
    }
}

fn effective_domain_cards(
    tool: &ToolSpec,
    pattern: &PatternContract,
    node_id: &str,
    port: &str,
    base_domain: DomainSpec,
    wired: bool,
) -> Result<Vec<Cardinality>, String> {
    let mut cards: Vec<Cardinality> = base_domain.cardinalities().to_vec();
    if wired {
        cards.retain(|c| *c != Cardinality::Null);
        if cards.is_empty() {
            return Err(format!(
                "[{}:{}] input {}.{} has empty effective domain",
                tool.tool_name, pattern.name, node_id, port
            ));
        }
        Ok(cards)
    } else {
        if cards.contains(&Cardinality::Null) {
            Ok(vec![Cardinality::Null])
        } else {
            Err(format!(
                "[{}:{}] input {}.{} is unwired but domain {:?} does not allow Null",
                tool.tool_name, pattern.name, node_id, port, base_domain
            ))
        }
    }
}

fn accepts_rejects_for(
    spec: &InputPortSpec,
    domain_cards: &[Cardinality],
) -> (HashSet<Cardinality>, HashSet<Cardinality>) {
    let accepts: HashSet<Cardinality> = if let Some(f) = spec.accepts {
        f().into_iter().collect()
    } else {
        domain_cards.iter().copied().collect()
    };

    let rejects: HashSet<Cardinality> = if let Some(f) = spec.rejects {
        f().into_iter().collect()
    } else {
        let all = [Cardinality::Zero, Cardinality::One, Cardinality::N, Cardinality::Null];
        all.into_iter().filter(|c| !accepts.contains(c)).collect()
    };

    (accepts, rejects)
}

fn port_key(node: &str, port: &str) -> String {
    format!("{node}:{port}")
}

fn find_input_spec<'a>(
    port_spec_map: &'a PortSpecMaps<'a>,
    node: &str,
    port: &str,
) -> Option<&'a InputPortSpec> {
    let key = port_key(node, port);
    port_spec_map.inputs.get(&key).copied()
}

fn find_output_spec<'a>(
    port_spec_map: &'a PortSpecMaps<'a>,
    node: &str,
    port: &str,
) -> Option<&'a OutputPortSpec> {
    let key = port_key(node, port);
    port_spec_map.outputs.get(&key).copied()
}

struct InputPortInfo {
    name: String,
    domain_cards: Vec<Cardinality>,
    accepts: HashSet<Cardinality>,
    rejects: HashSet<Cardinality>,
}

struct PortSpecMaps<'a> {
    inputs: HashMap<String, &'a InputPortSpec>,
    outputs: HashMap<String, &'a OutputPortSpec>,
}

struct OutputPortInfo {
    name: String,
    driver_input: Option<String>,
    produces: HashMap<Cardinality, Vec<ProducesCase>>,
    downstream: Vec<DownstreamInfo>,
}

struct DownstreamInfo {
    node_id: String,
    port: String,
    accepts: HashSet<Cardinality>,
    rejects: HashSet<Cardinality>,
}

struct NodeInfo {
    inputs: HashMap<String, InputPortInfo>,
    outputs: HashMap<String, OutputPortInfo>,
}
