[package]
name = "gunbc-workflow"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Generic workflow planner/executor engine"

[dependencies]
gunbc-ir = { path = "../ir" }
gunbc-exec = { path = "../exec" }
gunbc-infra = { path = "../infra" }
serde = { workspace = true }
serde_json = { workspace = true }
