//! Bootstrap operations.
//!
//! All I/O happens through explicit `TransportOps::Execute` nodes in the DAG.
//! The ops here are PURE (no I/O) - they prepare requests and parse responses.

use gunbc_exec::{ExecError, Executable};
use gunbc_ir::transport::{ShellRequest, TransportRequest, TransportResponse};
use gunbc_ir::Value;
use std::collections::HashMap;

/// Operations for the bootstrap tool.
///
/// All operations are PURE - no I/O. I/O happens via TransportOps::Execute nodes.
#[derive(Debug, Clone)]
pub enum BootstrapOp {
    // ========================================================================
    // ScanWorkspace chain: PrepareScan -> Execute -> ParseScanResult
    // ========================================================================
    /// Prepare workspace scan request (PURE)
    PrepareScanWorkspace,
    /// Parse scan result (PURE)
    ParseScanResult,

    // ========================================================================
    // Pure domain logic
    // ========================================================================
    /// Generate Makefile content (PURE)
    GenerateMakefile,
    /// Generate .gitignore content (PURE)
    GenerateGitignore,
}

impl Executable for BootstrapOp {
    fn execute(&self, inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
        match self {
            BootstrapOp::PrepareScanWorkspace => execute_prepare_scan_workspace(inputs),
            BootstrapOp::ParseScanResult => execute_parse_scan_result(inputs),
            BootstrapOp::GenerateMakefile => execute_generate_makefile(inputs),
            BootstrapOp::GenerateGitignore => execute_generate_gitignore(inputs),
        }
    }
}

// ============================================================================
// PrepareScanWorkspace - PURE (builds TransportRequest)
// ============================================================================

/// Prepare workspace scan request (PURE - no I/O).
fn execute_prepare_scan_workspace(_inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
    // Use find to list directories in crates/
    let request = TransportRequest::Shell(ShellRequest {
        command: "find".to_string(),
        args: vec![
            "crates".to_string(),
            "-maxdepth".to_string(),
            "1".to_string(),
            "-mindepth".to_string(),
            "1".to_string(),
            "-type".to_string(),
            "d".to_string(),
        ],
        cwd: None,
        env: HashMap::new(),
        stdin: None,
    });

    let mut out = HashMap::new();
    out.insert("request".to_string(), Value::Request(request));
    Ok(out)
}

// ============================================================================
// ParseScanResult - PURE (parses TransportResponse)
// ============================================================================

/// Parse scan result (PURE - no I/O).
fn execute_parse_scan_result(inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
    let response = inputs
        .get("response")
        .and_then(|v| v.as_response())
        .ok_or_else(|| ExecError::new("missing or invalid 'response' input"))?;

    let mut crate_names = Vec::new();

    if let TransportResponse::Shell(shell) = response {
        if shell.success() {
            for line in shell.stdout.lines() {
                let line = line.trim();
                if !line.is_empty() {
                    // Extract crate name from path like "crates/foo"
                    if let Some(name) = line.strip_prefix("crates/") {
                        if !name.is_empty() && !name.contains('/') {
                            crate_names.push(name.to_string());
                        }
                    }
                }
            }
        }
    }

    crate_names.sort();

    let mut out = HashMap::new();
    out.insert("crate_count".to_string(), Value::Int(crate_names.len() as i64));
    out.insert("crate_names".to_string(), Value::StrList(crate_names));
    Ok(out)
}

/// Generate Makefile content.
fn execute_generate_makefile(_inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
    let makefile = r#"# Generated by gunbc-bootstrap
# Regenerate with: make bootstrap

.DEFAULT_GOAL := help

.PHONY: help build test lint ci gist buck2 makegen deps bootstrap

help:
	@echo "gunbc - DAG-based code generation framework"
	@echo ""
	@echo "Development:"
	@echo "  build       Build all targets"
	@echo "  test        Run all tests"
	@echo "  lint        Run clippy"
	@echo "  ci          Run full CI pipeline"
	@echo ""
	@echo "Tools:"
	@echo "  gist        Create GitHub gist from code"
	@echo "  buck2       Generate BUCK file"
	@echo "  makegen     Regenerate this Makefile"
	@echo "  deps        Install/check dependencies"
	@echo "  bootstrap   Regenerate all build infrastructure"

build:
	cargo build --all-targets

test:
	cargo test

lint:
	cargo clippy --all-targets -- -D warnings

ci:
	cargo run -p gunbc-ci -- run

gist:
	cargo run -p gunbc-gist -- $(if $(REPO),--repo $(REPO)) $(if $(EXT),-e $(EXT))

gist-dry:
	cargo run -p gunbc-gist -- --dry-run $(if $(REPO),--repo $(REPO))

buck2:
	cargo run -p gunbc-buck2 -- $(if $(INPUT),--input $(INPUT))

buck2-dry:
	cargo run -p gunbc-buck2 -- --dry-run

makegen:
	cargo run -p gunbc-makegen

makegen-dry:
	cargo run -p gunbc-makegen -- --dry-run

deps:
	cargo run -p gunbc-deps -- install

deps-list:
	cargo run -p gunbc-deps -- --list

bootstrap:
	cargo run -p gunbc-bootstrap

bootstrap-dry:
	cargo run -p gunbc-bootstrap -- --dry-run
"#;

    let mut out = HashMap::new();
    out.insert("makefile_content".to_string(), Value::Str(makefile.to_string()));
    Ok(out)
}

/// Generate .gitignore content.
fn execute_generate_gitignore(_inputs: HashMap<String, Value>) -> Result<HashMap<String, Value>, ExecError> {
    let gitignore = r#"# Generated by gunbc-bootstrap

# Rust
/target/
**/*.rs.bk
Cargo.lock

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Build artifacts
*.o
*.a
*.so
*.dylib

# Generated files (keep these tracked)
# Makefile
# .github/workflows/ci.yml
"#;

    let mut out = HashMap::new();
    out.insert("gitignore_content".to_string(), Value::Str(gitignore.to_string()));
    Ok(out)
}

// Mockable implementation for test generation
use gunbc_test::Mockable;

impl Mockable for BootstrapOp {
    fn mock_outputs(&self) -> HashMap<String, Value> {
        match self {
            BootstrapOp::PrepareScanWorkspace => {
                let mut out = HashMap::new();
                out.insert("request".to_string(), Value::Request(TransportRequest::Shell(ShellRequest {
                    command: "find".to_string(),
                    args: vec!["crates".to_string()],
                    cwd: None,
                    env: HashMap::new(),
                    stdin: None,
                })));
                out
            }
            BootstrapOp::ParseScanResult => {
                let mut out = HashMap::new();
                out.insert("crate_count".to_string(), Value::Int(5));
                out.insert("crate_names".to_string(), Value::StrList(vec!["lib-a".to_string(), "lib-b".to_string()]));
                out
            }
            BootstrapOp::GenerateMakefile => {
                let mut out = HashMap::new();
                out.insert("makefile_content".to_string(), Value::Str("# Mock Makefile".to_string()));
                out
            }
            BootstrapOp::GenerateGitignore => {
                let mut out = HashMap::new();
                out.insert("gitignore_content".to_string(), Value::Str("# Mock .gitignore\n/target/".to_string()));
                out
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_makefile() {
        let result = execute_generate_makefile(HashMap::new()).unwrap();

        match result.get("makefile_content") {
            Some(Value::Str(content)) => {
                assert!(content.contains("build:"));
                assert!(content.contains("test:"));
                assert!(content.contains("gist:"));
            }
            _ => panic!("expected makefile content"),
        }
    }

    #[test]
    fn test_generate_gitignore() {
        let result = execute_generate_gitignore(HashMap::new()).unwrap();

        match result.get("gitignore_content") {
            Some(Value::Str(content)) => {
                assert!(content.contains("/target/"));
                assert!(content.contains(".DS_Store"));
            }
            _ => panic!("expected gitignore content"),
        }
    }
}
